### ISSUE TITLE
Bug: Error loading rules when using eslint v9.15.0 with typescript-eslint v8.14.0 

### ISSUE THREAD

**Issue by claudiu-muresan-pfa** [typescript-eslint/typescript-eslint#10355]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Repro Code

```TypeScript
No code
```

### ESLint Config

```javascript
import globals from "globals";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all
});

export default [...compat.extends(
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
), {
    ignores: ["eslint.config.mjs", "cucumber.js"],
    languageOptions: {
        globals: {
            ...globals.node,
        },
        ecmaVersion: "latest",
        sourceType: "module",
        parserOptions: {
            project: true,
            tsconfigRootDir: "__dirname",
        }
    },
    rules: {
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-unsafe-call": "off",
        "@typescript-eslint/no-unsafe-argument": "off",
        "@typescript-eslint/no-unsafe-assignment": "off",
        "@typescript-eslint/no-unsafe-member-access": "off",
        "@typescript-eslint/no-unsafe-return": "off",
    },
}];
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    /* Language and Environment */
    "target": "es2021",
    "types": ["node"],

    /* Modules */
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    
    /* Interop Constraints */
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    /* Type Checking */
    // "strict": true,
    // "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
  },
  "include": ["src/**/*"],
}
```

### Expected Result

No errors when running `eslint` (9.15.0) with latest `typescript-eslint` (v8.14.0). 
Note that same eslint configuration works with `eslint` v9.14.0.

### Actual Result

```
$ /Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/.bin/eslint src --fix
Context FileContext {
  id: '@typescript-eslint/no-unused-expressions',
  options: [],
  report: [Function: report]
}

Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting /Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/src/broker/data.ts
    at Object.create (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/rules/no-unused-expressions.js:76:13)
    at create (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js:28:32)
    at Object.create (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:31:20)
    at createRuleListeners (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/linter/linter.js:944:21)
    at /Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/linter/linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (/Users/claudiumuresan/Projects/WaylayIO-Private/end-to-end-tests-waylay-js/node_modules/eslint/lib/linter/linter.js:2082:21)
error Command failed with exit code 2.
```

I added manually a console.log statement for listing the `context` contents.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`    | `8.14.0` |
| `@eslint/eslintrc`      | `3.2.0` |
| `@eslint/js`                | `9.15.0` |
| `eslint`                       | `9.15.0` |
| `typescript`               | `5.6.3` |
| `node`                        | `18.19.64` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/10338

Please use the search and see the pinned issues before posting.
