### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: anymatch is not a function

### ISSUE THREAD

**Issue by kaiyoma** [typescript-eslint/typescript-eslint#1122]
I'm still trying to figure out what code change caused this, but eslint just started failing for me with this stack trace:

```
(node:33600) UnhandledPromiseRejectionWarning: TypeError: anymatch is not a function
    at FSWatcher._isIgnored (...\node_modules\@typescript-eslint\typescript-estree\node_modules\chokidar\index.js:754:25)
    at NodeFsHandler._addToNodeFs (...\node_modules\@typescript-eslint\typescript-estree\node_modules\chokidar\lib\nodefs-handler.js:570:16)
    at Promise.all.paths.map (...\node_modules\@typescript-eslint\typescript-estree\node_modules\chokidar\index.js:435:47)
    at Array.map (<anonymous>)
    at FSWatcher.add (...\node_modules\@typescript-eslint\typescript-estree\node_modules\chokidar\index.js:434:13)
    at Object.watch (...\node_modules\@typescript-eslint\typescript-estree\node_modules\chokidar\index.js:929:11)
    at watch (...\node_modules\@typescript-eslint\typescript-estree\dist\tsconfig-parser.js:95:31)
    at Object.watchCompilerHost.watchDirectory (...\node_modules\@typescript-eslint\typescript-estree\dist\tsconfig-parser.js:188:29)
    at watchDirectory (...\node_modules\typescript\lib\typescript.js:90832:21)
    at watchDirectory (...\node_modules\typescript\lib\typescript.js:90821:24)
(node:33600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 408)
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `2.4.0` |
| `TypeScript`                           | `3.6.4` |
| `node`                                 | `10.16.0` |
| `npm`                                  | `6.9.0` |

**Comment by kaiyoma** [comment]
And just to be clear, `anymatch` is definitely installed:

```
=> Found "anymatch@2.0.0"
info Reasons this module exists
   - "chokidar" depends on it
   - Hoisted from "chokidar#anymatch"
   - Hoisted from "esprint#sane#anymatch"
   - Hoisted from "webpack-dev-server#chokidar#anymatch"
   - Hoisted from "babel-jest#@jest#transform#jest-haste-map#anymatch"
   - Hoisted from "@typescript-eslint#parser#@typescript-eslint#typescript-estree#chokidar#anymatch"
   - Hoisted from "babel-jest#@jest#transform#jest-haste-map#sane#anymatch"
```

**Comment by bradzacher** [comment]
Please upgrade to v 2.5.0 which was released this morning.
We removed the dependency on chokidar.

**Comment by kaiyoma** [comment]
`yarn install` isn't letting me install that version:

```
yarn install v1.19.1
[1/4] Resolving packages...
Couldn't find any versions for "@typescript-eslint/eslint-plugin" that matches "2.5.0"
? Please choose a version of "@typescript-eslint/eslint-plugin" from this list: (Use arrow keys)
```
