### ISSUE TITLE
[consistent-type-assertions] "TypeError: Missing `message` property in report() call; add a message that describes the linting problem."

### ISSUE THREAD

**Issue by garyking** [typescript-eslint/typescript-eslint#1130]
**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "rules": {
    "@typescript-eslint/consistent-type-assertions": ["error", "never"]
  }
}
```

```TS
const a = 1 as number;
```

**Expected Result**

An error show appear, indicating that `as` is not allowed, due to the `never` option being used.

**Actual Result**

An exception is thrown:

```
[Error - 12:45:05 AM] ESLint stack trace:
[Error - 12:45:05 AM] TypeError: Missing `message` property in report() call; add a message that describes the linting problem.
Occurred while linting test.ts:1
    at args (/usr/local/lib/node_modules/eslint/lib/util/report-translator.js:267:19)
    at Object.report (/usr/local/lib/node_modules/eslint/lib/linter.js:721:41)
    at reportIncorrectAssertionType (/usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-assertions.js:67:21)
    at TSAsExpression (/usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-assertions.js:123:21)
    at listeners.(anonymous function).forEach.listener (/usr/local/lib/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:294:14)
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.5.0` |
| `@typescript-eslint/parser`        | `2.3.3` |
| `TypeScript`                       | `3.6.4` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.12.0` |
| `npm`                              | `6.12.0` |

**Comment by bradzacher** [comment]
Hmm - I'm not sure why eslint lets you use that config, it shouldn't work.

This is the correct config:
```
"@typescript-eslint/consistent-type-assertions": ["error", {"assertionStyle": "never"}]
```

**Comment by garyking** [comment]
Ah, nice catch. Yeah I don't know why I used that.
