### ISSUE TITLE
ESLint: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by yuto0214w** [typescript-eslint/typescript-eslint#1337]
When I try lint the code, parser occur this error:

```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module 'typescript'
Require stack:
- e:\Projects\TypeScript\type\node_modules\@typescript-eslint\typescript-estree\dist\parser.js
- e:\Projects\TypeScript\type\node_modules\@typescript-eslint\parser\dist\parser.js
- e:\Projects\TypeScript\type\node_modules\eslint\lib\cli-engine\config-array-factory.js
- e:\Projects\TypeScript\type\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- e:\Projects\TypeScript\type\node_modules\eslint\lib\cli-engine\cli-engine.js
- e:\Projects\TypeScript\type\node_modules\eslint\lib\cli-engine\index.js
- e:\Projects\TypeScript\type\node_modules\eslint\lib\cli.js
- e:\Projects\TypeScript\type\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (e:\Projects\TypeScript\type\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (e:\Projects\TypeScript\type\node_modules\@typescript-eslint\typescript-estree\dist\parser.js:17:25)
    at Module._compile (e:\Projects\TypeScript\type\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
error Command failed with exit code 2.
```

What should I do?

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.11.0` |
| `TypeScript`                | `3.7.3` |
| `ESLint`                    | `6.7.2` |
| `node`                      | `13.3.0` |
| `npm`                       | `6.13.1` |
| `yarn`                      | `1.21.1` |

**Comment by bradzacher** [comment]
have you installed typescript in your project in such a way that is resolvable from that package?

**Comment by yuto0214w** [comment]
Sorry for late reply.
I forgot install the typescript locally.
I will be careful not to forget that in the future.
Thank you.
