### ISSUE TITLE
Yaml eslintrc file results in error: Failed to load parser 'typescript-eslint/parser'

### ISSUE THREAD

**Issue by nicogreenarry** [typescript-eslint/typescript-eslint#1395]
**Repro**

Here's [a repo](https://github.com/nicogreenarry/eslint-typescript-sandbox) reproducing the issue.

I set it up using the first few [setup instructions](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md).

When I use the js version of the config (rename `.eslintrc.js.disabled` to `.eslintrc.js`, and rename `.eslintrc.yaml` to `.eslintrc.yaml.disabled`) this command runs with no errors: `node_modules/.bin/eslint index.ts`

But if I use the yaml version of the config file, which has all the same values, and run the same command, I get this error:
```
Error: Failed to load parser 'typescript-eslint/parser' declared in '.eslintrc.yaml': Cannot find module 'typescript-eslint/parser'
Require stack:
- /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at Object.resolve (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadParser (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:870:45)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:665:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
```

**Expected Result**
eslint should work regardless of whether my eslint config is in `.eslintrc.js` or `.eslintrc.yaml`.

**Actual Result**
eslint doesn't work when I'm using a yaml file.

**Additional Info**

eslint runs with no errors if I comment out a few lines of the yaml file, so it looks like this:
```
root: true
#parser: typescript-eslint/parser
#plugins:
#  - typescript-eslint
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
```

Did eslint throw an exception? Yes. Debug output:
```
⋊> ~/d/eslint-typescript-sandbox on master ⨯ node_modules/.bin/eslint --debug index.ts                                              00:48:09
  eslint:cli CLI args: [ '--debug', 'index.ts' ] +0ms
  eslint:cli Running on files +3ms
  eslint:config-array-factory Loading JSON config file: /Users/nicogreenarry/dev/eslint-typescript-sandbox/package.json +0ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/node_modules/*', '/bower_components/*' ], basePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox', loose: false } ] +0ms
  eslint:ignore-pattern   processed: { basePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox', patterns: [ '/node_modules/*', '/bower_components/*' ] } +2ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/node_modules/*', '/bower_components/*' ], basePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox', loose: false } ] +0ms
  eslint:ignore-pattern   processed: { basePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox', patterns: [ '/node_modules/*', '/bower_components/*' ] } +0ms
  eslint:file-enumerator Start to iterate files: [ 'index.ts' ] +0ms
  eslint:file-enumerator File: /Users/nicogreenarry/dev/eslint-typescript-sandbox/index.ts +0ms
  eslint:cascading-config-array-factory Load config files for /Users/nicogreenarry/dev/eslint-typescript-sandbox. +0ms
  eslint:cascading-config-array-factory No cache found: /Users/nicogreenarry/dev/eslint-typescript-sandbox. +0ms
  eslint:config-array-factory Loading YAML config file: /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +4ms
  eslint:config-array-factory Config file found: /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +27ms
  eslint:config-array-factory Loading {extends:"eslint:recommended"} relative to /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +3ms
  eslint:config-array-factory Loading JS config file: /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/conf/eslint-recommended.js +0ms
  eslint:config-array-factory Loading {extends:"plugin:@typescript-eslint/eslint-recommended"} relative to /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +1ms
  eslint:config-array-factory Loading plugin "@typescript-eslint" from /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +0ms
  eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@2.14.0 (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +2ms
  eslint:config-array-factory Plugin /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 169ms +169ms
  eslint:config-array-factory Loading {extends:"plugin:@typescript-eslint/recommended"} relative to /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +2ms
  eslint:config-array-factory Loading plugin "@typescript-eslint" from /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +0ms
  eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@2.14.0 (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +0ms
  eslint:config-array-factory Plugin /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 0ms +0ms
  eslint:config-array-factory Loading {extends:"./configs/base.json"} relative to /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslint:config-array-factory package.json was not found: Cannot find module './configs/base.json/package.json'
Require stack:
- /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +1ms
  eslint:config-array-factory Loaded: ./configs/base.json (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json) +0ms
  eslint:config-array-factory Loading JSON config file: /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json +0ms
  eslint:config-array-factory Loading parser "@typescript-eslint/parser" from /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json +0ms
  eslint:config-array-factory Loaded: @typescript-eslint/parser@2.14.0 (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/parser/dist/parser.js) +1ms
  eslint:config-array-factory Loading plugin "@typescript-eslint" from /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json +24ms
  eslint:config-array-factory Loaded: @typescript-eslint/eslint-plugin@2.14.0 (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +0ms
  eslint:config-array-factory Plugin /Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 0ms +0ms
  eslint:config-array-factory Loading parser "typescript-eslint/parser" from /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +1ms
  eslint:config-array-factory Failed to load parser 'typescript-eslint/parser' declared in '.eslintrc.yaml'. +0ms
  eslint:config-array-factory Loading plugin "typescript-eslint" from /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml +0ms
  eslint:config-array-factory Failed to load plugin 'typescript-eslint' declared in '.eslintrc.yaml'. +0ms
  eslint:cascading-config-array-factory Stop traversing because of 'root:true'. +232ms
  eslint:rules Loading rule 'constructor-super' (remaining=274) +0ms
  eslint:rules Loading rule 'for-direction' (remaining=273) +1ms
  eslint:rules Loading rule 'getter-return' (remaining=272) +0ms
  eslint:rules Loading rule 'no-async-promise-executor' (remaining=271) +1ms
  eslint:rules Loading rule 'no-case-declarations' (remaining=270) +1ms
  eslint:rules Loading rule 'no-class-assign' (remaining=269) +0ms
  eslint:rules Loading rule 'no-compare-neg-zero' (remaining=268) +0ms
  eslint:rules Loading rule 'no-cond-assign' (remaining=267) +0ms
  eslint:rules Loading rule 'no-const-assign' (remaining=266) +2ms
  eslint:rules Loading rule 'no-constant-condition' (remaining=265) +0ms
  eslint:rules Loading rule 'no-control-regex' (remaining=264) +2ms
  eslint:rules Loading rule 'no-debugger' (remaining=263) +3ms
  eslint:rules Loading rule 'no-delete-var' (remaining=262) +1ms
  eslint:rules Loading rule 'no-dupe-args' (remaining=261) +0ms
  eslint:rules Loading rule 'no-dupe-class-members' (remaining=260) +0ms
  eslint:rules Loading rule 'no-dupe-keys' (remaining=259) +1ms
  eslint:rules Loading rule 'no-duplicate-case' (remaining=258) +0ms
  eslint:rules Loading rule 'no-empty' (remaining=257) +0ms
  eslint:rules Loading rule 'no-empty-character-class' (remaining=256) +2ms
  eslint:rules Loading rule 'no-empty-pattern' (remaining=255) +0ms
  eslint:rules Loading rule 'no-ex-assign' (remaining=254) +0ms
  eslint:rules Loading rule 'no-extra-boolean-cast' (remaining=253) +1ms
  eslint:rules Loading rule 'no-extra-semi' (remaining=252) +0ms
  eslint:rules Loading rule 'no-fallthrough' (remaining=251) +0ms
  eslint:rules Loading rule 'no-func-assign' (remaining=250) +1ms
  eslint:rules Loading rule 'no-global-assign' (remaining=249) +0ms
  eslint:rules Loading rule 'no-inner-declarations' (remaining=248) +2ms
  eslint:rules Loading rule 'no-invalid-regexp' (remaining=247) +1ms
  eslint:rules Loading rule 'no-irregular-whitespace' (remaining=246) +1ms
  eslint:rules Loading rule 'no-misleading-character-class' (remaining=245) +1ms
  eslint:rules Loading rule 'no-mixed-spaces-and-tabs' (remaining=244) +1ms
  eslint:rules Loading rule 'no-new-symbol' (remaining=243) +1ms
  eslint:rules Loading rule 'no-obj-calls' (remaining=242) +0ms
  eslint:rules Loading rule 'no-octal' (remaining=241) +0ms
  eslint:rules Loading rule 'no-prototype-builtins' (remaining=240) +1ms
  eslint:rules Loading rule 'no-redeclare' (remaining=239) +0ms
  eslint:rules Loading rule 'no-regex-spaces' (remaining=238) +1ms
  eslint:rules Loading rule 'no-self-assign' (remaining=237) +1ms
  eslint:rules Loading rule 'no-shadow-restricted-names' (remaining=236) +1ms
  eslint:rules Loading rule 'no-sparse-arrays' (remaining=235) +1ms
  eslint:rules Loading rule 'no-this-before-super' (remaining=234) +0ms
  eslint:rules Loading rule 'no-undef' (remaining=233) +0ms
  eslint:rules Loading rule 'no-unexpected-multiline' (remaining=232) +1ms
  eslint:rules Loading rule 'no-unreachable' (remaining=231) +1ms
  eslint:rules Loading rule 'no-unsafe-finally' (remaining=230) +0ms
  eslint:rules Loading rule 'no-unsafe-negation' (remaining=229) +0ms
  eslint:rules Loading rule 'no-unused-labels' (remaining=228) +1ms
  eslint:rules Loading rule 'no-unused-vars' (remaining=227) +0ms
  eslint:rules Loading rule 'no-useless-catch' (remaining=226) +2ms
  eslint:rules Loading rule 'no-useless-escape' (remaining=225) +0ms
  eslint:rules Loading rule 'no-with' (remaining=224) +1ms
  eslint:rules Loading rule 'require-yield' (remaining=223) +0ms
  eslint:rules Loading rule 'use-isnan' (remaining=222) +0ms
  eslint:rules Loading rule 'valid-typeof' (remaining=221) +3ms
  eslint:rules Loading rule 'camelcase' (remaining=220) +3ms
  eslint:rules Loading rule 'no-array-constructor' (remaining=219) +8ms
  eslint:rules Loading rule 'no-empty-function' (remaining=218) +1ms
  eslint:rules Loading rule 'no-use-before-define' (remaining=217) +4ms
  eslint:rules Loading rule 'no-var' (remaining=216) +5ms
  eslint:rules Loading rule 'prefer-const' (remaining=215) +0ms
  eslint:rules Loading rule 'prefer-rest-params' (remaining=214) +1ms
  eslint:rules Loading rule 'prefer-spread' (remaining=213) +1ms
  eslint:cascading-config-array-factory Configuration was determined: ConfigArray [ { name: 'DefaultIgnorePattern', filePath: '', criteria: null, env: undefined, globals: undefined, ignorePattern: IgnorePattern { patterns: [Array], basePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox', loose: false }, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: undefined, settings: undefined }, { name: '.eslintrc.yaml » eslint:recommended', filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/conf/eslint-recommended.js', criteria: null, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: { 'constructor-super': 'error', 'for-direction': 'error', 'getter-return': 'error', 'no-async-promise-executor': 'error', 'no-case-declarations': 'error', 'no-class-assign': 'error', 'no-compare-neg-zero': 'error', 'no-cond-assign': 'error', 'no-const-assign': 'error', 'no-constant-condition': 'error', 'no-control-regex': 'error', 'no-debugger': 'error', 'no-delete-var': 'error', 'no-dupe-args': 'error', 'no-dupe-class-members': 'error', 'no-dupe-keys': 'error', 'no-duplicate-case': 'error', 'no-empty': 'error', 'no-empty-character-class': 'error', 'no-empty-pattern': 'error', 'no-ex-assign': 'error', 'no-extra-boolean-cast': 'error', 'no-extra-semi': 'error', 'no-fallthrough': 'error', 'no-func-assign': 'error', 'no-global-assign': 'error', 'no-inner-declarations': 'error', 'no-invalid-regexp': 'error', 'no-irregular-whitespace': 'error', 'no-misleading-character-class': 'error', 'no-mixed-spaces-and-tabs': 'error', 'no-new-symbol': 'error', 'no-obj-calls': 'error', 'no-octal': 'error', 'no-prototype-builtins': 'error', 'no-redeclare': 'error', 'no-regex-spaces': 'error', 'no-self-assign': 'error', 'no-shadow-restricted-names': 'error', 'no-sparse-arrays': 'error', 'no-this-before-super': 'error', 'no-undef': 'error', 'no-unexpected-multiline': 'error', 'no-unreachable': 'error', 'no-unsafe-finally': 'error', 'no-unsafe-negation': 'error', 'no-unused-labels': 'error', 'no-unused-vars': 'error', 'no-useless-catch': 'error', 'no-useless-escape': 'error', 'no-with': 'error', 'require-yield': 'error', 'use-isnan': 'error', 'valid-typeof': 'error' }, settings: undefined }, { name: '.eslintrc.yaml » plugin:@typescript-eslint/eslint-recommended', filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js', criteria: null, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: undefined, settings: undefined }, { name: '.eslintrc.yaml » plugin:@typescript-eslint/eslint-recommended#overrides[0]', filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js', criteria: { includes: [Array], excludes: null, basePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox' }, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: { 'getter-return': 'off', 'no-dupe-args': 'off', 'no-dupe-keys': 'off', 'no-unreachable': 'off', 'valid-typeof': 'off', 'no-const-assign': 'off', 'no-new-symbol': 'off', 'no-this-before-super': 'off', 'no-undef': 'off', 'no-dupe-class-members': 'off', 'no-redeclare': 'off' }, settings: undefined }, { name: '.eslintrc.yaml » plugin:@typescript-eslint/recommended » ./configs/base.json', filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json', criteria: null, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: { error: null, filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/parser/dist/parser.js', id: '@typescript-eslint/parser', importerName: '.eslintrc.yaml » plugin:@typescript-eslint/recommended » ./configs/base.json', importerPath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json' }, parserOptions: { sourceType: 'module' }, plugins: { '@typescript-eslint': [Object] }, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: undefined, settings: undefined }, { name: '.eslintrc.yaml » plugin:@typescript-eslint/recommended', filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/@typescript-eslint/eslint-plugin/dist/index.js', criteria: null, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: { '@typescript-eslint/adjacent-overload-signatures': 'error', '@typescript-eslint/ban-ts-ignore': 'error', '@typescript-eslint/ban-types': 'error', camelcase: 'off', '@typescript-eslint/camelcase': 'error', '@typescript-eslint/class-name-casing': 'error', '@typescript-eslint/consistent-type-assertions': 'error', '@typescript-eslint/explicit-function-return-type': 'warn', '@typescript-eslint/interface-name-prefix': 'error', '@typescript-eslint/member-delimiter-style': 'error', 'no-array-constructor': 'off', '@typescript-eslint/no-array-constructor': 'error', 'no-empty-function': 'off', '@typescript-eslint/no-empty-function': 'error', '@typescript-eslint/no-empty-interface': 'error', '@typescript-eslint/no-explicit-any': 'warn', '@typescript-eslint/no-inferrable-types': 'error', '@typescript-eslint/no-misused-new': 'error', '@typescript-eslint/no-namespace': 'error', '@typescript-eslint/no-non-null-assertion': 'warn', '@typescript-eslint/no-this-alias': 'error', 'no-unused-vars': 'off', '@typescript-eslint/no-unused-vars': 'warn', 'no-use-before-define': 'off', '@typescript-eslint/no-use-before-define': 'error', '@typescript-eslint/no-var-requires': 'error', '@typescript-eslint/prefer-namespace-keyword': 'error', '@typescript-eslint/triple-slash-reference': 'error', '@typescript-eslint/type-annotation-spacing': 'error', 'no-var': 'error', 'prefer-const': 'error', 'prefer-rest-params': 'error', 'prefer-spread': 'error' }, settings: undefined }, { name: '.eslintrc.yaml', filePath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml', criteria: null, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: { error: [Object], filePath: null, id: 'typescript-eslint/parser', importerName: '.eslintrc.yaml', importerPath: '/Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml' }, parserOptions: undefined, plugins: { 'typescript-eslint': [Object] }, processor: undefined, reportUnusedDisableDirectives: undefined, root: true, rules: undefined, settings: undefined } ] on /Users/nicogreenarry/dev/eslint-typescript-sandbox +61ms
Error: Failed to load parser 'typescript-eslint/parser' declared in '.eslintrc.yaml': Cannot find module 'typescript-eslint/parser'
Require stack:
- /Users/nicogreenarry/dev/eslint-typescript-sandbox/.eslintrc.yaml
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at Object.resolve (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadParser (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:870:45)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:665:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/Users/nicogreenarry/dev/eslint-typescript-sandbox/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.14.0` |
| `@typescript-eslint/parser`        | `2.14.0` |
| `TypeScript`                       | `3.7.4` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `8.15.1` |
| `npm`                              | `6.13.4` |

**Comment by bradzacher** [comment]
you've got the name wrong. our packages are within the `@typescript-eslint` namespace. You forgot the `@`.

`@typescript-eslint/parser`

**Comment by nicogreenarry** [comment]
No, I tried that already, and that doesn't solve the issue. I just pushed a new commit demonstrating this. Can you reopen the issue?

**Comment by armano2** [comment]
@nicogreenarry this is not an issue with our package, its issue with how yaml read files

```yaml
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
```
[playground](https://nodeca.github.io/js-yaml/#yaml=cm9vdDogdHJ1ZQpwYXJzZXI6ICdAdHlwZXNjcmlwdC1lc2xpbnQvcGFyc2VyJwpwbHVnaW5zOgogIC0gJ0B0eXBlc2NyaXB0LWVzbGludCcKZXh0ZW5kczoKICAtICdlc2xpbnQ6cmVjb21tZW5kZWQnCiAgLSAncGx1Z2luOkB0eXBlc2NyaXB0LWVzbGludC9lc2xpbnQtcmVjb21tZW5kZWQnCiAgLSAncGx1Z2luOkB0eXBlc2NyaXB0LWVzbGludC9yZWNvbW1lbmRlZCc=)
