### ISSUE TITLE
[no-unnecessary-type-arguments] crashes with "TypeError: inputs is not iterable"

### ISSUE THREAD

**Issue by ulrichb** [typescript-eslint/typescript-eslint#1400]
**Repro**

Sry, I tried by cannot create an isolated repro sample

**Expected Result**

No crash.

**Actual Result**

```plain
TypeError: inputs is not iterable
Occurred while linting C:\...\src\FrontEnd\TaskConfiguration\reproB.tsx:8
    at Object.findFirstResult (C:\...\node_modules\@typescript-eslint\eslint-plugin\dist\util\misc.js:31:27)
    at getTypeParametersFromType (C:\...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-unnecessary-type-arguments.js:83:23)
    at getTypeParametersFromNode (C:\...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-unnecessary-type-arguments.js:69:16)
    at TSTypeParameterInstantiation (C:\...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-unnecessary-type-arguments.js:56:40)
    at C:\...\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\...\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\...\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (C:\...\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (C:\...\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
```

**Additional Info**

I added a console log, and saw that within `getTypeParametersFromType()`, `sym` is defined, but `sym.declarations` is `undefined`.

Note that there was an undefined-check, and it has been removed recently in https://github.com/typescript-eslint/typescript-eslint/commit/6a6bde01a0fe405f9d186788781cc2fa9cb37145#diff-dbe61204e37d60d91675cae497193c52L134-L136.

... so probably the second check (`sym.declarations === undefined`) should be restored again.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.14.0` |
| `@typescript-eslint/parser`        | `2.14.0` |
| `TypeScript`                       | `3.7.4` |
| `ESLint`                           | `6.8.0` |

**Comment by armano2** [comment]
i understand that this is private repository?

if so can you atleast explain what happens in `reproB.tsx` (without code - it should be around ~8th character)

**Comment by ulrichb** [comment]
Jep, private repo.

It's the following line:
`export type JsonMonacoEditorProps = ExtractComponentProps<typeof LazyJsonMonacoEditor>;`

... but it when isolating any of the stuff (`LazyJsonMonacoEditor` or `ExtractComponentProps`), the crash disappears, so this doesn't help.

BTW: This is the console log of `sym`, maybe this helps:
```plain
{
  flags: 33554436,
  escapedName: 'unknown',
  checkFlags: 0,
  type: <ref *1> TypeObject {
    checker: {
      getNodeCount: [Function: getNodeCount],
      getIdentifierCount: [Function: getIdentifierCount],
      getSymbolCount: [Function: getSymbolCount],
      getTypeCount: [Function: getTypeCount],
      getRelationCacheSizes: [Function: getRelationCacheSizes],
      isUndefinedSymbol: [Function: isUndefinedSymbol],
      isArgumentsSymbol: [Function: isArgumentsSymbol],
      isUnknownSymbol: [Function: isUnknownSymbol],
      getMergedSymbol: [Function: getMergedSymbol],
      getDiagnostics: [Function: getDiagnostics],
      getGlobalDiagnostics: [Function: getGlobalDiagnostics],
      getTypeOfSymbolAtLocation: [Function: getTypeOfSymbolAtLocation],
      getSymbolsOfParameterPropertyDeclaration: [Function: getSymbolsOfParameterPropertyDeclaration],
      getDeclaredTypeOfSymbol: [Function: getDeclaredTypeOfSymbol],
      getPropertiesOfType: [Function: getPropertiesOfType],
      getPropertyOfType: [Function: getPropertyOfType],
      getTypeOfPropertyOfType: [Function: getTypeOfPropertyOfType],
      getIndexInfoOfType: [Function: getIndexInfoOfType],
      getSignaturesOfType: [Function: getSignaturesOfType],
      getIndexTypeOfType: [Function: getIndexTypeOfType],
      getBaseTypes: [Function: getBaseTypes],
      getBaseTypeOfLiteralType: [Function: getBaseTypeOfLiteralType],
      getWidenedType: [Function: getWidenedType],
      getTypeFromTypeNode: [Function: getTypeFromTypeNode],
      getParameterType: [Function: getTypeAtPosition],
      getPromisedTypeOfPromise: [Function: getPromisedTypeOfPromise],
      getReturnTypeOfSignature: [Function: getReturnTypeOfSignature],
      isNullableType: [Function: isNullableType],
      getNullableType: [Function: getNullableType],
      getNonNullableType: [Function: getNonNullableType],
      getNonOptionalType: [Function: removeOptionalTypeMarker],
      getTypeArguments: [Function: getTypeArguments],
      typeToTypeNode: [Function: typeToTypeNode],
      indexInfoToIndexSignatureDeclaration: [Function: indexInfoToIndexSignatureDeclaration],
      signatureToSignatureDeclaration: [Function: signatureToSignatureDeclaration],
      symbolToEntityName: [Function: symbolToEntityName],
      symbolToExpression: [Function: symbolToExpression],
      symbolToTypeParameterDeclarations: [Function: symbolToTypeParameterDeclarations],
      symbolToParameterDeclaration: [Function: symbolToParameterDeclaration],
      typeParameterToDeclaration: [Function: typeParameterToDeclaration],
      getSymbolsInScope: [Function: getSymbolsInScope],
      getSymbolAtLocation: [Function: getSymbolAtLocation],
      getShorthandAssignmentValueSymbol: [Function: getShorthandAssignmentValueSymbol],
      getExportSpecifierLocalTargetSymbol: [Function: getExportSpecifierLocalTargetSymbol],
      getExportSymbolOfSymbol: [Function: getExportSymbolOfSymbol],
      getTypeAtLocation: [Function: getTypeAtLocation],
      getTypeOfAssignmentPattern: [Function: getTypeOfAssignmentPattern],
      getPropertySymbolOfDestructuringAssignment: [Function: getPropertySymbolOfDestructuringAssignment],
      signatureToString: [Function: signatureToString],
      typeToString: [Function: typeToString],
      symbolToString: [Function: symbolToString],
      typePredicateToString: [Function: typePredicateToString],
      writeSignature: [Function: writeSignature],
      writeType: [Function: writeType],
      writeSymbol: [Function: writeSymbol],
      writeTypePredicate: [Function: writeTypePredicate],
      getAugmentedPropertiesOfType: [Function: getAugmentedPropertiesOfType],
      getRootSymbols: [Function: getRootSymbols],
      getContextualType: [Function: getContextualType],
      getContextualTypeForObjectLiteralElement: [Function: getContextualTypeForObjectLiteralElement],
      getContextualTypeForArgumentAtIndex: [Function: getContextualTypeForArgumentAtIndex],
      getContextualTypeForJsxAttribute: [Function: getContextualTypeForJsxAttribute],
      isContextSensitive: [Function: isContextSensitive],
      getFullyQualifiedName: [Function: getFullyQualifiedName],
      getResolvedSignature: [Function: getResolvedSignature],
      getResolvedSignatureForSignatureHelp: [Function: getResolvedSignatureForSignatureHelp],
      getExpandedParameters: [Function: getExpandedParameters],
      hasEffectiveRestParameter: [Function: hasEffectiveRestParameter],
      getConstantValue: [Function: getConstantValue],
      isValidPropertyAccess: [Function: isValidPropertyAccess],
      isValidPropertyAccessForCompletions: [Function: isValidPropertyAccessForCompletions],
      getSignatureFromDeclaration: [Function: getSignatureFromDeclaration],
      isImplementationOfOverload: [Function: isImplementationOfOverload],
      getImmediateAliasedSymbol: [Function: getImmediateAliasedSymbol],
      getAliasedSymbol: [Function: resolveAlias],
      getEmitResolver: [Function: getEmitResolver],
      getExportsOfModule: [Function: getExportsOfModuleAsArray],
      getExportsAndPropertiesOfModule: [Function: getExportsAndPropertiesOfModule],
      getSymbolWalker: [Function: getSymbolWalker],
      getAmbientModules: [Function: getAmbientModules],
      getJsxIntrinsicTagNamesAt: [Function: getJsxIntrinsicTagNamesAt],
      isOptionalParameter: [Function: isOptionalParameter],
      tryGetMemberInModuleExports: [Function: tryGetMemberInModuleExports],
      tryGetMemberInModuleExportsAndProperties: [Function: tryGetMemberInModuleExportsAndProperties],
      tryFindAmbientModuleWithoutAugmentations: [Function: tryFindAmbientModuleWithoutAugmentations],
      getApparentType: [Function: getApparentType],
      getUnionType: [Function: getUnionType],
      isTypeAssignableTo: [Function: isTypeAssignableTo],
      createAnonymousType: [Function: createAnonymousType],
      createSignature: [Function: createSignature],
      createSymbol: [Function: createSymbol],
      createIndexInfo: [Function: createIndexInfo],
      getAnyType: [Function: getAnyType],
      getStringType: [Function: getStringType],
      getNumberType: [Function: getNumberType],
      createPromiseType: [Function: createPromiseType],
      createArrayType: [Function: createArrayType],
      getElementTypeOfArrayType: [Function: getElementTypeOfArrayType],
      getBooleanType: [Function: getBooleanType],
      getFalseType: [Function: getFalseType],
      getTrueType: [Function: getTrueType],
      getVoidType: [Function: getVoidType],
      getUndefinedType: [Function: getUndefinedType],
      getNullType: [Function: getNullType],
      getESSymbolType: [Function: getESSymbolType],
      getNeverType: [Function: getNeverType],
      getOptionalType: [Function: getOptionalType],
      isSymbolAccessible: [Function: isSymbolAccessible],
      getObjectFlags: [Function: getObjectFlags],
      isArrayType: [Function: isArrayType],
      isTupleType: [Function: isTupleType],
      isArrayLikeType: [Function: isArrayLikeType],
      isTypeInvalidDueToUnionDiscriminant: [Function: isTypeInvalidDueToUnionDiscriminant],
      getAllPossiblePropertiesOfTypes: [Function: getAllPossiblePropertiesOfTypes],
      getSuggestionForNonexistentProperty: [Function: getSuggestionForNonexistentProperty],
      getSuggestionForNonexistentSymbol: [Function: getSuggestionForNonexistentSymbol],
      getSuggestionForNonexistentExport: [Function: getSuggestionForNonexistentExport],
      getBaseConstraintOfType: [Function: getBaseConstraintOfType],
      getDefaultFromTypeParameter: [Function: getDefaultFromTypeParameter],
      resolveName: [Function: resolveName],
      getJsxNamespace: [Function: getJsxNamespace],
      getAccessibleSymbolChain: [Function: getAccessibleSymbolChain],
      getTypePredicateOfSignature: [Function: getTypePredicateOfSignature],
      resolveExternalModuleSymbol: [Function: resolveExternalModuleSymbol],
      tryGetThisTypeAt: [Function: tryGetThisTypeAt],
      getTypeArgumentConstraint: [Function: getTypeArgumentConstraint],
      getSuggestionDiagnostics: [Function: getSuggestionDiagnostics],
      runWithCancellationToken: [Function: runWithCancellationToken],
      getLocalTypeParametersOfClassOrInterfaceOrTypeAlias: [Function: getLocalTypeParametersOfClassOrInterfaceOrTypeAlias]
    },
    flags: 1,
    id: 4,
    intrinsicName: 'error',
    objectFlags: 0,
    immediateBaseConstraint: [Circular *1]
  }
}
```

**Comment by armano2** [comment]
ok i managed to reproduce it:

This is minimal test case:
```ts
// test.ts
import { F, foo as X } from './index';
function bar<T = X>(value: T): T {
    return value
}
bar<F<number>>(1)

// index.ts
type F<T> = T
export = F
```

Small note this code is invalid xd

**Comment by ulrichb** [comment]
> Small note this code is invalid xd

Hmm, that's strange. In my case the imported `ExtractComponentProps` (and the whole project) compiles fine with TSC. Is there any possibility to log the "compile errors" produced by TSTree?

**Comment by armano2** [comment]
in your code there is issue with resolving one of dependencies (type of it) and it's resolved as `unknown`, my example produces same type error, (without seeing code its hard to say what's wrong there)

**Comment by ulrichb** [comment]
... so is there any flag to show all resolution errors in ESLint? (Have no errors when compiling with TSC.)
