### ISSUE TITLE
Parsing errors when tsconfig.json's compilerOption's module is set to none

### ISSUE THREAD

**Issue by ericbartholet** [typescript-eslint/typescript-eslint#1502]
**What code were you trying to parse?**

```ts
// Parsing error: Cannot read property 'text' of undefined
const foo = 1;

// Parsing error: Cannot read property 'kind' of undefined
(() => { })();

// Parsing error: Cannot use 'in' operator to search for 'name' in undefined
let a: "a" | "b";
```

**What did you expect to happen?**
No parsing errors

**What actually happened?**
Got parsing errors

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.17.0` |
| `TypeScript`                | `3.7.5` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `10.18.1` |
| `npm`                       | `6.13.6` |

**Comment by ericbartholet** [comment]
**tsconfig.json**
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "none",
        "outDir": "dist/",
        "rootDir": "src/",
        "moduleResolution": "node"
    },
    "include": ["src/app.ts"]
}
```

**Comment by ericbartholet** [comment]
**ESLint Output Debugging Information**

```
Parsing error: Cannot read property 'text' of undefined
eslint:linter TypeError: Cannot read property 'text' of undefined
at TokenObject.TokenOrIdentifierObject.getText (C:\VSTS\Local\ESLintTest\node_modules\typescript\lib\typescript.js:130339:31)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:1487:31)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
at Converter.convertChild (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:144:21)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:605:32)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
at Converter.convertChild (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:144:21)
at result.createNode.declarations.node.declarationList.declarations.map.el (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:619:84)
at Array.map (<anonymous>)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:619:69)
```

```
Parsing error: Cannot read property 'kind' of undefined
eslint:linter TypeError: Cannot read property 'kind' of undefined
at Object.canContainDirective (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\node-utils.js:242:29)
at Converter.convertBodyExpressions (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:197:44)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:442:32)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
at Converter.convertChild (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:144:21)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:979:32)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
at Converter.convertChild (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:144:21)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:1790:29)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
```

```
Parsing error: Cannot use 'in' operator to search for 'name' in undefined
eslint:linter TypeError: Cannot use 'in' operator to search for 'name' in undefined
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:1475:28)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
at Converter.convertType (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:153:21)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:2107:35)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
at Converter.convertType (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:153:21)
at createNode.types.node.types.map.el (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:2076:54)
at Array.map (<anonymous>)
at Converter.convertNode (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:2076:39)
at Converter.converter (C:\VSTS\Local\ESLintTest\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
```

**Comment by ericbartholet** [comment]
Work around for now we've found is to set module to CommonJS in tsconfig.json so ESLint can run as expected then update our build step's compilation to override the module value:
`tsc -p ./tsconfig.json -m none`

**Comment by armano2** [comment]
interesting, i will take a look into this

**Comment by armano2** [comment]
Update: i was able to successfully reproduce this issue with minimal repo:
https://github.com/armano2/errors-typescript-eslint

**Comment by armano2** [comment]
Update:
- `const foo = 1;` is fixed

as for:
- Cannot read property 'kind' of undefined
- Cannot use 'in' operator to search for 'name' in undefined

issue is due to parent is undefined, issue is present only in persisted parse and only in first parsed file (2nd file is no longer affected by this)

**Comment by armano2** [comment]
> tsc -p ./tsconfig.json -m none

@ericbartholet better workaround for this can be a override of tsconfig 

you should be able to create `tsconfig.eslint.json`  and use it in eslintrc
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**Comment by tkdaj** [comment]
I keep getting the error "Parsing error: Cannot read property 'parent' of null" when adding new typescript files to my CRA project or refactoring a variable which is used in multiple files.  My tsconfig looks like this:

`{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "noImplicitAny": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": ["src"]
}`

and I'm using CRA with typescript 3.7.3
