### ISSUE TITLE
<TypeError: Cannot convert undefined or null to object>

### ISSUE THREAD

**Issue by rgranger** [typescript-eslint/typescript-eslint#1567]
After reinstalling node_modules, an error is thrown when using `eslint`.

![image](https://user-images.githubusercontent.com/5648257/73762897-017bf980-4771-11ea-9bdc-56b9203e8b64.png)

* eslint version that throws : 2.19.0
* eslint version that works : 2.18.0

--> Downgrading @typescript-eslint/eslint-plugin down to 2.18.0 works

**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "extends": [
    "standard"
  ],
  "plugins": [
    "babel",
    "@typescript-eslint"
  ],
  "env": {
    "browser" : true,
    "node": true,
    "mocha": true
  },
  "rules": {
    "eqeqeq": ["error", "always"],
    "object-curly-spacing"  : [2, "always"],
    "no-console"            : 2,
    "prefer-const"          : 2,
    "no-var"                : 2,
    "comma-dangle"          : ["error", "only-multiline"],
    "no-multi-spaces": ["error", { "ignoreEOLComments": true }],
    "indent": ["error", 2, {
      "SwitchCase": 1,
      "VariableDeclarator": 1,
      "outerIIFEBody": 1,
      "MemberExpression": 1,
      "CallExpression": {
        "arguments": 1
      },
      "FunctionDeclaration": {
        "parameters": 1,
        "body": 1
      },
      "FunctionExpression": {
        "parameters": 1,
        "body": 1
      }
    }],
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": ["error", {
      "vars": "all",
      "args": "none",
      "ignoreRestSiblings": true
    }]
  }
}
```

```TS
// your repro code case

// I don't think the tsconfig file is relevant but i can add it if you think so (it is quite huge)
```

**Expected Result**

The linter should not throw an error

**Actual Result**

`eslint` throws an error

**Additional Info**

Dump from running `eslint` command in terminal with option --debug :

```
...A whole lot of eslint:ignored-paths...

  eslint:ignored-paths   target = "D:\\Projets\\WebApp\\aw-utils\\webstorm\\webstorm-debug.js" +1ms
  eslint:ignored-paths   result = false +0ms
  eslint:ignored-paths contains: +1ms
  eslint:ignored-paths   target = "D:\\Projets\\WebApp\\aw-utils\\webstorm\\webstorm-debug.js" +0ms
  eslint:ignored-paths   result = false +1ms
  eslint:cli-engine Processing D:\Projets\WebApp\aw-utils\api\upload\build-form-data.js +0ms
  eslint:cli-engine Linting D:\Projets\WebApp\aw-utils\api\upload\build-form-data.js +1ms
  eslint:config Constructing config file hierarchy for D:\Projets\WebApp\aw-utils\api\upload +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading D:\Projets\WebApp\aw-utils\.eslintrc +2ms
  eslint:config-file Loading config file: D:\Projets\WebApp\aw-utils\.eslintrc +0ms
  eslint:config-file Loading aw +62ms
  eslint:config-file Attempting to resolve eslint-config-aw +1ms
  eslint:config-file Loading JS config file: D:\Projets\WebApp\aw-utils\node_modules\eslint-config-aw\index.js +3ms
  eslint:plugins Loaded plugin babel (eslint-plugin-babel@5.3.0) (from D:\Projets\WebApp\aw-utils\node_modules\eslint-plugin-babel\index.js) +0ms
TypeError: Cannot convert undefined or null to object
Referenced from: D:\Projets\WebApp\aw-utils\.eslintrc
    at Function.getOwnPropertyNames (<anonymous>)
    at nativelyBoundMembers.map.namespace (D:\Projets\WebApp\aw-utils\node_modules\@typescript-eslint\eslint-plugin\dist\rules\unbound-method.js:34:19)
    at Array.map (<anonymous>)
    at Object.<anonymous> (D:\Projets\WebApp\aw-utils\node_modules\@typescript-eslint\eslint-plugin\dist\rules\unbound-method.js:32:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! aw-utils@35.8.0-dev.0 lint:source: `eslint . --ignore-pattern=*.spec.js --ext=.jsx --ext=.js "--debug"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the aw-utils@35.8.0-dev.0 lint:source script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RGR\AppData\Roaming\npm-cache\_logs\2020-02-04T16_25_51_843Z-debug.log
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.19.0` |
| `@typescript-eslint/parser`        | `2.19.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `8.9.4` |
| `npm`                              | `4.6.1` |

**Comment by bradzacher** [comment]
The minimum supported version of node right now is 8.10.0, please upgrade to the next minor version.

Also note that node8 is now EOL, and is no longer maintained. We (and ESLint) will be removing support with the next major bump (coming v soon).

**Comment by rgranger** [comment]
Indeed, I reinstalled the latest node 8.x (8.17.0) and the error is gone. Thank you for the fast reply !
