### ISSUE TITLE
Cannot read property 'indexOf' of undefined while writing import statement

### ISSUE THREAD

**Issue by crystalfp** [typescript-eslint/typescript-eslint#1616]
_Moved here from microsoft/vscode-eslint #897 to mysticatea/eslint-plugin-node #207 to here. Hope this is the last hop..._

**What code were you trying to parse?**

1.  Have a `types.d.ts` file defining and exporting the interface `MyInterface`.

```ts
export interface MyInterface {
  blaBla: string;
}
```
2.  In VS Code create a ts file in the same directory. For me it was called `east-viewmodel.ts`.
3.  Inside this file start writing the import statement `import {MyInterface} from` At this point a notification appears in VS Code with the following text:
```
ESLint: Cannot read property 'indexOf' of undefined
Occurred while linting D:\Projects\IdeaIgniterEnvironment\client\east-viewmodel.ts:3.
Please see the 'ESLint' output channel for details.
```
The output channel shows the following stack trace:
```
[Error - 6:05:10 AM] TypeError: Cannot read property 'indexOf' of undefined
Occurred while linting D:\Projects\IdeaIgniterEnvironment\client\east-viewmodel.ts:3
    at stripImportPathParams (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint-plugin-node\lib\util\strip-import-path-params.js:8:20)
    at ExportAllDeclaration,ExportNamedDeclaration,ImportDeclaration,ImportExpression (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint-plugin-node\lib\util\visit-import.js:55:40)
    at D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:634:23)
    at D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\linter.js:936:32
```
Not critical, but annoying.
Thanks for looking!
mario

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.20.0` |
| `TypeScript`                | `3.7.5` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `12.15.0` |
| `npm`                       | `6.13.7` |

**Comment by armano2** [comment]
@mysticatea this seems to be issue with `eslint-plugin-node`

`eslint-plugin-node\lib\util\visit-import.js:55:40`

**Comment by bradzacher** [comment]
Please file an issue with `eslint-plugin-node`

**Comment by crystalfp** [comment]
Done
