### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by kaiyoma** [typescript-eslint/typescript-eslint#1653]
**What code were you trying to parse?**

```ts
import moduleInfo from './moduleInfo';

export { moduleInfo as info };

export * as actions from './actions';
export * as selectors from './selectors';
```

**What actually happened?**
```
TypeError: Cannot read property 'map' of undefined
    at Converter.convertNode (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:1225:64)
    at Converter.converter (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
    at Converter.convertChild (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:144:21)
    at ...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:201:32
    at Array.map (<anonymous>)
    at Converter.convertBodyExpressions (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:199:14)
    at Converter.convertNode (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:434:32)
    at Converter.converter (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
    at Converter.convertProgram (...\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:47:21)
    at Object.astConverter (...\node_modules\@typescript-eslint\typescript-estree\dist\ast-converter.js:26:29)
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `2.21.0` |
| `TypeScript`                           | `3.8.2` |
| `node`                                 | `12.16.1` |
| `npm`                                  | `6.13.4` |

**Comment by bradzacher** [comment]
we do not have support for 3.8 syntax yet.

#1436
