### ISSUE TITLE
[jest/prefer-spy-on]: Fix objects must not be overlapped in a report.

### ISSUE THREAD

**Issue by wKovacs64** [typescript-eslint/typescript-eslint#175]
**What code were you trying to parse?**

```ts
test('prefer-spy-on', () => {
  console.log = jest.fn();
});
```

**What did you expect to happen?**

I expected the rule to work.

**What actually happened?**

```
AssertionError [ERR_ASSERTION]: Fix objects must not be overlapped in a report.
    at mergeFixes (/Users/user/project/node_modules/eslint/lib/util/report-translator.js:150:9)
    at normalizeFixes (/Users/user/project/node_modules/eslint/lib/util/report-translator.js:180:16)
    at args (/Users/user/project/node_modules/eslint/lib/util/report-translator.js:278:18)
    at Object.report (/Users/user/project/node_modules/eslint/lib/linter.js:720:41)
    at AssignmentExpression (/Users/user/project/node_modules/eslint-plugin-jest/rules/prefer-spy-on.js:41:17)
    at listeners.(anonymous function).forEach.listener (/Users/user/project/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/user/project/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/user/project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/user/project/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.1.1` |
| `TypeScript`                | `3.2.4` |
| `ESLint`                    | `5.12.1` |
| `node`                      | `11.7.0` |
| `npm`                       | `6.5.0` |
| `eslint-plugin-jest` | `22.2.1` |

[`prefer-spy-on` source](https://github.com/jest-community/eslint-plugin-jest/blob/4bfdee55701d31a584e3bbe7455efb38b2138b0c/rules/prefer-spy-on.js)

**Comment by armano2** [comment]
issue is related to this plugin, they are using non standard fields from AST
`end` and `start` should not be used, this rule should use `range[0]`, `range[1]` instead
