### ISSUE TITLE
"0:0  error  Parsing error: '{' expected" for js file（React）

### ISSUE THREAD

**Issue by KushibikiMashu** [typescript-eslint/typescript-eslint#1812]
Hi there. I always appreciate the work you guys do.

I tried to run lint with `@typescript-eslint/parser` as a parser.

`$ eslint --fix . -c .eslintrc.js  --ext 'js,jsx,ts,tsx'`

Then, the following error is displayed.

```bash
/repos/front/components/app/front/pages/_app.js
0:0 error Parsing error: '{' expected
```

 I would appreciate it if you could tell me the cause and solution.

```.eslintrc.js
module.exports = {
  env: {
    browser: true,
    es6: true,
  },
  extends: [
    'airbnb',
    'plugin:@typescript-eslint/recommended',
    'plugin:promise/recommended',
    'plugin:import/typescript',
    'prettier',
    'prettier/react',
    'prettier/@typescript-eslint',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
    project: ['./tsconfig.json', './prettier.config.js'],
  },
  plugins: ['@typescript-eslint', 'promise', 'react', 'prettier'],
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  }
}
```

```tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": "./"
  },
  "exclude": [
    "node_modules",
    ".next"
  ],
  "include": [
    "src",
    "pages",
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx"
  ]
}
```

The following is the result of running in debug mode.

```
  eslint:ignore-pattern Check {
  filePath: '/Users/kushibiki/repos/front/components/app/front/pages/_app.js',
  dot: false,
  relativePath: 'pages/_app.js',
  result: false
} +2ms
  eslint:file-enumerator Yield: _app.js +2ms
  eslint:cascading-config-array-factory Load config files for /Users/kushibiki/repos/front/components/app/front/pages. +0ms
  eslint:cascading-config-array-factory Cache hit: /Users/kushibiki/repos/front/components/app/front/pages. +0ms
  eslint:cli-engine Lint /Users/kushibiki/repos/front/components/app/front/pages/_app.js +0ms
  eslint:linter Linting code for /Users/kushibiki/repos/front/components/app/front/pages/_app.js (pass 1) +0ms
  eslint:linter Verify +0ms
  eslint:linter With ConfigArray: /Users/kushibiki/repos/front/components/app/front/pages/_app.js +0ms
  eslint:linter Parsing error: '{' expected.
  eslint:linter Error: '{' expected.
    at diagnosticReporter (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/create-program/createWatchProgram.js:82:11)
    at Object.watchCompilerHost.afterProgramCreate (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/create-program/createWatchProgram.js:202:13)
    at synchronizeProgram (/Users/kushibiki/repos/front/components/app/front/node_modules/typescript/lib/typescript.js:100408:22)
    at Object.createWatchProgram (/Users/kushibiki/repos/front/components/app/front/node_modules/typescript/lib/typescript.js:100354:9)
    at createWatchProgram (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/create-program/createWatchProgram.js:244:22)
    at Object.getProgramsForProjects (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/create-program/createWatchProgram.js:162:30)
    at Object.createProjectProgram (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/create-program/createProjectProgram.js:26:74)
    at getProgramAndAST (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:62:32)
    at Object.parseAndGenerateServices (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:321:30)
    at Object.parseForESLint (/Users/kushibiki/repos/front/components/app/front/node_modules/@typescript-eslint/parser/dist/parser.js:53:51) +7s
  eslint:linter Generating fixed text for /Users/kushibiki/repos/front/components/app/front/pages/_app.js (pass 1) +1ms
  eslint:source-code-fixer Applying fixes +0ms
  eslint:source-code-fixer No fixes to apply +0ms
```

```_app.js
import React from 'react'
import 'src/Assets/scss/style.scss'
import Layout from '../src/Components/Layout'
import Header from '../src/Components/Header'

export default function MyApp({ Component, pageProps }) {
  const { displayName } = Component
  if (displayName !== undefined && displayName.includes('SearchPage')) {
    return (
      <>
        <Header />
        <Component {...pageProps} />
      </>
    )
  }

  return (
    <>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.15.0` |
| `TypeScript`                | `3.7.5` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `12.4.0` |
| `npm`                       | `6.13.4` |

**Comment by KushibikiMashu** [comment]
Sorry, I figured it out on my own.

```
 parserOptions: {
-    project: ['./tsconfig.json', './prettier.config.json'],
+    project: './tsconfig.json',
 },
```

I close this issue. Thank you.
