### ISSUE TITLE
Throw without arguments should be a syntax error

### ISSUE THREAD

**Issue by steelbrain** [typescript-eslint/typescript-eslint#1852]
```JSON
{
  "rules": {
    "no-throw-literal": "error"
  }
}
```

```TS
throw
```

Just that in a file somewhere

**Expected Result**

This should be a parse-error and should not be linted on.

**Actual Result**

Parser creates a `ThrowStatement` with `argument` set to null, which breaks rules downstream, see https://github.com/eslint/eslint/pull/13143 for context

**Additional Info**

```
[Error - 1:41:32 PM] TypeError: Cannot read property 'type' of null
Occurred while linting [fileName].ts:132
    at Object.couldBeError (eslint/lib/rules/utils/ast-utils.js:1262:22)
    at ThrowStatement (eslint/lib/rules/no-throw-literal.js:38:31)
    at eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
    at eslint/lib/linter/linter.js:936:32
```

**Versions**

| package                     | version   |
| --------------------------- | --------- |
| `@typescript-eslint/parser` | `^2.13.0` |
| `TypeScript`                | `^3.8.2`  |
| `ESLint`                    | `5.16.0`  |
| `node`                      | `12.16.0` |
| `npm`                       | `6.13.7`  |

**Comment by bradzacher** [comment]
cc @JamesHenry - what do you think about making the `parser` less forgiving in these invalid situations to match errors that are thrown by babel-eslint/acorn/espree?

I think `typescript-estree` is probably fine to parse as is (because typescript parses fine as is), but `parser` is intended to be used in ESLint, so we should probably match the same errors they throw here?

**Comment by JamesHenry** [comment]
@bradzacher are you talking about building checks ourselves or leveraging TS? IIRC it came up before that almost all of the valuable checks come from semantic diagnostics (even when they seem syntactic in nature) and so if we enable that feedback from TS it forces users to require type information even if they wouldn’t need it for their rules setup

**Comment by bradzacher** [comment]
Probably the former - building just the checks required to achieve some parity with what other parsers do. That way we can be sure that base rules won't error in weird ways (like this issue).

**Comment by steelbrain** [comment]
Not sure if I should create a new error for this or post here but

```
import
```

should also be a syntax error, otherwise we get

```
[Error - 8:02:02 PM] TypeError: Cannot read property 'indexOf' of undefined
Occurred while linting file.tsx:1
    at isAbsolute (eslint-plugin-import/lib/core/importType.js:48:15)
    at typeTest (eslint-plugin-import/lib/core/importType.js:116:7)
    at resolveImportType (eslint-plugin-import/lib/core/importType.js:148:10)
    at reportIfMissing (eslint-plugin-import/lib/rules/no-extraneous-dependencies.js:130:32)
    at ImportDeclaration (eslint-plugin-import/lib/rules/no-extraneous-dependencies.js:208:11)
    at eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (eslint/lib/linter/node-event-generator.js:283:22)

```

**Comment by bradzacher** [comment]
cc @thorn0 - if we were to make `typescript-estree` more ESTree spec complaint here, and throw issues for weird/incomplete code; would that cause issues for prettier?

**Comment by thorn0** [comment]
No problem. These issues mentioned here are actually not easy to reproduce with Prettier. The standalone `throw` parses only if it's inside a block and not followed by a semicolon, and I can't reproduce the issue with standalone `import` at all. I mean it's already a `SyntaxError`.

**Comment by AriPerkkio** [comment]
Hello @bradzacher, I've been testing various ESLint plugins for a while now. This bug/functionality in typescript parser is causing crashes in `eslint:all`, `eslint-plugin-node` and `eslint-plugin-testing-library`. 

I'm trying to figure out whether this bug should be handled by all of these community plugins or is this really a bug in typescript parser. There's some conflicting comments out there:
- https://github.com/mysticatea/eslint-plugin-node/issues/207#issuecomment-587439053.
- https://github.com/typescript-eslint/typescript-eslint/issues/1616#issuecomment-587546308

[ESLint](https://eslint.org/docs/developer-guide/working-with-custom-parsers#the-ast-specification) states that `The AST that custom parsers should create is based on ESTree`.  I think some of these cases do not meet the spec. 

So when ever I run into cases caused by typescript-parser generated AST which doesn't meet the spec, should I just ignore these or report them to plugin maintainers?

<details>
    <summary>Crashing rules</summary>

## Rule: indent
- Message: `Cannot read property 'loc' of undefined Occurred while linting <text>:1`
- Path: `Tejas1510/Awesome-Javascript-and-React-Project/college-website/server/src/server/api/email/emailer.js`
- [Link](https://github.com/Tejas1510/Awesome-Javascript-and-React-Project/blob/HEAD/college-website/server/src/server/api/email/emailer.js#L1)

```js
const

function sendEmail() {

try {

```

```
TypeError: Cannot read property 'loc' of undefined
Occurred while linting <text>:1
    at Object.VariableDeclaration [as listener] (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/rules/indent.js:1422:69)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/rules/indent.js:1634:55
    at Array.forEach (<anonymous>)
    at Program:exit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/rules/indent.js:1634:26)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.leaveNode(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:306:14)
```

## Rule: no-manual-cleanup
- Message: `Cannot read property 'match' of undefined Occurred while linting <text>:3`
- Path: `wesleyclzns/Perdita/perdita-app/src/componentes/App.js`
- [Link](https://github.com/wesleyclzns/Perdita/blob/HEAD/perdita-app/src/componentes/App.js#L3)

```js
import React from 'react';
import Pidex from './Pidex'
import
function App() {
  return (
    <div className="App">
      <header className="App-header">
       <h1>Pertida Index</h1>
```

```
TypeError: Cannot read property 'match' of undefined
Occurred while linting <text>:3
    at ImportDeclaration(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/no-manual-cleanup.js:47:59)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```

## Rule: unable-to-parse-rule-id
- Message: `Cannot read property 'indexOf' of undefined Occurred while linting <text>:3`
- Path: `wesleyclzns/Perdita/perdita-app/src/componentes/App.js`
- [Link](https://github.com/wesleyclzns/Perdita/blob/HEAD/perdita-app/src/componentes/App.js#L3)

```js
import React from 'react';
import Pidex from './Pidex'
import
function App() {
  return (
    <div className="App">
      <header className="App-header">
       <h1>Pertida Index</h1>
```

```
TypeError: Cannot read property 'indexOf' of undefined
Occurred while linting <text>:3
    at stripImportPathParams(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-node/lib/util/strip-import-path-params.js:8:20)
    atExportAllDeclaration,ExportNamedDeclaration,ImportDeclaration,ImportExpression(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-node/lib/util/visit-import.js:55:40)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode(/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:952:32
```

</details>

**Comment by bradzacher** [comment]
ESLint's default parser is required to adhere to the ESTree spec because that is the spec they are designed to adhere to.

Custom ESLint parsers are not beholden to the same requirement.
As a custom parser - typescript-eslint is not required to exactly adhere to the ESTree spec.

And in fact - we definitely do not adhere to it - there's no way for us to!
- We have new nodes that sit in statement/expression locations that can easily cause crashes on plugins that aren't careful.
- We also have new nodes which add to places where ESTree previously defined a single node child.
- We `null` out properties in certain cases
- We add all manner of new properties to existing nodes

An example of where we have seen this cause problems: the empty body function expression.
For example, this case especially:

```ts
class Foo {
  methodWithoutBody();
//                 ^^ TSEmptyBodyFunctionExpression -> body == null
  methodWithBody() {}
//              ^^^^^ FunctionExpression            -> body == BlockStatement
}
```

A lot of plugins assume that every `MethodDefinition` has a `FunctionExpression` as its `.value`, and that `FunctionExpression` has a `.body` which is a `BlockStatement`.

But `TSEmptyBodyFunctionExpression` breaks that convention at all levels - crashing plugins up that just try to do `node.value.body.body`.

There's also countless problems with stylistic rules and things like function generics, because they assume they don't exist - they don't have handling to traverse the new properties on existing nodes - which means that they create many false positives, or create broken fixes that either just delete generics or create syntactically broken code.

So the question is - what should a plugin do?

99.999999% of the time - fixing this is as simple as adding an if guard.
```
MethodDefinition(node) {
  if (node.value.body) {
    return;
  }

  // continue as normal
}
```

And for your cases - they could similarly be solved with simple `if` checks.
But should they? 🤷  That's up to the plugin themselves as to what they want to handle.

I do want to make our parser more correct, but doing so is not a small task, and it is also a breaking change. It's going to be quite some time before I will be able to tackle this.

**Comment by AriPerkkio** [comment]
Thanks for the very detailed answer. I think I'm starting to understand this issue now. 

These examples of valid Typescript AST you mentioned and whether plugins should handle those - this is a different issue. I should have specified some examples before for commenting the issue here.

I'm more concerned how the parser outputs AST for typescript which is not valid. Here are some examples tested with astexplorer and typescript playgroud.

```ts
import 

function HelloWorld() {}
```

- Espree: Unexpected token function
- TS: String literal expected.(1141)

```ts
const

function HelloWorld() { }
```

- Espree: Unexpected keyword 'function'
- TS: Variable declaration list cannot be empty.(1123)

```ts
throw

function HelloWorld() {}
```

- Illegal newline after throw
- TS: Line break not permitted here.(1142)

The parser is generating AST for all of these cases. I would expect it to recognize these as syntax errors, or something similar. I'm quite unsure whether third party plugins should be expected to handle these cases. They should however handle cases like `TSEmptyBodyFunctionExpression` if they are expected to work with typescript parser.

**Comment by bradzacher** [comment]
The typescript parser is very forgiving. It does its best to figure out what you meant and not throw errors unless it really really has to.

It does this for a number of reasons, but mainly so that use cases that need to be failure tolerant are so (eg syntax highlighters).

It emits errors separately as what it calls diagnostics.

In order to get these diagnostics, you need to use the program.

Before v3, we didn't create a program unless you configured type-aware linting.

So it meant we had no way to get the syntax errors. So we just didn't emit any...

Now we always have some form of a program, we could leverage TS to do some basic syntax validation.

**Comment by armano2** [comment]
> But again - emitting errors is a breaking change for the typescript-estree package - meaning it's a breaking change for the entire project.

thats not true, emiting errors is hidden behind flag and user has to opt in to actually get them, consumers of typescript-estree like prettier are not being affected by this

**Comment by bradzacher** [comment]
we can definitely prep a PR to do this (that's kind of the point of #2911 - laying the framework to do this easily), and we could land an option that's default off.

But it wouldn't get used until we set it on by default (which is breaking for both `typescript-estree` and `parser`).

As it stands right now `typescript-estree` is a bit of an unsafe mess that's grown and grown over the years. It's probably worth refactoring it before we start throwing in assertions.

Also worth noting that some of our AST types are inconsistent, so we'd ideally clean those up at the same time.

**Comment by JoshuaKGoldberg** [comment]
> But again - emitting errors is a breaking change for the typescript-estree package - meaning it's a breaking change for the entire project.

@bradzacher what if we made this an opt-in behavior, so API consumers such as Prettier can opt-into it? 

I see from as far back as https://github.com/typescript-eslint/typescript-eslint/issues/185#issuecomment-459824877 that `errorOnTypeScriptSyntacticAndSemanticIssues` has performance issues. Perhaps we could change the option to be more granular (e.g. splitting in two or becoming an enum / string literal) so we could call just `program.getSyntacticDiagnostics` and not `program.getSemanticDiagnostics`? Before I dig into that, just checking - has any work / performance investigating been done there?

**Comment by bradzacher** [comment]
The issue is that because TS is designed as a "forgiving" parser - most true syntax issues are actually reported as semantic issues.

Which is a big part of the problem!

I think the best way for us to build this is by enforcing invariants during the conversion. For example "if no expression exists for the throw statement, then parser error".

We could add a flag to turn off these invariants if consumers want a "bad" ast.

**Comment by JoshuaKGoldberg** [comment]
🤔 my concern there is that doing so would add a lot of code to add to the parser. https://github.com/typescript-eslint/typescript-eslint/pull/6247 shows what it's like.

Perhaps there's a way to get TypeScript to report these more accurately?

**Comment by bradzacher** [comment]
I personally don't mind some logic!

I don't mind either way if there's a way to make TS enforce it and we leverage that - the important thing is that our runtime output matches our types.

Our AST structure isn't exactly 1:1 so we have some invariants we will want to enforce as we merge things and move things around.

**Comment by JoshuaKGoldberg** [comment]
I've gone ahead and made two PRs for comparison:

* #6247
    * Advantage: works well with #6066 by not needing a new program
    * Disadvantage: adds code to `convert.ts` (as discussed)
* #6271
    * Advantage: more comprehensive
    * Disadvantage: partially conflicts with #6066 by needing to do a `program.getSemanticDiagnostics(ast)`

Filed https://github.com/microsoft/TypeScript/issues/52011 for #6271.

**Comment by bradzacher** [comment]
I can't remember if I've mentioned this before, but the thing I'd be testing is what is the performance of `program.getSemanticDiagnostics`.

That was the API that I implemented the old `no-unused-vars-experimental` rule with, and we found that it was way to slow for whole-codebase-linting-purposes. In some cases it would take ~50ms per file to return - which quickly adds up across a codebase (50ms * 1000 files = 50 seconds! Awful!!)

Code reference: https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts#L296
Reference issue: https://github.com/typescript-eslint/typescript-eslint/issues/1335

**Comment by bradzacher** [comment]
@fisker - that's actually a funny TS quirk - not due to us!
For whatever reason in the second example TS creates an identifier with the name `""` (which we currently don't error on).

I think that TS's parser treats the newline as an error recovery signal, and "makes the AST work", Whereas if it sees something on the same line (like EOF, `;`, `}`), then it will error on it.

**Comment by armano2** [comment]
there are similar issues with `const`, `let` and `var`
