### ISSUE TITLE
[dot-notation] Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by CatsMiaow** [typescript-eslint/typescript-eslint#1945]
- Node.js v12.16.2
- @typescript-eslint/eslint-plugin v2.30.0
- @typescript-eslint/parser v2.30.0

```json
"rules": {
  "dot-notation": "off",
  "@typescript-eslint/dot-notation": ["error", { "allowPrivateClassPropertyAccess": true }]
}
```
**test.spec.ts**
```ts
import got from 'got';

test('Test', async () => {
  const body = await got.post('https://google.com');

  expect(typeof body).toBe('object');
});
```

Occurs when using the `allowPrivateClassPropertyAccess` option. https://github.com/typescript-eslint/typescript-eslint/pull/1867
```bash
eslint --ext .ts test/test.spec.ts
TypeError: Cannot read property '0' of undefined
Occurred while linting /Users/cats/test/test.spec.ts:4
    at MemberExpression (/Users/cats/node_modules/@typescript-eslint/eslint-plugin/dist/rules/dot-notation.js:67:119)
    at /Users/cats/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/cats/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/cats/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/cats/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/cats/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/cats/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:635:23)
    at /Users/cats/node_modules/eslint/lib/linter/linter.js:948:32
    at Array.forEach (<anonymous>)
```

**Comment by bradzacher** [comment]
Ugh. This is due to the dodgy types in TypeScript.
