### ISSUE TITLE
Can TypeScript be installed globally?

### ISSUE THREAD

**Issue by iwis** [typescript-eslint/typescript-eslint#2041]
Several months ago I installed TypeScript globally by running: npm install - g typescript
Today I made steps described on https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md i.e.:

1. I run: `yarn add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin`

The result was:
```
...
info No lockfile found.
...
warning "@typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
...
success Saved lockfile.
success Saved 104 new dependencies.
...
```

2. I created .eslintrc.js file with the content given in README.md.

3. I run: `yarn eslint . --ext .js,.jsx,.ts,.tsx`
The result was:
```
Oops! Something went wrong! :(

ESLint: 7.0.0

Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': Cannot find module 'typescript'
Require stack:
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\2.8\node.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\2.9\node.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\3.0\node.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\3.2\node.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\node.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\eslint-plugin\dist\util\isTypeReadonly.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\eslint-plugin\dist\util\index.js   
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\eslint-plugin\dist\rules\adjacent-overload-signatures.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\eslint-plugin\dist\rules\index.js  
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\eslint-plugin\dist\index.js        
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\lib\cli-engine\config-array-factory.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\lib\eslint\eslint.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\lib\eslint\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\lib\cli.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\eslint\bin\eslint.js
Referenced from: C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\.eslintrc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\tsutils\typeguard\2.8\node.js:3:12)
    at Module._compile (C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I uninstalled global TypeScript by `npm uninstall - g typescript`, then installed it locally by `npm install typescript`, and finally I performed the above mentioned steps 1, 2 and 3. Now ESlint works.
Unfortunately I have not found information that TypeScript should not be installed globally. If this is really the case, then please add this information to README.md.

**Comment by bradzacher** [comment]
I believe you're making the incorrect assumption about the npm ecosystem.
You should assume that a tool _will not_ work with global installs unless specifically stated in the readme.
Global installs often require extra work from the package author to support properly. ESP in the case of requiring dependencies in a global package space vs a local package space.

We do not support global typescript installs, and likely never will.

**Comment by iwis** [comment]
I made a pull request to add information about this to FAQ.md. I added a justification why the information can be relevant to me. I am a new npm user so maybe only I have such problems. In this case, feel free to delete the pull request.

https://github.com/typescript-eslint/typescript-eslint/pull/2043
