### ISSUE TITLE
Failed to load plugin '@typescript-eslint' declared in 'BaseConfig': Cannot find module 'typescript'

### ISSUE THREAD

**Issue by dahuzix** [typescript-eslint/typescript-eslint#2048]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/<rule>": ["<setting>"]
  }
}
```

```TS
// your repro code case
```

**Expected Result**

**Actual Result**
```js
eslint --init
? How would you like to use ESLint? To check syntax, find problems, and enforce code style
? What type of modules does your project use? JavaScript modules (import/export)
? Which framework does your project use? Vue.js
? Does your project use TypeScript? Yes
? Where does your code run? Browser
? How would you like to define a style for your project? Use a popular style guide
? Which style guide do you want to follow? Airbnb: https://github.com/airbnb/javascript
? What format do you want your config file to be in? JavaScript
Checking peerDependencies of eslint-config-airbnb-base@latest
The config that you've selected requires the following dependencies:

eslint-plugin-vue@latest @typescript-eslint/eslint-plugin@latest eslint-config-airbnb-base@latest eslint@^5.16.0 || ^6.8.0 eslint-plugin-import@^2.20.1 @typescript-eslint/parser@latest
? Would you like to install them now with npm? Yes
Installing eslint-plugin-vue@latest, @typescript-eslint/eslint-plugin@latest, eslint-config-airbnb-base@latest, eslint@^5.16.0 || ^6.8.0, eslint-plugin-import@^2.20.1, @typescript-eslint/parser@latest
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ eslint-config-airbnb-base@14.1.0
+ eslint-plugin-vue@6.2.2
+ eslint-plugin-import@2.20.2
+ eslint@6.8.0
+ @typescript-eslint/parser@2.34.0
+ @typescript-eslint/eslint-plugin@2.34.0
updated 6 packages in 6.887s

3 packages are looking for funding
  run `npm fund` for details


Oops! Something went wrong! :(

ESLint: 7.0.0

Error: An error occurred while generating your JavaScript config file. A config file was still generated, but the config file itself may not follow your linting rules.
Error: Failed to load plugin '@typescript-eslint' declared in 'BaseConfig': Cannot find module 'typescript'
Require stack:
- /Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/2.8/node.js
- /Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/2.9/node.js
- /Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/3.0/node.js
- /Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/3.2/node.js
- /Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/node.js
- /Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/index.js
- /Users/socrates/data/www/qiankun/node_modules/tsutils/index.js
- /Users/socrates/data/www/qiankun/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js
- /Users/socrates/data/www/qiankun/node_modules/@typescript-eslint/eslint-plugin/dist/util/index.js
- /Users/socrates/data/www/qiankun/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js
- /Users/socrates/data/www/qiankun/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /Users/socrates/data/www/qiankun/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/lib/cli-engine/index.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/lib/init/source-code-utils.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/lib/init/config-initializer.js
- /Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (/Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/socrates/data/www/qiankun/node_modules/tsutils/typeguard/2.8/node.js:3:12)
    at Module._compile (/Users/socrates/.nvm/versions/node/v12.10.0/lib/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
````

**Additional Info**
when i run  eslint --init, i chose  vue, and typescript options.
when it gos to install the dependence, some error happended,
i try some times, it still error, how can i  fix this?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `X.Y.Z` |
| `@typescript-eslint/parser`        | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |
| `npm`                              | `X.Y.Z` |

```js
node -v
 // v12.10.0

npm -v
 // 6.14.5

tsc -v
// Version 3.9.2

// package.json
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.34.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^6.2.2",
    "lerna": "^3.21.0"
  }
```

**Comment by bradzacher** [comment]
> Cannot find module 'typescript

just install typescript.
