### ISSUE TITLE
TypeScript ESLint doesn't work with Airbnb configuration

### ISSUE THREAD

**Issue by iwis** [typescript-eslint/typescript-eslint#2049]
I installed https://github.com/typescript-eslint/typescript-eslint/ then performed steps from https://www.npmjs.com/package/eslint-config-airbnb-typescript (without React). I got the following errors:

```
C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>npm install --save-dev eslint-config-airbnb-typescript eslint-plugin-import@^2.20.1 @typescript-eslint/eslint-plugin@^2.24.0
npm WARN eslint-plugin-import@2.20.1 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.24.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.24.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react@^7.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.34.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN iw-components@1.0.0 No repository field.

+ eslint-plugin-import@2.20.1
+ eslint-config-airbnb-typescript@7.2.1
+ @typescript-eslint/eslint-plugin@2.24.0
added 68 packages from 40 contributors, removed 106 packages, updated 35 packages and audited 103 packages in 19.366s
found 0 vulnerabilities


C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>yarn eslint . --ext .ts
yarn run v1.22.4
error Command "eslint" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>eslint . --ext .ts     
'eslint' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>npx eslint --ext .ts .    
npx: installed 136 in 8.026s

Oops! Something went wrong! :(

ESLint: 7.0.0

Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'eslint'
Require stack:
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\Linter.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleTester.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\dist\analyze-scope.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\dist\parser.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli-engine\config-array-factory.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\eslint\eslint.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\eslint\index.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\Linter.js:4:18)
    at Module._compile (C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)

C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>
```

```js
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: ['./tsconfig.json'],                    //required for "type-aware linting"
  },  
  plugins: [
    '@typescript-eslint',
  ],
  extends: [
  //'eslint:recommended',
  //'plugin:@typescript-eslint/eslint-recommended',
  //'plugin:@typescript-eslint/recommended',
  //'plugin:@typescript-eslint/recommended-requiring-type-checking', //"type-aware linting"
  'airbnb-typescript/base',
  ],
};
```

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`      |2.24.0 |
| `@typescript-eslint/parser`             | 2.24.0 |
| `@typescript-eslint/typescript-estree`  |2.24.0 |
| `@typescript-eslint/experimental-utils` | 2.24.0 |
| `TypeScript`                            | 3.7.5 |
| `node`                                  | 12.10.0 |
| `npm`                                   | 6.10.3 |

**Comment by iwis** [comment]
It is probably again a problem with documentation.

**Comment by yoyo930021** [comment]
If you install eslint?

**Comment by iwis** [comment]
Using yarn or node?

**Comment by iwis** [comment]
I run: `npm install yarn add -D eslint`. And I get:
```
npm WARN @typescript-eslint/eslint-plugin@2.24.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react@^7.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.20.1 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN iw-components@1.0.0 No repository field.

+ yarn@1.22.4
+ eslint@7.0.0
+ add@2.0.6
added 107 packages from 67 contributors, updated 7 packages and audited 217 packages in 6.606s
found 0 vulnerabilities
```
`yarn eslint . --ext .ts` works now.  I do not know where was a problem. I think that I done everything according to documentation.

**Comment by bradzacher** [comment]
A lot of the packages just assume two things:
- you've already got typescript installed.
- you've already got eslint installed.

The thinking being that you've already got a scaffold built or are just starting a project, thus you already have installed typescript. It's rare that the setup process is:
create folder -> install linting tooling -> attempt lint.
usually it's:
create folder -> install typescript (and other frameworks like react) -> install linting tooling -> write code -> attempt lint.

Thus they omit the typescript installation step.

Similarly it's a generally assumed thing within the eslint world that you have already installed `eslint`. All of the plugins, parsers and configs have a `peerDependency` on `eslint` on purpose ([that's literally what peer deps are designed for](https://nodejs.org/es/blog/npm/peer-dependencies/)).

**Comment by iwis** [comment]
I have installed TypeScript at the beginning using: `npm install typescript@3.7.5 --save-exact`

I also installed ESLint using: `yarn add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin`

My process was:

1. write code using TypeScript (thus I had TypeScript - firstly it was installed globally, but now it is installed locally)
2. install "TypeScript ESLint"
3. install Airbnb configuration

 
I performed steps no. 2-3 again to check if I will have a problem:

1. `npm init -y`

2. `npm install typescript@3.7.5 --save-exact`
   TypeScript 3.7.5 is the newest version supported by TypeScript ESLint 2.34

3. `yarn add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin`
   I have found this command on: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
   I have checked in node_modules folder that it contains ESLint 7.0.0

4. `npm install eslint-config-airbnb-typescript eslint-plugin-import@^2.20.1 @typescript-eslint/eslint-plugin@^2.24.0 --save-dev`
   I have found this command on: https://www.npmjs.com/package/eslint-config-airbnb-typescript
   I believe that ESLint was removed during this step but I am not sure because I don't use npm often.

5. Commands `eslint --ext .ts` and `yarn eslint . --ext .ts` don't work now.

6. `npm install yarn add -D eslint`

7. I added .eslintrc.js file with the following content:
```
module.exports = {
  extends: ['airbnb-typescript/base'],
  parserOptions: {
    project: './tsconfig.json',
  },
};
```
8. Now `yarn eslint . --ext .ts` works.

Here is the result of each step:
```
c:\Users\Darek\Documents\Working\workspace\iw-components>npm init -y
Wrote to c:\Users\Darek\Documents\Working\workspace\iw-components\package.json:

{
  "name": "iw-components",
  "version": "1.0.0",
  "description": "The code was created while writing solutions to some tasks available at https://eloquentjavascript.net/ and https://javascript.info/.",
  "main": "index.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>npm install typescript@3.7.5 --save-exact
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN iw-components@1.0.0 No repository field.

+ typescript@3.7.5
added 1 package from 1 contributor and audited 1 package in 1.564s
found 0 vulnerabilities

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>yarn add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
yarn add v1.22.4
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 105 new dependencies.
info Direct dependencies
├─ @typescript-eslint/eslint-plugin@2.34.0
├─ @typescript-eslint/parser@2.34.0
├─ eslint@7.0.0
└─ typescript@3.7.5
info All dependencies
├─ @babel/code-frame@7.8.3
├─ @babel/helper-validator-identifier@7.9.5
├─ @babel/highlight@7.9.0
├─ @types/color-name@1.1.1
├─ @types/eslint-visitor-keys@1.0.0
├─ @types/json-schema@7.0.4
├─ @typescript-eslint/eslint-plugin@2.34.0
├─ @typescript-eslint/parser@2.34.0
├─ acorn-jsx@5.2.0
├─ acorn@7.2.0
├─ ajv@6.12.2
├─ ansi-escapes@4.3.1
├─ ansi-regex@5.0.0
├─ ansi-styles@3.2.1
├─ argparse@1.0.10
├─ astral-regex@1.0.0
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ callsites@3.1.0
├─ chalk@4.0.0
├─ chardet@0.7.0
├─ cli-cursor@3.1.0
├─ cli-width@2.2.1
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ concat-map@0.0.1
├─ cross-spawn@7.0.2
├─ debug@4.1.1
├─ deep-is@0.1.3
├─ doctrine@3.0.0
├─ emoji-regex@7.0.3
├─ eslint@7.0.0
├─ espree@7.0.0
├─ esprima@4.0.1
├─ esquery@1.3.1
├─ esrecurse@4.2.1
├─ estraverse@4.3.0
├─ external-editor@3.1.0
├─ fast-deep-equal@3.1.1
├─ fast-json-stable-stringify@2.1.0
├─ fast-levenshtein@2.0.6
├─ figures@3.2.0
├─ file-entry-cache@5.0.1
├─ flat-cache@2.0.1
├─ flatted@2.0.2
├─ fs.realpath@1.0.0
├─ glob-parent@5.1.1
├─ glob@7.1.6
├─ globals@12.4.0
├─ has-flag@4.0.0
├─ iconv-lite@0.4.24
├─ ignore@4.0.6
├─ import-fresh@3.2.1
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ inquirer@7.1.0
├─ is-extglob@2.1.1
├─ isexe@2.0.0
├─ js-tokens@4.0.0
├─ js-yaml@3.13.1
├─ json-schema-traverse@0.4.1
├─ json-stable-stringify-without-jsonify@1.0.1
├─ mimic-fn@2.1.0
├─ minimist@1.2.5
├─ mkdirp@0.5.5
├─ ms@2.1.2
├─ mute-stream@0.0.8
├─ natural-compare@1.4.0
├─ onetime@5.1.0
├─ optionator@0.9.1
├─ os-tmpdir@1.0.2
├─ parent-module@1.0.1
├─ path-is-absolute@1.0.1
├─ path-key@3.1.1
├─ progress@2.0.3
├─ punycode@2.1.1
├─ regexpp@3.1.0
├─ resolve-from@4.0.0
├─ restore-cursor@3.1.0
├─ rimraf@2.6.3
├─ run-async@2.4.1
├─ rxjs@6.5.5
├─ safer-buffer@2.1.2
├─ semver@7.3.2
├─ shebang-command@2.0.0
├─ shebang-regex@3.0.0
├─ signal-exit@3.0.3
├─ slice-ansi@2.1.0
├─ sprintf-js@1.0.3
├─ string-width@3.1.0
├─ strip-json-comments@3.1.0
├─ table@5.4.6
├─ text-table@0.2.0
├─ through@2.3.8
├─ tmp@0.0.33
├─ tslib@1.13.0
├─ type-check@0.4.0
├─ type-fest@0.8.1
├─ typescript@3.7.5
├─ uri-js@4.2.2
├─ v8-compile-cache@2.1.0
├─ which@2.0.2
├─ word-wrap@1.2.3
└─ write@1.0.3
Done in 7.04s.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>npm install eslint-config-airbnb-typescript eslint-plugin-import@^2.20.1 @typescript-eslint/eslint-plugin@^2.24.0 --save-dev
npm WARN eslint-plugin-import@2.20.1 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.24.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.24.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react@^7.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.34.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN iw-components@1.0.0 No repository field.

+ eslint-config-airbnb-typescript@7.2.1
+ eslint-plugin-import@2.20.1
+ @typescript-eslint/eslint-plugin@2.24.0
added 68 packages from 40 contributors, removed 106 packages, updated 35 packages and audited 103 packages in 8.365s
found 0 vulnerabilities

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>eslint --ext .ts
'eslint' is not recognized as an internal or external command,
operable program or batch file.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>yarn eslint . --ext .ts
yarn run v1.22.4
error Command "eslint" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>npm install yarn add -D eslint
npm WARN @typescript-eslint/eslint-plugin@2.24.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react@^7.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.20.1 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN iw-components@1.0.0 No repository field.

+ add@2.0.6
+ yarn@1.22.4
+ eslint@7.0.0
added 107 packages from 67 contributors, updated 7 packages and audited 217 packages in 5.947s
found 0 vulnerabilities

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Users\Darek\Documents\Working\workspace\iw-components>yarn eslint . --ext .ts
  ...
  ...
  ...

  18:4    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  19:3    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  19:3    error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi
  20:1    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  21:94   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  22:55   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  23:7    error  'isOpen' is never reassigned. Use 'const' instead                                                                                                                          prefer-const
  23:65   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  23:65   error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi
  24:69   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  24:69   error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi
  25:2    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  25:2    error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi
  26:1    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  27:67   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  28:7    error  'iwTreeOpenAllNodes' is assigned a value but never used                                                                                                                    @typescript-eslint/no-unused-vars    
  28:52   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  29:3    error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
  29:12   error  'innerNode' is never reassigned. Use 'const' instead                                                                                                                       prefer-const
  29:74   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  30:51   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  30:51   error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi
  31:52   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  31:52   error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi
  32:4    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  33:2    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                            linebreak-style
  33:2    error  Missing semicolon                                                                                                                                                          @typescript-eslint/semi

✖ 2038 problems (2038 errors, 0 warnings)
  1883 errors and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by iwis** [comment]
I performed all steps in the folder with this content: https://github.com/iwis/iw-components
