### ISSUE TITLE
Parsing error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by kyranet** [typescript-eslint/typescript-eslint#2098]
**Repro**

The `.eslint.json` can be retrieved from [here](https://github.com/dirigeants/klasa-lint/blob/master/.eslintrc.json).

```TS
export function test(): [string] {
	return ['some string, can be any tuple'];
}
```

**Expected Result**

No error is thrown.

**Actual Result**

[ERROR] Parsing error: Cannot read property 'map' of undefined

**Additional Info**

```js
2020-05-25T17:03:00.507Z eslint:file-enumerator Yield: conf.ts
2020-05-25T17:03:00.507Z eslint:cascading-config-array-factory Load config files for */src/commands/Admin.
2020-05-25T17:03:00.507Z eslint:cascading-config-array-factory Cache hit: */src/commands/Admin.
2020-05-25T17:03:00.508Z eslint:cli-engine Lint */src/commands/Admin/conf.ts
2020-05-25T17:03:00.508Z eslint:linter Linting code for */src/commands/Admin/conf.ts (pass 1)
2020-05-25T17:03:00.508Z eslint:linter Verify
2020-05-25T17:03:00.508Z eslint:linter With ConfigArray: */src/commands/Admin/conf.ts
2020-05-25T17:03:00.518Z eslint:linter Parsing error: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at Converter.convertNode (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:2095:53)
    at Converter.converter (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertType (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:158:21)
    at Converter.convertTypeAnnotation (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:192:34)
    at Converter.convertNode (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:1105:53)
    at Converter.converter (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertChild (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:149:21)
    at */node_modules/@typescript-eslint/typescript-estree/dist/convert.js:261:41
    at Array.map (<anonymous>)
    at Converter.convertParameters (*/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:260:27)
```

An exception is thrown in those lines:

https://github.com/typescript-eslint/typescript-eslint/blob/a71b9c9aabe1c3f26a76e77c29b3d2b7205c35ef/packages/typescript-estree/src/convert.ts#L2619-L2624

For more information, this is the [full log](https://gist.github.com/kyranet/3b6a0d4ba19c69e6e32c5652017ecabe) (ran with `--debug`) in my project, which can be found [here](https://github.com/dirigeants/klasa/tree/project-red).

**Versions**

| package                                | version              |
| -------------------------------------- | -------------------- |
| `@typescript-eslint/typescript-estree` | `2.34.0`             |
| `TypeScript`                           | `4.0.0-dev.20200522` |
| `node`                                 | `14.3.0`             |
| `npm`                                  | `6.14.5`             |

**Comment by bradzacher** [comment]
We do not support the nightly builds of TS, because they are unstable and can contain any number of breaking changes.

https://github.com/typescript-eslint/typescript-eslint#supported-typescript-version

We will investigate this further as 4.0.0 enters its beta and rc release phase.
