### ISSUE TITLE
[3.0.1] Failed to load parser errors with ESLint v6

### ISSUE THREAD

**Issue by SamChou19815** [typescript-eslint/typescript-eslint#2100]
**Repro**

`package.json`:
```json
{
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^3.0.1",
    "@typescript-eslint/parser": "^3.0.1",
    "eslint": "^6.8.0",
    "typescript": "^3.9.3"
  }
}
```

```JSON
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"]
}
```

```TS
const f = (): number => 42;
```

Command: `yarn eslint ok.ts`

**Expected Result**

No error.

**Actual Result**

```console
yarn eslint ok.ts
yarn run v1.22.4
warning package.json: No license field
$ /Users/sam/Downloads/ttt/node_modules/.bin/eslint ok.ts
TypeError: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc': Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/sam/Downloads/ttt/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/ESLint.js:14:31)
    at Module._compile (/Users/sam/Downloads/ttt/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/Users/sam/Downloads/ttt/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/sam/Downloads/ttt/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:15:14)
    at Module._compile (/Users/sam/Downloads/ttt/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Additional Info**

If I edit the `node_modules` and remove the line `__exportStar(require("./ESLint"), exports);` (`export * from './ESLint';` in ts source) in `node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js`, the error goes away.

I think it should not be exported to the top-level without guard, since the jsdoc for the class clearly says it's only in ESLint v7, and v3 still claims to support ESLint v6.

https://github.com/typescript-eslint/typescript-eslint/blob/a71b9c9aabe1c3f26a76e77c29b3d2b7205c35ef/packages/experimental-utils/src/ts-eslint/ESLint.ts#L344-L352

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `3.0.1` |
| `TypeScript`                            | `3.9.3` |
| `node`                                  | `12.14.1` |
| `npm`                                   | `6.14.3` |

**Comment by Towerism** [comment]
This will cause all new projects scaffolded with `eslint --init` unless users downgrade the plugin to 3.0.0. They will get a warning if they want to use latest typescript version though.

**Comment by djejaquino** [comment]
@Towerism downgrading to `3.0.0` worked for me, thanks.

Shouldn't it be backward compatible, since it is a patch version?

**Comment by bradzacher** [comment]
This has been fixed in master (and is available on the `canary` tag on npm).
It will be released to `latest` in due course.
