### ISSUE TITLE
plugin:@typescript-eslint/recommended-requiring-type-checking causes an error

### ISSUE THREAD

**Issue by aress31** [typescript-eslint/typescript-eslint#2265]
I am not sure if it is the right place to post this, but please see the description below.

**Repro**

When extending `plugin:@typescript-eslint/recommended-requiring-type-checking` `eslint` crashes with the following stack trace, when removing this, `eslint` works just fine...

```js
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'import', 'html', 'sort-keys-fix'],
  root: true,
  rules: {
    'import/no-unresolved': 'off',
    'sort-keys-fix/sort-keys-fix': 2,
  },
};
```

**Expected Result**
`yarn lint` to work as expected.

**Actual Result**
```
$ eslint --ext .ts,.html . --ignore-path .gitignore

Oops! Something went wrong! :(

ESLint: 7.3.1

Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting C:\Users\ateyar\Documents\GitHub\open-wc\declarations.d.ts
    at Object.getParserServices (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\getParserServices.js:23:15)
    at create (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\@typescript-eslint\eslint-plugin\dist\rules\await-thenable.js:41:37)
    at Object.create (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleCreator.js:13:24)
    at createRuleListeners (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:758:21)
    at C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:928:31
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:873:34)
    at Linter._verifyWithoutProcessors (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:1170:31)
    at Linter.<computed> (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\index.js:151:21)
    at Linter._verifyWithConfigArray (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:1268:21)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `^3.5.0` |
| `TypeScript`                | `~3.9.5` |
| `ESLint`                    | `^7.3.1` |
| `node`                      | `14.0.14` |
| `npm`                       | `^6.14.5` |

**Comment by bradzacher** [comment]
The error message provided explains the problem exactly.

Have you read that, or the documentation in this repo?

**Comment by aress31** [comment]
I have indeed followed the getting started documentation, and I am not really understanding what should be the action from my side to fix it, could you please provide some guidance?

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md

**Comment by aress31** [comment]
I have followed the instructions but it is still not working.

Please see the following stack trace:
```
PS C:\Users\ateyar\Documents\GitHub\open-wc> yarn lint:eslint
yarn run v1.22.4
$ eslint --ext .ts,.html . --ignore-path .gitignore

Oops! Something went wrong! :(

ESLint: 7.4.0

Error: Invalid location
    at locationToIndex (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\TransformableString.js:22:11)
    at TransformableString.originalLocation (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\TransformableString.js:121:19)    at remapMessages (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\index.js:294:31)
    at verifyCodePart (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\index.js:212:12)
    at Linter.<computed> (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\index.js:219:9)
    at Linter._verifyWithConfigArray (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:1268:21)
    at Linter.verify (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:1223:25)
    at Linter.verifyAndFix (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\linter\linter.js:1413:29)
    at verifyText (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\cli-engine\cli-engine.js:224:48)
    at CLIEngine.executeOnFiles (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint\lib\cli-engine\cli-engine.js:788:28)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And my `eslint` configuration:
```
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
  ],
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: ['tsconfig.json'],
  },
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'import', 'html', 'sort-keys-fix'],
  root: true,
  rules: {
    'import/no-unresolved': 'off',
    'sort-keys-fix/sort-keys-fix': 2,
  },
};
```

**Comment by bradzacher** [comment]
```
Invalid location
    at locationToIndex (C:\Users\ateyar\Documents\GitHub\open-wc\node_modules\eslint-plugin-html\src\TransformableString.js:22:11)
```

That stack looks like that's not for this project.

**Comment by aress31** [comment]
@bradzacher, it is for the project though...

**Comment by aress31** [comment]
Any update?

**Comment by bradzacher** [comment]
- eslint-plugin-html\src\TransformableString.js:22:11)
- eslint-plugin-html\src\TransformableString.js:121:19)
- eslint-plugin-html\src\index.js:294:31)
- eslint-plugin-html\src\index.js:212:12)
- eslint-plugin-html\src\index.js:219:9)
- eslint\lib\linter\linter.js:1268:21)
- eslint\lib\linter\linter.js:1223:25)
- eslint\lib\linter\linter.js:1413:29)
- eslint\lib\cli-engine\cli-engine.js:224:48)
- eslint\lib\cli-engine\cli-engine.js:788:28)

As mentioned before - that stack trace includes no lines from any of the packages in this project.
The last package involved in the stack is `eslint-plugin-html`. So likely this is an issue with that package.

**Comment by aress31** [comment]
Yeah I get it but when I remove the type checking I get no error so it surely got something to do with this package right?

**Comment by bradzacher** [comment]
with the information you've given - impossible to tell.

given that `eslint-plugin-html` includes a preprocessor, I'd start with a discussion in that repo with those maintainers, as they know their project and codebase (I know nothing about how that project or how it works beyond what I can glean in the readme).

If they find that it is indeed a problem on this project's side, happy to investigate further.
