### ISSUE TITLE
Tuple parsing error

### ISSUE THREAD

**Issue by TQjona** [typescript-eslint/typescript-eslint#2442]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Trying to parse a tuple fails:

```TS
type foo = [];
```

**Expected Result**

Works fine

**Actual Result**

ESlint encounters a parsing error

**Additional Info**

The error seems to be caused by a recent update (~ past two weeks)

ESlint stacktrace:
```
2020-08-31T11:59:41.049Z eslint:linter Parsing error: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at Converter.convertNode (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:2095:53)
    at Converter.converter (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertType (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:158:21)
    at Converter.convertTypeAnnotation (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:192:34)
    at Converter.convertNode (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:994:46)
    at Converter.converter (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertChild (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:149:21)
    at Converter.convertNode (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:614:32)
    at Converter.converter (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertChild (/home/username/project/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:149:21)
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `2.34.0` |
| `TypeScript`                           | `4.0.2` |
| `node`                                 | `14.8.0` |

**Comment by bradzacher** [comment]
> - [x] I have updated to the latest version of the packages.

The fact that you've listed v2.x when the latest release is 3.x suggests that you just ticked this box without actually doing it.

**Comment by TQjona** [comment]
For anyone else encountering this issue:

Updating react-scripts from currently latest stable version `3.4.3` to the currently latest unstable version `4.0.0-next.77` fixes this issue. This update of react-scripts bumps the version of typescript-eslint from version `2.34.0` to `3.10.1`
