### ISSUE TITLE
trying to augument an interface with `implements` instead of `extends` causes eslint to crash violently

### ISSUE THREAD

**Issue by KilianKilmister** [typescript-eslint/typescript-eslint#2551]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

I'm assuming it's the parser, but i'm not 100% sure

**Expected Result**

eslint raising a syntax error

**Actual Result**

violent crash

```log
[Error - 10:22:42 AM] ESLint stack trace:
[Error - 10:22:42 AM] TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/kilianhefti/dev/GitHub/doken/packages/token/src/abc.ts:1
    at ReferenceTracker._iteratePropertyReferences (/Users/kilianhefti/dev/GitHub/doken/node_modules/eslint-utils/index.js:1605:20)
    at _iteratePropertyReferences.next (<anonymous>)
    at ReferenceTracker._iterateVariableReferences (/Users/kilianhefti/dev/GitHub/doken/node_modules/eslint-utils/index.js:1583:29)
    at _iterateVariableReferences.next (<anonymous>)
    at ReferenceTracker.iterateGlobalReferences (/Users/kilianhefti/dev/GitHub/doken/node_modules/eslint-utils/index.js:1438:25)
    at iterateGlobalReferences.next (<anonymous>)
    at Program (/Users/kilianhefti/dev/GitHub/doken/node_modules/eslint/lib/rules/no-misleading-character-class.js:186:35)
    at /Users/kilianhefti/dev/GitHub/doken/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/kilianhefti/dev/GitHub/doken/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
[Error - 10:22:49 AM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Cannot read property 'type' of undefined
Occurred while linting /Users/kilianhefti/dev/GitHub/doken/packages/token/src/abc.ts:1
  Code: -32603 
```

**Additional Info**

i don't think the config matters here, but just to be save:

**Repro**

rule:

```JS
module.exports = {
  extends: 'standard-with-typescript',
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint/eslint-plugin'
  ],
  reportUnusedDisableDirectives: true,
  parserOptions: {
    warnOnUnsupportedTypeScriptVersion: false,
    ecmaVersion: 2021,
    projectFolderIgnoreList: [
      './node_modules/**'
    ],
    project: [
      './tsconfig.base.json',
      './packages/**/tsconfig.json',
      './src/tsconfig.json',
      './tsconfig.json',
      './dtsconfig.json'
    ],
    lib: [
      'esnext'
    ],
    extraFileExtensions: ['.cjs', '.mjs'],
    tsconfigRootDir: './'
  },
  rules: {
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/no-unused-vars-experimental': 'error',
    // checking
    '@typescript-eslint/class-literal-property-style': ['warn', 'getters'],
    '@typescript-eslint/array-type': 'off',
    '@typescript-eslint/no-dynamic-delete': 'warn',
    '@typescript-eslint/no-unnecessary-condition': ['warn', { allowConstantLoopConditions: true }],
    // filed
    // #region
    '@typescript-eslint/no-non-null-assertion': 'off', // ? https://github.com/standard/eslint-config-standard-with-typescript/issues/422
    '@typescript-eslint/return-await': [
      'error',
      'in-try-catch' // ? https://github.com/standard/eslint-config-standard-with-typescript/issues/417
    ],
    '@typescript-eslint/consistent-type-assertions': [
      'error',
      {
        assertionStyle: 'as',
        objectLiteralTypeAssertions: 'allow' // ? https://github.com/standard/eslint-config-standard-with-typescript/issues/421
      }
    ],
    // #endregion
    // argue for change/removal
    '@typescript-eslint/strict-boolean-expressions': 'off', // or at least non-nullables
    '@typescript-eslint/no-floating-promises': 'off',
    '@typescript-eslint/no-require-imports': 'warn',
    '@typescript-eslint/no-unnecessary-qualifier': 'error',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/require-array-sort-compare': [
      'error', { ignoreStringArrays: true } // _ add
    ],
    '@typescript-eslint/promise-function-async': [
      'error',
      {
        allowedPromiseNames: [],
        checkArrowFunctions: false, // _ add to standard
        checkFunctionDeclarations: true,
        checkFunctionExpressions: true,
        checkMethodDeclarations: true
      }
    ],
    // suggest
    '@typescript-eslint/no-confusing-non-null-assertion': 'error', // _ add to standard
    '@typescript-eslint/no-unsafe-return': 'warn',
    '@typescript-eslint/prefer-as-const': 'warn',
    '@typescript-eslint/no-inferrable-types': 'warn',
    '@typescript-eslint/prefer-string-starts-ends-with': 'warn',
    '@typescript-eslint/no-parameter-properties': 'warn',
    '@typescript-eslint/no-unnecessary-type-arguments': 'error',
    '@typescript-eslint/no-unsafe-call': 'warn',
    '@typescript-eslint/prefer-literal-enum-member': 'warn',
    '@typescript-eslint/no-loss-of-precision': 'warn', // _ add to standard
    '@typescript-eslint/unbound-method': 'warn', // _ add to standard
    '@typescript-eslint/switch-exhaustiveness-check': 'warn', // _ add to standard
    // '@typescript-eslint/ban-types': [
    //   'off',
    //   {
    //     types: {
    //       extendsDefaults: false
    //       //   String: { // _ add to standard
    //       //     message: 'Use string instead',
    //       //     fixWith: 'string'
    //       //   },
    //       //   Boolean: { // _ add to standard
    //       //     message: 'Use boolean instead',
    //       //     fixWith: 'boolean'
    //       //   },
    //       //   Number: { // _ add to standard
    //       //     message: 'Use number instead',
    //       //     fixWith: 'number'
    //       //   },
    //       //   Symbol: { // _ add to standard
    //       //     message: 'Use symbol instead',
    //       //     fixWith: 'symbol'
    //       //   },
    //
    //       //   Function: { // _ add to standard
    //       //     message: [
    //       //       'The `Function` type accepts any function-like value.',
    //       //       'It provides no type safety when calling the function, which can be a common source of bugs.',
    //       //       'It also accepts things like class declarations, which will throw at runtime as they will not be // called   with    `new`.',
    //       //       'If you are expecting the function to accept certain arguments, you should explicitly define the // function   shape.'
    //       //     ].join('\n'),
    //       //     fixWith: '(...args: any) => any'
    //       //   },
    //
    //     //   // object typing
    //     //   Object: { // _ add to standard
    //     //     message: [
    //     //       'The `Object` type actually means "any non-nullish value", so it is marginally better than `unknown`.',
    //     //       '- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.',
    //     //       '- If you want a type meaning "any value", you probably want `unknown` instead.'
    //     //     ].join('\n'),
    //     //     fixWith: 'object'
    //     //   },
    //     //   '{}': { // _ add to standard
    //     //     message: [
    //     //       '`{}` actually means "any non-nullish value".',
    //     //       '- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.',
    //     //       '- If you want a type meaning "any value", you probably want `unknown` instead.'
    //     //     ].join('\n'),
    //     //     fixWith: 'object'
    //     //   }
    //     }
    //   }
    // ],
    'no-restricted-syntax': [
      'error',
      {
        selector: 'TSEnumDeclaration:not([const=true])',
        message: 'Use const enums for documentation' // _ add to standard
      },
      {
        selector: 'ClassProperty[accessability=protected]',
        message: 'Use const enums for documentation'
      }
    ],
    '@typescript-eslint/consistent-type-imports': [
      'warn',
      {
        prefer: 'type-imports',
        disallowTypeAnnotations: true // _ add to standard
      }
    ],
    '@typescript-eslint/no-misused-promises': [
      'error',
      {
        checksVoidReturn: false // _ add to standard
      }
    ],
    // other
    '@typescript-eslint/prefer-reduce-type-parameter': 'warn', // same
    '@typescript-eslint/method-signature-style': 'off',
    '@typescript-eslint/member-ordering': [
      'warn',
      {
        default: [
          'abstract-field',
          'static-field',
          'instance-field',
          'field',
          'signature',
          'constructor',
          'abstract-method',
          'static-method',
          'instance-method',
          'method'
        ]
      }
    ],
    '@typescript-eslint/no-var-requires': 'warn', //* same
    '@typescript-eslint/no-extra-non-null-assertion': 'warn', //* same
    '@typescript-eslint/naming-convention': [
      'off',
      {
        selector: 'default',
        format: ['camelCase']
      },
      {
        selector: ['function', 'parameter'],
        format: ['camelCase']
      },
      {
        selector: 'variable',
        modifiers: ['const'],
        format: ['UPPER_CASE', 'camelCase', 'PascalCase']
      },
      {
        selector: 'memberLike',
        format: ['camelCase', 'PascalCase'],
        modifiers: ['static']
      },
      {
        selector: 'memberLike',
        format: ['camelCase', 'PascalCase', 'UPPER_CASE'],
        modifiers: ['static', 'readonly']
      },
      {
        selector: 'enumMember',
        format: ['UPPER_CASE']
      },
      {
        selector: 'typeLike',
        format: ['PascalCase']
      }
    ]
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
    // '@typescript-eslint/': 'warn',
  },
  overrides: [
    {
      files: [
        '**/dist/**',
        '**/cjs/**',
        '**/@types/**'
      ],
      rules: {
        '@typescript-eslint/no-unused-vars': 'off',
        'no-unused-vars': 'off',
        '@typescript-eslint/triple-slash-reference': 'off',
        '@typescript-eslint/no-empty-interface': 'off',
        '@typescript-eslint/no-unsafe-return': 'off',
        '@typescript-eslint/no-unsafe-call': 'off',
        '@typescript-eslint/no-var-requires': 'off',
        '@typescript-eslint/no-require-imports': 'off',
        'no-void': 'off',
        camelcase: 'off',
        '@typescript-eslint/naming-convention': [
          'off',
          {
            selector: 'default',
            format: []
          }
        ],
        '@typescript-eslint/no-unnecessary-condition': 'off',
        'spaced-comment': 'off'
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
        // "@typescript-eslint/no-require-imports": "off",
      }
    },
    {
      files: [
        '**/*.js',
        '**/*.mjs'
      ],
      rules: {
        '@typescript-eslint/naming-convention': [
          'off',
          {
            selector: 'default',
            format: null
          }
        ]
      }
    }
  ]
}

```

example type

```TS
type ReplacerFunction = Parameters<String['replace']>[1]
```

`compilerOptions` in `tsconfig`

```json5
{
  "lib": [
    "esnext"
  ],
  "alwaysStrict": true,
  "stripInternal": true,
  "assumeChangesOnlyAffectDirectDependencies": true,
  "declaration": true,
  "declarationDir": "@types",
  "declarationMap": true,
  "diagnostics": true,
  "forceConsistentCasingInFileNames": false,
  "importsNotUsedAsValues": "error",
  "incremental": true,
  "module": "esnext",
  "moduleResolution": "node",
  "outDir": "dist",
  "plugins": [],
  "pretty": true,
  "rootDir": ".",
  "baseUrl": ".",
  "sourceMap": true,
  "target": "ESNext",
  "useDefineForClassFields": true,
  "experimentalDecorators": true,
  "strict": true,
  "strictBindCallApply": true,
  "strictFunctionTypes": true,
  "strictNullChecks": true,
  "noImplicitAny": true,
  "strictPropertyInitialization": true,
  "noImplicitReturns": false,
  "noImplicitThis": true,
  "allowSyntheticDefaultImports": true,
  "emitDecoratorMetadata": true,
  "composite": true,
  "preserveSymlinks": true
},
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.0.1` |
| `@typescript-eslint/parser`        | `3.10.1` |
| `TypeScript`                       | `4.1.0-dev.20200911` |
| `ESLint`                           | `7.8.1` |
| `node`                             | `14.10` |

**Comment by bradzacher** [comment]
I'm unable to repro this against master.

Could you please create a repro repo to help investigate?

**Comment by KilianKilmister** [comment]
@bradzacher i don't seem to be able to reproduce it now either. Strange, it looked like that was the issue.

The basic context was that i had a class implementing the `RegExp` interface and an interface acompaning that class where i added all the doc comments. splitting the two into seperate files showed the error still occuring with the interface and changing the `implements` to `extends` on that interface resolved the issue.

Maybe i had some residual eslint or typescript-eslint with an older version somehere in my `node_modules`.

Well, that would close this i guess. Thanks anyways
