### ISSUE TITLE
`Parser` declares `typescript` as a peerDependency, not a devDependency.

### ISSUE THREAD

**Issue by hodovani** [typescript-eslint/typescript-eslint#2710]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

- run `npx eslint --init` in an empty npm project.
My log:

```
matviihodovaniuk@Matviis-MacBook-Pro eslint-demo % npx eslint --init            
✔ How would you like to use ESLint? · style
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · react
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser, node
✔ How would you like to define a style for your project? · prompt
✔ What format do you want your config file to be in? · JSON
✔ What style of indentation do you use? · tab
✔ What quotes do you use for strings? · single
✔ What line endings do you use? · unix
✔ Do you require semicolons? · No / Yes
The config that you've selected requires the following dependencies:

eslint-plugin-react@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest
Installing eslint-plugin-react@latest, @typescript-eslint/eslint-plugin@latest, @typescript-eslint/parser@latest
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN eslint-demo@1.0.0 No description
npm WARN eslint-demo@1.0.0 No repository field.

+ eslint-plugin-react@7.21.5
+ @typescript-eslint/parser@4.5.0
+ @typescript-eslint/eslint-plugin@4.5.0
added 70 packages from 47 contributors and audited 180 packages in 12.119s
found 0 vulnerabilities

Successfully created .eslintrc.json file in /Users/matviihodovaniuk/Documents/eslint-demo
```
I chose `Yes` for `Does your project use TypeScript?`

**Expected Result**

When I run `npx eslint index.ts` I can see a linter result.

**Actual Result**

```
matviihodovaniuk@Matviis-MacBook-Pro eslint-demo % npx eslint index.js   

Oops! Something went wrong! :(

ESLint: 7.12.0

Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module 'typescript'
Require stack:
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/2.8/node.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/2.9/node.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/3.0/node.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/3.2/node.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/node.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@typescript-eslint/eslint-plugin/dist/util/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/@eslint/eslintrc/lib/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/eslint/lib/eslint/eslint.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/eslint/lib/eslint/index.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/eslint/lib/cli.js
- /Users/matviihodovaniuk/Documents/eslint-demo/node_modules/eslint/bin/eslint.js
Referenced from: /Users/matviihodovaniuk/Documents/eslint-demo/.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (/Users/matviihodovaniuk/Documents/eslint-demo/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/matviihodovaniuk/Documents/eslint-demo/node_modules/tsutils/typeguard/2.8/node.js:3:12)
    at Module._compile (/Users/matviihodovaniuk/Documents/eslint-demo/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
```

**Additional Info**

Could we install `typescript` if a user don't have it `package.json`?

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.5.0` |
| `TypeScript`                | `4.0.3` |
| `ESLint`                    | `7.12.0` |
| `node`                      | `12.8.1` |

**Comment by bradzacher** [comment]
It's listed as a peerDep on purpose - so that you can install your own specific version.

If we made it a dependency - then your project would be stuck with the version we install.
On top of that - if your module manager (npm/yarn/pnpm/etc) doesn't hoist the version correctly then you could also get two versions installed at once. This has the potential to be catastrophic, causing subtle, hard-to-debug errors.

We list the installation of typescript in our installation instructions:
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#installation

**Comment by hodovani** [comment]
@bradzacher thanks. Sorry, but I found this issue when I was adding ESLint into my empty NPM project. I chose that I want to use TypeScript I expect it would setup all dependencies. What would be wrong if a user doesn't have `typescript` in they `package.json` and ESLint install it?

**Comment by bradzacher** [comment]
If you don't have typescript installed nothing will work. All our tooling is built on top of the package.

Our tooling is built with the assumption that you've already got TS installed, because we are a linter. We are secondary to your build pipeline.
