### ISSUE TITLE
[@angular-eslint/template/banana-in-box]

### ISSUE THREAD

**Issue by DmitriyTanase** [typescript-eslint/typescript-eslint#2763]
- [ + ] I have tried restarting my IDE and the issue persists.
- [ - ] I have updated to the latest version of the packages.
- [ + ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**eslintrc.js**

```eslintrc.js
module.exports = {
  parser: "@angular-eslint/template-parser",
  parserOptions: {
    project: './tsconfig.json',
    sourceType: "module"
  },
  env: {
    "browser": true,
    "es6": true,
    "node": true
  },
  ignorePatterns: ["node_modules/**/*", "**/node_modules/**/*", "dist/**/*"],
  extends: [
    'eslint:recommended',
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    'plugin:@angular-eslint/recommended',
    "prettier",
    "prettier/@typescript-eslint"
  ],
  plugins: [
    "eslint-plugin-import",
    "@angular-eslint/eslint-plugin",
    "eslint-plugin-jsdoc",
    "@angular-eslint/eslint-plugin-template",
    "eslint-plugin-prefer-arrow",
    "@typescript-eslint",
    "@angular-eslint",
    "prettier",
    'simple-import-sort',
    // "@typescript-eslint/tslint"
  ],
  rules: {
...
"@angular-eslint/no-conflicting-lifecycle": "error",
    "@angular-eslint/no-host-metadata-property": "error",
    "@angular-eslint/no-input-rename": "error",
    "@angular-eslint/no-inputs-metadata-property": "error",
    "@angular-eslint/no-output-native": "error",
    "@angular-eslint/no-output-on-prefix": "error",
    "@angular-eslint/no-output-rename": "error",
    "@angular-eslint/no-outputs-metadata-property": "error",
    // "@angular-eslint/template/banana-in-box": "error",
    "@angular-eslint/template/no-negated-async": "error",
    "@angular-eslint/use-lifecycle-interface": "error",
    "@angular-eslint/use-pipe-transform-interface": "error",
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/array-type": "off",
...
}
```
**tsconfig.json**
```TS
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
    "include": [
      "src",
      "eslintrc.js",
      ".eslintrc.js"
    ]
  }
}

```

**Expected Result**
In progress migration an angular app from tslint to eslint
Successful linting with eslint

**Actual Result**
```
 eslint "./src/**/*.ts"


Oops! Something went wrong! :(

ESLint: 7.13.0

Error: Error while loading rule '@angular-eslint/template/banana-in-box': You he 'parser' in your ESLint config.
Occurred while linting D:\Projects\VTB\WebClient\src\app\animations.ts
    at Linter._verifyWithConfigArray (D:\Projects\VTB\WebClient\node_modules\eslint\lib\linter\linter.js:1271:21)
    at Linter.verify (D:\Projects\VTB\WebClient\node_modules\eslint\lib\linter\linter.js:1226:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! web-client@0.0.0 eslint: `eslint "./src/**/*.ts"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the web-client@0.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hi-tech\AppData\Roaming\npm-cache\_logs\2020-11-13T13_39_40_039Z-debug.log
```

**Additional Info**
At first I replace parser as tolds me error, error from 'problems' tab in VS go out, but in console I get that error again
At second I commented out line of code whitch contains banana-in-box, as you can see, but its didnt help
Help me resolve this

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | "4.3.0" |
| `@typescript-eslint/parser`        | "^4.7.0" |
| `TypeScript`                       | "^4.0.5" |
| `ESLint`                           | "^7.6.0" |
| `node`                             | "12.18.4' |

**Comment by bradzacher** [comment]
Unless I'm mistaken - you've filed this issue in the wrong project.
https://github.com/angular-eslint/angular-eslint
