### ISSUE TITLE
[naming-convention] Example "Ignore destructured names" causes error

### ISSUE THREAD

**Issue by tbuschto** [typescript-eslint/typescript-eslint#2822]
I have no clue what's going on, please help:

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

```JSON
{
  "extends": "eslint:recommended",
  "env": {
    "es6": true
  },
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "@typescript-eslint/eslint-plugin",
    "jsdoc",
    "react"
  ],
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true,
      "arrowFunctions": true
    },
    "project": [
      "./tsconfig-lint.json"
    ]
  },
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "variable",
        "modifiers": ["destructured"],
        "format": null
      }
    ]
  }
}
```

```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es6",
    "rootDirs": ["src", "test"],
    "lib": ["es6"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "noUnusedLocals": true,
    "jsx": "react",
    "jsxFactory": "JSX.createElement",
    "allowJs": true
  },
  "include": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./test/**/*.tsx",
    "./test/**/*.js",
    "./test/**/*.jsx",
    "./examples/**/*.ts",
    "./examples/**/*.tsx",
    "./examples/**/*.js",
    "./examples/**/*.jsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Expected Result**

Not throwing error.

**Actual Result**

```
Error: .eslintrc.json:
        Configuration for rule "@typescript-eslint/naming-convention" is invalid:
        Value "variable" should be array.
        Value "variable" should be equal to one of the allowed values.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value "destructured" should be equal to one of the allowed values.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value "variable" should be equal to one of the allowed values.
        Value "variable" should be equal to one of the allowed values.
        Value "variable" should be equal to one of the allowed values.
        Value "variable" should be equal to one of the allowed values.
        Value "variable" should be equal to one of the allowed values.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value "variable" should be equal to one of the allowed values.
        Value "variable" should be equal to one of the allowed values.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should NOT have additional properties.
        Value {"selector":"variable","modifiers":["destructured"],"format":null} should match exactly one schema in oneOf.

    at ConfigValidator.validateRuleOptions (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:142:23)
    at Object.keys.forEach.id (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:197:18)
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:194:34)
    at ConfigValidator.validateConfigArray (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:320:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:492:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:298:21)
    at FileEnumerator._iterateFilesRecursive (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/eslint/lib/cli-engine/file-enumerator.js:476:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/mnt/c/Users/Tim/git/tabris-decorators-3/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:49)
```

**Additional Info**

It works if i remove "modifiers" or set it to empty array.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.8.2` |
| `@typescript-eslint/parser`        | `4.8.2` |
| `TypeScript`                       | `4.1.2` |
| `ESLint`                           | `7.14.0` |
| `node`                             | `14.15.1` |

**Comment by bradzacher** [comment]
Master is the latest version, which may not yet have been released.

The issue template explains this.

We tag every version. You should view the docs against the version you're using by using github tag selector.

**Comment by wood3n** [comment]
@bradzacher I have the same proble. And the version of eslint and @typescript-eslint/eslint-plugin is same as @tbuschto
