### ISSUE TITLE
[indent] Enabling TS causes rule to crash on incomplete code: "cannot read property 'loc' of undefined"

### ISSUE THREAD

**Issue by cakoose** [typescript-eslint/typescript-eslint#2826]
Reduced test case:

package.json
```json
{
  "name": "eslint-bug-indent-crash",
  "version": "0.0.1",
  "license": "CC0",
  "private": true,
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "4.8.2",
    "@typescript-eslint/parser": "4.8.2",
    "eslint": "7.14.0",
    "typescript": "4.1.2"
  }
}

```
.eslintrc.js
```javascript
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    plugins: [
        '@typescript-eslint',
    ],
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    rules: {
        'indent': 'warn',
    },
};
```

main.ts
```typescript
const   // <-- incomplete code

function f() {}
```

Crash when running `eslint`
```
$ ./node_modules/.bin/eslint .

Oops! Something went wrong! :(

ESLint: 7.14.0

TypeError: Cannot read property 'loc' of undefined
Occurred while linting <redacted>/eslint-bug-indent-crash/main.ts:1
    at Object.VariableDeclaration [as listener] (<redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/rules/indent.js:1422:69)
    at <redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/rules/indent.js:1634:55
    at Array.forEach (<anonymous>)
    at Program:exit (<redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/rules/indent.js:1634:26)
    at <redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (<redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (<redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.leaveNode (<redacted>/eslint-bug-indent-crash/node_modules/eslint/lib/linter/node-event-generator.js:306:14)
```

Most rules appear to handle incomplete code without crashing, so I assume this crash is worth fixing?  This crash is annoying during development because my IDE runs eslint continuously and shows a big warning when eslint crashes.

The crash doesn't seem to occur in plain JS.  When I change "main.ts" to "main.js" and change ".eslintrc.js" to:

```javascript
module.exports = {
    root: true,
    parserOptions: {
        ecmaVersion: 6,
    },
    rules: {
        'indent': 'warn',
    },
};
```

...the crash goes away:

```
$ ./node_modules/.bin/eslint .

<redacted>/eslint-bug-indent-crash/main.js
  3:1  error  Parsing error: Unexpected keyword 'function'

✖ 1 problem (1 error, 0 warnings)
```

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code
