### ISSUE TITLE
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module 'lodash/unescape'

### ISSUE THREAD

**Issue by gicontz** [typescript-eslint/typescript-eslint#2869]
- [✔️] I have tried restarting my IDE and the issue persists.
- [✔️] I have updated to the latest version of the packages.
- [✔️] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

1. All Good in Local
2. Failing in CircleCi

**What I've tried**

1. yarn add lodash.unescape && yarn add --dev @types/lodash.unescape _**-- not working**_

**eslintrc.json**

```JSON
{
  "extends": [
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2017,
    "project": "./tsconfig.json"
  },
  "plugins": [
    "@typescript-eslint",
    "prettier"
  ]
}

```

**Dependencies**
```JSON
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/preset-env": "^7.7.4",
    "@babel/preset-typescript": "^7.9.0",
    "@babel/runtime": "^7.8.7",
    "@types/jest": "^25.2.1",
    "@types/react": "^16.9.32",
    "@types/react-dom": "^16.9.6",
    "@types/systemjs": "^6.1.0",
    "@types/webpack-env": "^1.15.1",
    "@typescript-eslint/eslint-plugin": "^3.0.2",
    "@typescript-eslint/parser": "^3.0.2",
    "babel-eslint": "^11.0.0-beta.2",
    "babel-loader": "^8.0.6",
    "cloc": "^2.5.1",
    "concurrently": "^5.1.0",
    "copy-webpack-plugin": "^6.0.2",
    "cross-var": "^1.1.0",
    "dotenv": "^8.2.0",
    "dotenv-cli": "^3.1.0",
    "dotenv-webpack": "^1.8.0",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-config-ts-react-important-stuff": "^2.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "html-webpack-plugin": "^4.0.4",
    "husky": "^4.2.3",
    "jest": "^25.2.7",
    "jest-cli": "^25.2.7",
    "lint-staged": "^10.2.7",
    "prettier": "^2.0.5",
    "regenerator-runtime": "^0.13.5",
    "serve": "^11.3.1",
    "ts-config-single-spa": "^1.7.0",
    "typescript": "^3.8.3",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-config-single-spa-ts": "^1.4.2",
    "webpack-dev-server": "^3.9.0",
    "webpack-merge": "^4.2.2"
  },
  "dependencies": {
    "import-map-overrides": "^1.15.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "single-spa": "^5.5.2",
    "systemjs": "^6.3.2"
  },
  "resolutions": {
    "webpack-dev-server/**/node-forge": "^0.10.0",
    "webpack/**/elliptic": "^6.5.3"
  }
```

**TS Config**
```JSON
{
  "extends": "ts-config-single-spa",
  "include": ["src/**/*", "webpack.*.*"],
}
```

**Expected Result**

1. Do the linting checks

**Actual Result**

```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module 'lodash/unescape'
Require stack:
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/typescript-estree/dist/node-utils.js
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/typescript-estree/dist/convert.js
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/typescript-estree/dist/ast-converter.js
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/typescript-estree/dist/parser.js
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/typescript-estree/dist/index.js
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/parser/dist/parser.js
- /home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/parser/dist/index.js
- /home/circleci/att-tfm/web/root-config/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /home/circleci/att-tfm/web/root-config/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /home/circleci/att-tfm/web/root-config/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/circleci/att-tfm/web/root-config/node_modules/eslint/lib/cli-engine/index.js
- /home/circleci/att-tfm/web/root-config/node_modules/eslint/lib/cli.js
- /home/circleci/att-tfm/web/root-config/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/circleci/att-tfm/web/root-config/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/circleci/att-tfm/web/root-config/node_modules/@typescript-eslint/typescript-estree/dist/node-utils.js:26:36)
    at Module._compile (/home/circleci/att-tfm/web/root-config/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

error Command failed with exit code 2.
```

**Additional Info**

Command in CircleCI `yarn lint --no-color`

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.10.1` |
| `TypeScript`                | `3.9.7` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `14.15.1` |

**Comment by gicontz** [comment]
Closing this one:

Fix: 
```node
yarn add lodash && yarn add --dev @types/lodash
```
