### ISSUE TITLE
[prefer-readonly-parameter-types] Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by AriPerkkio** [typescript-eslint/typescript-eslint#3405]
Hello, `prefer-readonly-parameter-types` rule seems to crash in certain cases. This issue was spotted by automated CI run - it is not blocking my development or anything.

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JS
// .eslintrc.js
module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
  },
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
    tsconfigRootDir: __dirname,
    project: ["./tsconfig.json"],
  },
  plugins: ["@typescript-eslint"],
  rules: {
    "@typescript-eslint/prefer-readonly-parameter-types": "error",
  },
};
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["esnext", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist"
  },
  "include": ["./index.ts"]
}
```

This is as minimal as I could narrow the issue down.

```TS
type MyType<T> = {
  [K in keyof T]: "cat" | "dog" | T[K];
};

function method<A extends any[] = string[]>(value: MyType<A>) {
  return value;
}

method(["cat", "dog"]);
method<"mouse"[]>(["cat", "mouse"]);
```

**Expected Result**

ESLint should not crash.

**Actual Result**

```
TypeError: Cannot read property 'flags' of undefined
Occurred while linting /workspaces/eslint-remote-tester/node_modules/.cache-eslint-remote-tester/querycap/webappkit/@querycap/reactutils/must.tsx:7
    at Object.isUnionType (/workspaces/eslint-remote-tester/node_modules/tsutils/typeguard/2.8/type.js:69:18)
    at unionTypeParts (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:92:19)
    at isPropertyReadonlyInType (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:151:21)
    at isReadonlyPropertyFromMappedType (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:197:12)
    at /workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:179:21
    at someTypePart (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:100:52)
    at isReadonlyPropertyIntersection (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:172:12)
    at Object.isPropertyReadonlyInType (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:161:43)
    at isTypeReadonlyObject (/workspaces/eslint-remote-tester/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:72:28)
    at isTypeReadonlyRecurser (/workspaces/eslint-remote-tester/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:127:30)
```

**Additional Info**

<details>
  <summary>Crash reports from real projects</summary>

## Rule: prefer-readonly-parameter-types

- Message: `Cannot read property 'flags' of undefined Occurred while linting /workspaces/eslint-remote-tester/node_modules/.cache-eslint-remote-tester/querycap/webappkit/@querycap/reactutils/must.tsx:7`
- Path: `querycap/webappkit/@querycap/reactutils/must.tsx`
- [Link](https://github.com/querycap/webappkit/blob/HEAD/@querycap/reactutils/must.tsx#L7)

```tsx
   5 |
   6 | export function must<TPrepare extends Readonly<Array<any>>>(usePrepare: () => TPrepare) {
>  7 |   return function <TProps>(render: (props: TProps, ...prepare: NonNullableArray<TPrepare>) => JSX.Element | null) {
   8 |     const C = ({ "data-prepare": dataPrepare, ...props }: TProps & { ["data-prepare"]: NonNullableArray<TPrepare> }) =>
   9 |       render(props as any, ...(dataPrepare as any));
  10 |
```

```
TypeError: Cannot read property 'flags' of undefined
Occurred while linting /workspaces/eslint-remote-tester/node_modules/.cache-eslint-remote-tester/querycap/webappkit/@querycap/reactutils/must.tsx:7
    at Object.isUnionType (/workspaces/eslint-remote-tester/node_modules/tsutils/typeguard/2.8/type.js:69:18)
    at unionTypeParts (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:92:19)
    at isPropertyReadonlyInType (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:151:21)
    at isReadonlyPropertyFromMappedType (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:197:12)
    at /workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:179:21
    at someTypePart (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:100:52)
    at isReadonlyPropertyIntersection (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:172:12)
    at Object.isPropertyReadonlyInType (/workspaces/eslint-remote-tester/node_modules/tsutils/util/type.js:161:43)
    at isTypeReadonlyObject (/workspaces/eslint-remote-tester/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:72:28)
    at isTypeReadonlyRecurser (/workspaces/eslint-remote-tester/node_modules/@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js:127:30)
```

</details>

**Versions**

| package                            | version    |
| ---------------------------------- | ---------- |
| `@typescript-eslint/eslint-plugin` | `4.23.0`   |
| `@typescript-eslint/parser`        | `4.23.0`   |
| `TypeScript`                       | `4.2.4`    |
| `ESLint`                           | `7.26.0`   |
| `node`                             | `v14.15.1` |

**Comment by JoshuaKGoldberg** [comment]
@kirjs and I had a splendid time pairing on this: turns out `tsutils` crashes on a mapped type when the type mapping doesn't have modifiers.

https://github.com/ajafff/tsutils/pull/136

**Comment by rafaelss95** [comment]
I'm not entirely sure if it's a duplication, but it looks a lot like the one reported in #1742 (error logs are pretty similar).

**Comment by AriPerkkio** [comment]
@rafaelss95 the stack trace from `tsutils` seems identical so this is very likely a duplicate. I'm usually very careful not to file duplicate issues - no idea how I missed that issue here. 
As this issue already has a fix proposal linked I guess it makes sense to keep this one open.

**Comment by JoshuaKGoldberg** [comment]
As of #6428, the `v6` branch uses [`ts-api-tools`](https://github.com/JoshuaKGoldberg/ts-api-tools). Which has the same bug as `tsutils`. Fix is in review here: https://github.com/JoshuaKGoldberg/ts-api-tools/pull/18
