### ISSUE TITLE
Colon in jsx attribute name causing the eslint indent rule to crash

### ISSUE THREAD

**Issue by pfgithub** [typescript-eslint/typescript-eslint#3593]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```json
{
    "rules": {
        "indent": ["warn", 4]
    },
    "parser": "@typescript-eslint/parser"
}
```

```tsx
<demo
    aa:a={0}
/>
```

The same issue occurs using the `@typescript-eslint/indent` rule

```tsx
{
    "rules": {
        "@typescript-eslint/indent": ["warn", 4]
    },
    "parser": "@typescript-eslint/parser",
    "plugins": ["@typescript-eslint/eslint-plugin"]
}
```

The issue does not occur using `a:a={0}` instead of `aa:a={0}`

**Expected Result**

No error

**Actual Result**

```
Oops! Something went wrong! :(

ESLint: 7.29.0

RangeError: Maximum call stack size exceeded
Occurred while linting /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx:1
    at RedBlackTree.proto.le (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/functional-red-black-tree/rbtree.js:425:20)
    at BinarySearchTree.findLe (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:160:39)
    at OffsetStorage._getOffsetDescriptor (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:261:27)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:446:41)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:456:45)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:456:45)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:456:45)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:456:45)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:456:45)
    at OffsetStorage.getDesiredIndent (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/eslint/lib/rules/indent.js:456:45)
error Command failed with exit code 2.
```

**Additional Info**

```
  eslint:cli CLI args: [ '--debug', 'error.tsx' ] +0ms
  eslint:cli Running on files +3ms
  eslintrc:config-array-factory Loading JSON config file: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/package.json +0ms
  eslintrc:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', loose: false } ] +0ms
  eslintrc:ignore-pattern   processed: { basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', patterns: [ '/**/node_modules/*' ] } +1ms
  eslintrc:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', loose: false } ] +0ms
  eslintrc:ignore-pattern   processed: { basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', patterns: [ '/**/node_modules/*' ] } +0ms
  eslint:file-enumerator Start to iterate files: [ 'error.tsx' ] +0ms
  eslint:file-enumerator File: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx +1ms
  eslintrc:cascading-config-array-factory Load config files for /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp. +0ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp. +0ms
  eslintrc:config-array-factory Loading legacy config file: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/.eslintrc +3ms
  eslintrc:config-array-factory Config file found: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/.eslintrc +11ms
  eslintrc:config-array-factory Loading parser "@typescript-eslint/parser" from /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/.eslintrc +0ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/parser@4.28.1 (/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/@typescript-eslint/parser/dist/index.js) +1ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553. +190ms
  eslintrc:config-array-factory Config file not found on /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553 +178ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg/Dev/Node/temp/generated. +0ms
  eslintrc:config-array-factory Config file not found on /home/pfg/Dev/Node/temp/generated +0ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg/Dev/Node/temp. +0ms
  eslintrc:config-array-factory Config file not found on /home/pfg/Dev/Node/temp +0ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg/Dev/Node. +0ms
  eslintrc:config-array-factory Config file not found on /home/pfg/Dev/Node +0ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg/Dev. +0ms
  eslintrc:config-array-factory Config file not found on /home/pfg/Dev +0ms
  eslintrc:cascading-config-array-factory No cache found: /home/pfg. +0ms
  eslintrc:cascading-config-array-factory Stop traversing because of considered root. +0ms
  eslint:rules Loading rule 'indent' (remaining=283) +0ms
  eslintrc:cascading-config-array-factory Configuration was determined: ConfigArray(2) [ { type: 'config', name: 'DefaultIgnorePattern', filePath: '', criteria: null, env: undefined, globals: undefined, ignorePattern: IgnorePattern { patterns: [Array], basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', loose: false }, noInlineConfig: undefined, parser: undefined, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: undefined, settings: undefined }, { type: 'config', name: '.eslintrc', filePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/.eslintrc', criteria: null, env: undefined, globals: undefined, ignorePattern: undefined, noInlineConfig: undefined, parser: { error: null, filePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/@typescript-eslint/parser/dist/index.js', id: '@typescript-eslint/parser', importerName: '.eslintrc', importerPath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/.eslintrc' }, parserOptions: undefined, plugins: undefined, processor: undefined, reportUnusedDisableDirectives: undefined, root: undefined, rules: { indent: [Array] }, settings: undefined } ] on /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp +9ms
  eslintrc:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', loose: false } ] +201ms
  eslintrc:ignore-pattern   processed: { basePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp', patterns: [ '/**/node_modules/*' ] } +0ms
  eslintrc:ignore-pattern Check {
  filePath: '/home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx',
  dot: false,
  relativePath: 'error.tsx',
  result: false
} +0ms
  eslint:cli-engine Lint /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx +0ms
  eslint:linter Linting code for /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx (pass 1) +0ms
  eslint:linter Verify +1ms
  eslint:linter With ConfigArray: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx +0ms
  eslint:linter An error occurred while traversing +32ms
  eslint:linter Filename: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/error.tsx +1ms
  eslint:linter Line: 1 +0ms
  eslint:linter Parser Options: { ecmaVersion: undefined } +0ms
  eslint:linter Parser Path: /home/pfg/Dev/Node/temp/generated/4ad67f7e9c9a5986690c71c9f3c82553/tmp/node_modules/@typescript-eslint/parser/dist/index.js +0ms
  eslint:linter Settings: {} +0ms

Oops! Something went wrong! :(

… same as above
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.28.1` |
| `TypeScript`                | `4.3.4` |
| `ESLint`                    | `7.29.0` |
| `node`                      | `v14.15.3` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/1824
