### ISSUE TITLE
Doesn't work with eslint v8

### ISSUE THREAD

**Issue by coderaiser** [typescript-eslint/typescript-eslint#3735]
Installing latest versions of `typescript`, `@typescript-eslint/plugin`, `@typescript-eslint/parser` and [eslint v8](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0) with `node v16`, got a problem:

```sh
Welcome to Node.js v16.6.0.
Type ".help" for more information.
> require('@typescript-eslint/eslint-plugin')
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/coderaiser/putout/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
```

The thing is `CLIEngine` was deprecated in `ESLint` v7 and removed in v8 (which is right now in `beta`).

Also rules from `ESLint` cannot be required:

```sh
> require('@typescript-eslint/eslint-plugin')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rules/brace-style' is not defined by "exports" in /Users/coderaiser/putout/node_modules/eslint/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/coderaiser/putout/node_modules/@typescript-eslint/eslint-plugin/dist/rules/brace-style.js:6:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/coderaiser/putout/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/coderaiser/putout/node_modules/@typescript-eslint/eslint-plugin/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Because they are not exported anymore. According to [migration guide](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#the-cliengine-class-has-been-removed), rules should be used this way:

```diff
-import baseRule from 'eslint/lib/rules/brace-style';
+import {builtinRules} from 'eslint/use-at-your-own-risk';
+const baseRule = builtinRules['brace-style'];
```

**Comment by bradzacher** [comment]
Thanks for the issue - this is entirely expected. ESLint v8 contains a number of breakiing changes which we will need to make changes to support. We had discussions with the ESLint team about this, and are aware of the changes.

The supported ranges are communicated via our peer dependency ranges, which do not include ESLint v8.
