### ISSUE TITLE
 eslint-plugin-unicorn `no-for-loop` rule bug with `@typescript-eslint/parser` 

### ISSUE THREAD

**Issue by SimonSiefke** [typescript-eslint/typescript-eslint#392]
**What code were you trying to parse?**

```ts
const links = document.querySelectorAll('link')
for (let i = 0; i < links.length; i++) {
  const link = links[i]
}
```

The ESLint config:
```javascript
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['unicorn'],
  rules: {
    'unicorn/no-for-loop': 'error',
  },
}
```

**What did you expect to happen?**
ESLint does not throw an exception. The rule is actually working fine without `@typescript-eslint/parser`.

**What actually happened?**
ESLint threw an Exception: `TypeError: Expected `index` to be a number`.

```
[Error - 11:07:51 PM] ESLint stack trace:
[Error - 11:07:51 PM] TypeError: Expected `index` to be a number.
Occurred while linting /home/simon/Documents/self-tuts/live-server/unicorn.bug.js:2
    at SourceCode.getLocFromIndex (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/source-code.js:436:19)
    at getRemovalRange (/home/simon/Documents/self-tuts/live-server/node_modules/eslint-plugin-unicorn/rules/no-for-loop.js:171:28)
    at Object.ForStatement.problem.fix.fixer [as fix] (/home/simon/Documents/self-tuts/live-server/node_modules/eslint-plugin-unicorn/rules/no-for-loop.js:308:25)
    at normalizeFixes (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/report-translator.js:176:28)
    at args (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/report-translator.js:278:18)
    at Object.report (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/linter.js:721:41)
    at ForStatement (/home/simon/Documents/self-tuts/live-server/node_modules/eslint-plugin-unicorn/rules/no-for-loop.js:313:12)
    at listeners.(anonymous function).forEach.listener (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/safe-emitter.js:45:38)
```
**Versions**

| package                            | version  |
| ---------------------------------- | -------- |
| `@typescript-eslint/eslint-plugin` | `1.5.0`  |
| `TypeScript`                       | `3.4.1`  |
| `ESLint`                           | `5.16.0` |
| `node`                             | `11.10.0`|
| `npm`                              | `6.9.0`  |

**Comment by bradzacher** [comment]
This is a bug in eslint-plugin-unicorn.
They are using the [non-standard `start` property on the node](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/rules/no-for-loop.js#L171) to implement their rule when they should be using `range[0]`.

You've already filed a bug with them - it'd be faster to fix that as opposed to adding start/end to the parser.

See #405 for discussion.
