### ISSUE TITLE
no-unused-vars triggers an error on `declare enum`

### ISSUE THREAD

**Issue by mgol** [typescript-eslint/typescript-eslint#396]
**What code were you trying to parse?**

```ts
declare enum Test {
  Foo,
}
```

**What did you expect to happen?**

It should lint the code & not crash.

**What actually happened?**

With the following configuration:
```
"rules": [
  "no-unused-vars": [
    "error",
    {
      "args": "all",
      "argsIgnorePattern": "^_",
      "ignoreRestSiblings": true
    }
  ]
]
```
trying to lint the file with source provided above crashes with an error:
```
TypeError: Cannot read property 'parent' of undefined
Occurred while linting test.d.ts:1
    at variable.defs.some.def (project/node_modules/eslint/lib/rules/no-unused-vars.js:184:54)
    at Array.some (<anonymous>)
    at hasRestSpreadSibling (project/node_modules/eslint/lib/rules/no-unused-vars.js:182:38)
    at collectUnusedVariables (project/node_modules/eslint/lib/rules/no-unused-vars.js:578:80)
    at collectUnusedVariables (project/node_modules/eslint/lib/rules/no-unused-vars.js:585:17)
    at Program:exit (project/node_modules/eslint/lib/rules/no-unused-vars.js:630:36)
    at listeners.(anonymous function).forEach.listener (project/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (project/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.5.0` |
| `@typescript-eslint/parser`        | `1.5.0` |
| `TypeScript`                       | `3.3.4000` |
| `ESLint`                           | `5.15.3` |
| `node`                             | `v8.15.1` |
| ~~`npm`~~                              | N/A |
| `yarn`                              | `1.15.2` |

**Comment by bradzacher** [comment]
Could you try again with `@typescript-eslint/no-unused-vars` instead?
The base eslint rule `no-unused-vars` does not support typescript code.

**Comment by mgol** [comment]
Thanks, it works with `@typescript-eslint/no-unused-vars`.

I was confused by [ROADMAP.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) which references `no-unused-vars` first and only in a footnote mentions `@typescript-eslint/no-unused-vars` as "adding support for some TS-specific features". It suggests the original rule should still at least not crash. Given this issue, should the doc be changed to just reference `@typescript-eslint/no-unused-vars` instead?
