### ISSUE TITLE
The prop value with an expression type of TSNonNullExpression could not be resolved.

### ISSUE THREAD

**Issue by kripod** [typescript-eslint/typescript-eslint#437]
**What code were you trying to parse?**

```tsx
import { graphql, useStaticQuery } from 'gatsby';
import React from 'react';
import Helmet from 'react-helmet';
import { ThemeProvider } from 'styled-components';
import { Query } from '../generated/graphql';
import theme from '../utils/theme';

interface Props {
  children: React.ReactNode;
}

export default function Layout({ children }: Props) {
  const data = useStaticQuery<Query>(graphql`
    {
      site {
        siteMetadata {
          title
          description
          language
        }
      }
    }
  `);

  return (
    <ThemeProvider theme={theme}>
      <div>
        <Helmet
          titleTemplate={`%s | ${data.site!.siteMetadata!.title!}`}
          defaultTitle={data.site!.siteMetadata!.title!}
        >
          <html lang={data.site!.siteMetadata!.language} />
          <meta
            name="description"
            content={data.site!.siteMetadata!.description!}
          />
        </Helmet>

        <header>{/* TODO */}</header>

        <main>{children}</main>

        <footer>{/* TODO */}</footer>
      </div>
    </ThemeProvider>
  );
}
```

_(Source: https://github.com/kripod/gatsby-starter-strict/blob/f17ff00807feffba6d894de8e902a339b0d7c24a/src/components/Layout.tsx, but line 32 replaced with: `<html lang={data.site!.siteMetadata!.language!} />`)_

**What did you expect to happen?**

To parse the code without errors, as `data.site!.siteMetadata!.title!` and `data.site!.siteMetadata!.description!` work just fine.

**What actually happened?**

CLI error message:

```
$ eslint "**/*.{ts,tsx,js}"
Error: The prop value with an expression type of TSNonNullExpression could not be resolved.
  Please file issue to get this fixed immediately.
Occurred while linting D:\Development\Projects\gatsby-starter-strict\src\components\Layout.tsx:32
    at Object.extract [as JSXExpressionContainer] (D:\Development\Projects\gatsby-starter-strict\node_modules\jsx-ast-utils\lib\values\expressions\index.js:179:11)
    at getValue (D:\Development\Projects\gatsby-starter-strict\node_modules\jsx-ast-utils\lib\values\index.js:48:27)
    at extractValue (D:\Development\Projects\gatsby-starter-strict\node_modules\jsx-ast-utils\lib\getPropValue.js:24:12)
    at getPropValue (D:\Development\Projects\gatsby-starter-strict\node_modules\jsx-ast-utils\lib\getPropValue.js:41:10)
    at JSXOpeningElement (D:\Development\Projects\gatsby-starter-strict\node_modules\eslint-plugin-jsx-a11y\lib\rules\html-has-lang.js:37:50)
    at listeners.(anonymous function).forEach.listener (D:\Development\Projects\gatsby-starter-strict\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Development\Projects\gatsby-starter-strict\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Development\Projects\gatsby-starter-strict\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\Development\Projects\gatsby-starter-strict\node_modules\eslint\lib\util\node-event-generator.js:280:22)
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.6.1-alpha.14+6c50a99` |
| `TypeScript`                | `3.4.3` |
| `ESLint`                    | `6.0.0-alpha.0` |
| `node`                      | `10.15.0` |
| `yarn`                       | `1.15.2` |

**Comment by bradzacher** [comment]
Hi @kripod - as per the stack - this is a bug with one of the dependencies of `eslint-plugin-jsx-a11y`.
Specifically `jsx-ast-utils`.
As per the error message, Please file a bug with them to get this fixed.
