### ISSUE TITLE
no-invalid-this issue exception after upgrading to eslint 8.7.0

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#4444]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-invalid-this": "warn"
  }
}
```

```TS
export function buttonChangeAddress(callback: UiButtonCallbackType): string { // eslint-disable-line promise/prefer-await-to-callbacks
```

**Expected Result**

no error thrown

**Actual Result**

After upgrading to eslint 8.7.0!

```bash
> eslint --cache --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"


Oops! Something went wrong! :(

ESLint: 8.7.0

TypeError: rules.FunctionDeclaration is not a function
Occurred while linting /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/components/addAddressDialog/index.ts:30
Rule: "@typescript-eslint/no-invalid-this"
    at FunctionDeclaration (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-invalid-this.js:51:23)
    at ruleErrorHandler (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/linter.js:1079:28)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/linter.js:1110:32
````

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.9.1` |
| `@typescript-eslint/parser`        | `5.9.1` |
| `TypeScript`                       | `4.5.4` |
| `ESLint`                           | `8.7.0Z` |
| `node`                             | `16.13.2` |

**Comment by WikiRik** [comment]
For the person that has the time to look into this and make a PR; the ESLint PR that caused this issue is https://github.com/eslint/eslint/pull/15495

**Comment by doberkofler** [comment]
Thank you!
