### ISSUE TITLE
[unbound-method] Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#496]
**Repro**

```js
module.exports = {
	parser: '@typescript-eslint/parser',
	parserOptions: {
		project: './tsconfig.json'
	},
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended'
	],
	rules: {
		'@typescript-eslint/explicit-function-return-type': 'off',
		'@typescript-eslint/indent': ['warn', 'tab'],
		'@typescript-eslint/unbound-method': 'warn',
	}
};
```

```TS
class CommunicationError extends Error {
	status: number;
	description: string;

	constructor(status: number, message: string, description: string = '') {
		super(message);

		Object.setPrototypeOf(this, CommunicationError.prototype);

		this.status = status;
		this.description = description;
		this.stack = (new Error()).stack;
	}
}
```

**Expected Result**

**Actual Result**

```cmd
> npx eslint *.{js,jsx,ts,tsx}
TypeError: Cannot read property 'kind' of undefined
Occurred while linting D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\index.ts:8
    at isDangerousMethod (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\@typescript-eslint\eslint-plugin\dist\rules\un
bound-method.js:66:30)
    at MemberExpression (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\@typescript-eslint\eslint-plugin\dist\rules\unb
ound-method.js:54:31)
    at D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\util\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\util\node-event-gene
rator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\util\node-event-gen
erator.js:280:22)
    at NodeEventGenerator.enterNode (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\util\node-event-generato
r.js:294:14)
    at CodePathAnalyzer.enterNode (D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\code-path-analysis\code-pa
th-analyzer.js:632:23)
    at D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\lib\linter.js:752:32
```

**Additional Info**

```
  eslint:cli CLI args: [ '--debug', '*.ts' ] +0ms
  eslint:cli Running on files +7ms
  eslint:glob-utils Creating list of files to process. +0ms
  eslint:ignored-paths baseDir = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\unbound-method" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +3ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +1ms
  eslint:ignored-paths Looking for ignore file in D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method +1ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths contains: +6ms
  eslint:ignored-paths   target = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\unbound-method\\index.ts" +1ms
  eslint:ignored-paths   result = false +1ms
  eslint:ignored-paths contains: +0ms
  eslint:ignored-paths   target = "D:\\MyDev\\ljs_app\\trunk\\examples\\frontend\\@typescript-eslint\\unbound-method\\index.ts" +1ms
  eslint:ignored-paths   result = false +0ms
  eslint:cli-engine Processing D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\index.ts +0ms
  eslint:cli-engine Linting D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\index.ts +2ms
  eslint:config Constructing config file hierarchy for D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method +0ms
  eslint:config Using .eslintrc and package.json files +1ms
  eslint:config Loading D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\.eslintrc.js +1ms
  eslint:config-file Loading JS config file: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\.eslintrc.js +0ms
  eslint:config-file Loading plugin:@typescript-eslint/recommended +17ms
  eslint:config-file Attempting to resolve @typescript-eslint/eslint-plugin +1ms
  eslint:config-file Loading JS config file: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\@typescript-eslint\eslint-p
lugin\dist\index.js +2ms
  eslint:plugins Loaded plugin @typescript-eslint (@typescript-eslint/eslint-plugin@1.7.0) (from D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unb
ound-method\node_modules\@typescript-eslint\eslint-plugin\dist\index.js) +0ms
  eslint:config-file Loading D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\conf\eslint-recommended.js +366ms
  eslint:config-file Loading JS config file: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\eslint\conf\eslint-recommen
ded.js +1ms
  eslint:config Using D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\.eslintrc.js +404ms
  eslint:config-ops Using config from partial cache +0ms
  eslint:config-ops Apply environment settings to config +1ms
  eslint:linter Linting code for D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\index.ts (pass 1) +0ms
  eslint:traverser Unknown node type "ClassProperty": Estimated visitor keys ["type","key","value","computed","static","readonly","range","loc","typeAnnotation"
] +0ms
  eslint:traverser Unknown node type "TSTypeAnnotation": Estimated visitor keys ["type","loc","range","typeAnnotation"] +1ms
  eslint:traverser Unknown node type "TSNumberKeyword": Estimated visitor keys ["type","range","loc"] +4ms
  eslint:traverser Unknown node type "ClassProperty": Estimated visitor keys ["type","key","value","computed","static","readonly","range","loc","typeAnnotation"
] +3ms
  eslint:traverser Unknown node type "TSTypeAnnotation": Estimated visitor keys ["type","loc","range","typeAnnotation"] +6ms
  eslint:traverser Unknown node type "TSStringKeyword": Estimated visitor keys ["type","range","loc"] +3ms
  eslint:linter An error occurred while traversing +1s
  eslint:linter Filename: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\index.ts +1ms
  eslint:linter Line: 8 +1ms
  eslint:linter Parser Options: {
  sourceType: 'module',
  project: './tsconfig.json',
  ecmaFeatures: { globalReturn: false },
  ecmaVersion: 6
} +4ms
  eslint:linter Parser Path: D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\node_modules\@typescript-eslint\parser\dist\parser.js +6
ms
  eslint:linter Settings: {} +7ms
Cannot read property 'kind' of undefined
Occurred while linting D:\MyDev\ljs_app\trunk\examples\frontend\@typescript-eslint\unbound-method\index.ts:8
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.7.0` |
| `@typescript-eslint/parser`        | `1.7.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.1.0` |
| `npm`                              | `6.9.0` |

**Comment by bradzacher** [comment]
as per the error message, you need to tell the parser about your tsconifg:
> You have used a rule which requires parserServices to be generated. You must therefore provide a v
alue for the "parserOptions.project" property for @typescript-eslint/parser.
O

```
{
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: './tsconfig.json'
  }
}
```

**Comment by doberkofler** [comment]
@bradzacher Sorry. I made a mistake when extracting my sample code but the error is really there. I've updated my original post with the correct results and would kindly ask you to reopen the SR and possibly help. Thank you!

**Comment by bradzacher** [comment]
the updated post now contains a different error.

> Cannot read property 'kind' of undefined

**Comment by bradzacher** [comment]
I don't understand why you're calling setPrototype of within your constructor.
The entire point of class semantics is that this is handled for you - from my understanding that line should be entirely redundant?

-----

regardless. This is a bug in typescript. It's not setting a `valueDeclaration` for the symbol even though the types say that it should never be undefined..

**Comment by bradzacher** [comment]
reported to TS:
https://github.com/microsoft/TypeScript/issues/31294

**Comment by doberkofler** [comment]
> I don't understand why you're calling setPrototype of within your constructor.

It's [recommended](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work) by the TypeScript team.

**Comment by bradzacher** [comment]
Ah, it's recommended specifically for extending builtin types.
You only need to do that when targeting ES5, because typescript has to transpile your class definition down.
If you're targeting ES6+, then the class definition shouldn't get transpiled, meaning it will work fine as is.

This is run in chrome's dev tools:
![image](https://user-images.githubusercontent.com/7462525/57323876-7b386700-70bb-11e9-8655-fa173a2d2265.png)

**Comment by doberkofler** [comment]
Yes, I'm (still) targeting ES5
