### ISSUE TITLE
Tests: Website tests regularly failing with ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#4972]
Example failure: https://github.com/typescript-eslint/typescript-eslint/runs/6432851109?check_suite_focus=true

```
We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: ESOCKETTIMEDOUT

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
      at http://localhost:3000/__cypress/runner/cypress_runner.js:156078:82
      at visitFailedByErr (http://localhost:3000/__cypress/runner/cypress_runner.js:155437:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:156077:11
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:11[249](https://github.com/typescript-eslint/typescript-eslint/runs/6432851109?check_suite_focus=true#step:7:249):10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/index.spec.js:103:8)
  
  From Node.js Internals:
    Error: ESOCKETTIMEDOUT
        at ClientRequest.<anonymous> (/home/runner/.cache/Cypress/8.7.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:808:19)
        at Object.onceWrapper (events.js:482:28)
        at ClientRequest.emit (events.js:376:20)
        at Socket.emitRequestTimeout (_http_client.js:790:9)
        at Object.onceWrapper (events.js:482:28)
        at Socket.emit (events.js:388:22)
        at Socket._onTimeout (net.js:483:8)
        at listOnTimeout (internal/timers.js:555:17)
        at processTimers (internal/timers.js:498:7)
```

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/4739? 😄

**Comment by bradzacher** [comment]
I forgot that we had raised one already!
