### ISSUE TITLE
Bug: TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by Yohandah** [typescript-eslint/typescript-eslint#5160]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Repro Code

```typescript
If I do this : it works

const reducer: ActionReducer<FormState> = createReducer(
  on(fromForm.resetForm, (state: FormState) => initialState),
)
```

if I do this it fires the error : 
```
const reducer: ActionReducer<FormState> = createReducer(
  on(fromForm.resetForm, () => initialState),
)
```

```
TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting C:\dev\easyfpda-web\src\app\modules\create-fpda-form\store\form-store\form.reducer.ts:232
    at SourceCode.getTokenBefore (C:\dev\easyfpda-web\node_modules\eslint\lib\source-code\token-store\index.js:298:18)
    at getFixes (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:52:38)
    at Object.fix (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:41:45)
    at normalizeFixes (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:223:22
    at Array.map (<anonymous>)
    at mapSuggestions (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:217:10)
    at C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:365:55
    at Object.report (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\linter.js:926:41)
    at CallExpression[callee.name='createReducer'] CallExpression[callee.name='on'] > ArrowFunctionExpression:not([returnType.typeAnnotation], :has(CallExpression)) (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:35:25)
Process finished with exit code -1
```
```


### ESLint Config

```javascript
{
  "root": true,
  "ignorePatterns": ["projects/**/*", "src/app/utils/ngrx-forms/ngrx-forms-fixs"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "airbnb-typescript/base",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:eslint-comments/recommended",
        "plugin:promise/recommended",
        "plugin:unicorn/recommended",
        "plugin:prettier/recommended",
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates",
        "plugin:ngrx/recommended"
      ],
      "plugins": ["@typescript-eslint", "unicorn", "no-null", "eslint-comments", "import", "ngrx"],
    ]
  }
}
```

### tsconfig

```jsonc
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": ["es2018", "dom", "dom.iterable"],
    "paths": {
      "@core/*": ["src/app/core/*"],
      "@modules/*": ["src/app/modules/*"],
      "@shared/*": ["src/app/shared"],
      "@utils/*": ["src/app/utils/*"]
    }
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  },
  "exclude": ["dist", "node_modules"]
}
```

### Expected Result

No errors

### Actual Result

Error 
```
TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting C:\dev\easyfpda-web\src\app\modules\create-fpda-form\store\form-store\form.reducer.ts:232
    at SourceCode.getTokenBefore (C:\dev\easyfpda-web\node_modules\eslint\lib\source-code\token-store\index.js:298:18)
    at getFixes (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:52:38)
    at Object.fix (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:41:45)
    at normalizeFixes (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:223:22
    at Array.map (<anonymous>)
    at mapSuggestions (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:217:10)
    at C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:365:55
    at Object.report (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\linter.js:926:41)
    at CallExpression[callee.name='createReducer'] CallExpression[callee.name='on'] > ArrowFunctionExpression:not([returnType.typeAnnotation], :has(CallExpression)) (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:35:25)
Process finished with exit code -1
```

### Versions

```
"eslint": "^7.26.0",
"eslint-config-airbnb-typescript": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jest": "^25.7.0",
    "eslint-plugin-jsdoc": "^37.6.1",
    "eslint-plugin-ngrx": "^1.47.1",
    "eslint-plugin-no-null": "^1.0.2",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-unicorn": "^40.1.0",
"typescript": "~4.3.5"
"@angular-eslint/builder": "^12.7.0",
    "@angular-eslint/eslint-plugin": "^12.7.0",
    "@angular-eslint/eslint-plugin-template": "^12.7.0",
 "@typescript-eslint/eslint-plugin": "5.27.1",
    "@typescript-eslint/parser": "5.27.1",
```

**Comment by bradzacher** [comment]
Looking at the stack trace that you included:
```
Occurred while linting C:\dev\easyfpda-web\src\app\modules\create-fpda-form\store\form-store\form.reducer.ts:232
    at SourceCode.getTokenBefore (C:\dev\easyfpda-web\node_modules\eslint\lib\source-code\token-store\index.js:298:18)
    at getFixes (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:52:38)
    at Object.fix (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:41:45)
    at normalizeFixes (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:223:22
    at Array.map (<anonymous>)
    at mapSuggestions (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:217:10)
    at C:\dev\easyfpda-web\node_modules\eslint\lib\linter\report-translator.js:365:55
    at Object.report (C:\dev\easyfpda-web\node_modules\eslint\lib\linter\linter.js:926:41)
```

I can see the source of the error is
```
at getFixes (C:\dev\easyfpda-web\node_modules\eslint-plugin-ngrx\dist\rules\store\on-function-explicit-return-type.js:52:38)
```

i.e. the bug is with `eslint-plugin-ngrx`
so it's not related to our project - please file an issue with the rule owner!
