### ISSUE TITLE
[indent-new-do-not-use] Error with ESLint 6.0.0 pre-releases

### ISSUE THREAD

**Issue by teppeis** [typescript-eslint/typescript-eslint#564]
**Repro**

```JSON
{
  "extends": "plugin:@typescript-eslint/eslint-recommended",
}
```

**Expected Result**

Able to parse and lint

**Actual Result**

Error: Failed to load plugin '@typescript-eslint': Cannot find module 'eslint/lib/util/ast-utils'

https://github.com/typescript-eslint/typescript-eslint/blob/cca1714c4bcb7a0349b4e10103870cc46bedf052/packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts#L11

**Additional Info**

```
Error: Failed to load plugin '@typescript-eslint' declared in '--config » ../../+typescript.js': Cannot find module 'eslint/lib/util/ast-utils'
Referenced from: /Users/teppei/src/github.com/teppeis/eslint-config-teppeis/+typescript.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/index.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/requireindex/index.js:52:28
    at Array.forEach (<anonymous>)
    at Object.module.exports [as default] (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/requireindex/index.js:34:11)
    at Object.<anonymous> (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/@typescript-eslint/eslint-plugin/dist/index.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ConfigArrayFactory._loadPlugin (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:858:49)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:29)
    at ConfigArrayFactory._loadExtends (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:606:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:544:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:490:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:544:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:490:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:306:25)
    at ConfigArrayFactory.loadFile (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/config-array-factory.js:381:16)
    at createCLIConfigArray (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:140:35)
    at new CascadingConfigArrayFactory (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:199:29)
    at new CLIEngine (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/node_modules/eslint/lib/cli-engine/cli-engine.js:552:36)
    at verify (/Users/teppei/src/github.com/teppeis/eslint-config-teppeis/test/index.js:23:18)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser` | `1.9.0` |
| `TypeScript`                | `3.4.5` |
| `ESLint`                    | `6.0.0-alpha.2` |
| `node`                      | `10.15.3` |
| `npm`                       | `6.9.0` |

**Comment by platinumazure** [comment]
This is due to ast-utils moving to a different location in the most recent ESLint release.
