### ISSUE TITLE
Repo: Playwright aXe tests sometimes crash with "page.evalute: Target closed"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6003]
### Suggestion

https://github.com/typescript-eslint/typescript-eslint/actions/runs/3480484989/jobs/5820388812

```plaintext
$ /home/runner/work/typescript-eslint/typescript-eslint/node_modules/.bin/playwright test --reporter=list

Running 1 test using 1 worker

  ✘  1 [chromium] › index.spec.ts:4:1 › Index (30s)


  1) [chromium] › index.spec.ts:4:1 › Index ========================================================

    Test timeout of 30000ms exceeded.

    page.evaluate: Target closed

        at AxeBuilder.<anonymous> (/home/runner/work/typescript-eslint/typescript-eslint/node_modules/@axe-core/playwright/src/index.ts:282:15)
        at step (/home/runner/work/typescript-eslint/typescript-eslint/node_modules/@axe-core/playwright/dist/index.js:33:23)
        at Object.next (/home/runner/work/typescript-eslint/typescript-eslint/node_modules/@axe-core/playwright/dist/index.js:[14](https://github.com/typescript-eslint/typescript-eslint/actions/runs/3480484989/jobs/5820388812#step:6:15):53)
        at fulfilled (/home/runner/work/typescript-eslint/typescript-eslint/node_modules/@axe-core/playwright/dist/index.js:5:58)

    Pending operations:
      - page.evaluate at ../../node_modules/@axe-core/playwright/src/index.ts:282:[15](https://github.com/typescript-eslint/typescript-eslint/actions/runs/3480484989/jobs/5820388812#step:6:16)
      - page.evaluate at ../../node_modules/@axe-core/playwright/src/index.ts:[28](https://github.com/typescript-eslint/typescript-eslint/actions/runs/3480484989/jobs/5820388812#step:6:29)3:5
      - page.evaluate at ../../node_modules/@axe-core/playwright/src/index.ts:285:8



  1 failed
    [chromium] › index.spec.ts:4:1 › Index =========================================================
```

😢  you were the chosen one, Playwright!

This _might_ be linked to https://github.com/dequelabs/axe-core-npm/issues/484? I think it is.

For now, i've just been rerunning PRs when this specific failure is seen. 🤷

**Comment by JoshuaKGoldberg** [comment]
Haven't seen this in a while. 🤷
