### ISSUE TITLE
Bug: [no-unsafe-argument] Maximum call stack size exceeded for recursive types

### ISSUE THREAD

**Issue by mxgr7** [typescript-eslint/typescript-eslint#7298]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=FAFwngDgpgBAKgJyrAvDA2gOwK4FsBGUCANPElOgLqXDABm2mAxiAJYD2mMuAhhIsgAUIcgC4yyUnUzjBMmDgJEAlDBQA%2BBXkIJl4gbADewGDCacAziAyYp7JFcpqYI5CZhIQ2BF3TS5ynYOIAB0vBCCwvrkqhrcfAbCUpjKyjQAvkA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWDAPZU%2BDRLABmyKggDmfALbImwyKnhK0PAL4gbQA&tsconfig=N4XyA&tokens=false

### Repro Code

```typescript
type Tree = [number, Tree[]]

function mapTree(tree: Tree, fn: (n: number) => number): Tree {
  const [n, forest] = tree
  return [fn(n), forest.map(t => mapTree(t, fn))]
}
```

### ESLint Config

```javascript
{
  "parser": "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/no-unsafe-argument": "error"
  }
}
```

### tsconfig

```jsonc
{}
```

### Expected Result

I expect eslint to run without errors.

### Actual Result

```
RangeError: Maximum call stack size exceeded
Occurred while linting /input.tsx:6
Rule: "@typescript-eslint/no-unsafe-argument"
    at Mt (https://typescript-eslint.io/sandbox/index.js:111:214546)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215466)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803)
    at Da (https://typescript-eslint.io/sandbox/index.js:111:215803) 6:42 - 6:56
```

### Additional Info

It works if I add an explicit empty array as alternative type:
`type Tree = [number, Tree[] | []]`
instead of:
`type Tree = [number, Tree[]]`

See [playground example](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=FAFwngDgpgBAKgJyrAvDA2gOwK4FsBGUCANPElOgLowA%2BGllwwAZtpgMYgCWA9pjLgCGERMgAUIcgC4yyUs0wyximDgJEAlDBQA%2BVXkIINM0bADewGDHZ8AziAyZ5PJPeppJySzCQhsCfnQFZQ1nVxAAOiEIMQkTci1dAWFTCXlMDQ1GAF8gA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWDAPZU%2BDRLABmyKggDmfALbImwyKnhK0PAL4gbQA&tsconfig=N4XyA&tokens=false).

```
type Tree = [number, Tree[] | []]

function mapTree(tree: Tree, fn: (n: number) => number): Tree {
  const [n, forest] = tree
  return [fn(n), forest.map((t: Tree) => mapTree(t, fn))]
}
```
Result:
```
All is ok!
```

**Comment by auvred** [comment]
Minimal reproduction: [playground](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=C4TwDgpgBAKlC8UDaMC6AodAzArgOwGNgBLAezygCcICdKBnYgNwgAoBDSgcwC5YBKKAG90UKhGB0K1Wg2ZtOXfugC%2BQA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWDAPZU%2BDRLABmyKggDmfALbImwyKnhK0PAL4gbQA&tsconfig=N4XyA&tokens=false)

It seems that infinite recursion occurs in this function
https://github.com/typescript-eslint/typescript-eslint/blob/c869aa1792ed8e3c89d5ada2df8c00f8fe36526a/packages/type-utils/src/isUnsafeAssignment.ts#L75

**Comment by jkowalleck** [comment]
any updates here? 

here is my reproducible me2: https://github.com/CycloneDX/cyclonedx-node-npm/tree/4d6639b3f57b3cb8b84bb821e8e08deb7f55834a
error: https://github.com/CycloneDX/cyclonedx-node-npm/actions/runs/7157963064/job/19489455912?pr=1134#step:5:21
```text
eslint .


Oops! Something went wrong! :(

ESLint: 8.55.0

RangeError: Maximum call stack size exceeded
Occurred while linting /home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/src/builders.ts:249
Rule: "@typescript-eslint/no-unsafe-argument"
    at isTypeAnyType (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/predicates.js:97:23)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:41:40)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
    at isUnsafeAssignment (/home/runner/work/cyclonedx-node-npm/cyclonedx-node-npm/node_modules/@typescript-eslint/type-utils/dist/isUnsafeAssignment.js:83:28)
```

**Comment by bradzacher** [comment]
We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.

If this issue is important to you — consider being that champion.
If not — please use the subscribe function and wait patiently for someone else to implement this.
