### ISSUE TITLE
Bug: using Astro Fragment causes a crash

### ISSUE THREAD

**Issue by arty-name** [typescript-eslint/typescript-eslint#7886]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I have configured ESLint with `standard-with-typescript` and added `plugin:@typescript-eslint/strict-type-checked`. I have configured `astro-eslint-parser`. With this my Astro components are linted okay.

Once I try to render raw HTML using `<Fragment set:html={rawHTML} />` the ESLint crashes:

```
Oops! Something went wrong! :(

ESLint: 8.51.0

TypeError: Cannot read properties of undefined (reading 'parent')
Occurred while linting src/pages/index.astro:6
Rule: "@typescript-eslint/no-unsafe-assignment"
    at Object.getContextualType (node_modules/@typescript-eslint/type-utils/dist/getContextualType.js:34:25)
    at checkAssignment (node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment.js:182:24)
    at JSXAttribute[value != null] (node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment.js:279:17)
    at ruleErrorHandler (node_modules/eslint/lib/linter/linter.js:1091:28)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

I don’t have the expertise to decide which of the integrated components should be adjusted, and rely on your judgement.

### Reproduction Repository Link

https://github.com/arty-name/typescript-eslint-astro-fragment

### Repro Steps

1) clone the repo
2) `yarn install`
3) `yarn dev`

The repository might look funny because it started as an attempt to reproduce directly on StackBlitz, but the [linter hangs there](https://stackblitz.com/~/github.com/arty-name/typescript-eslint-astro-fragment) and I don’t know whether this is a supported use case.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.9.1` |
| `@typescript-eslint/parser`            | `6.9.1` |
| `ESLint`                               | `8.53.0` |
| `node`                                 | `20.5.1` |

**Comment by bradzacher** [comment]
I guess that the astro parser doesn't support type-aware linting and is doing some bad things with the parsing result.

You can disable type-aware linting on your astro files.


https://typescript-eslint.io/linting/typed-linting#how-can-i-disable-type-aware-linting-for-a-subset-of-files
