### ISSUE TITLE
[no-floating-promises] TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by glen-84** [typescript-eslint/typescript-eslint#815]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-floating-promises": "error",
  }
}
```

```TS
let team1score = 0;

team1score++;
```

**Expected Result**

No error.

**Actual Result**

```
[Error - 09:30:32] TypeError: Cannot read property 'kind' of undefined
Occurred while linting D:\Programming\Projects\...\src\app\test.ts:3
    at isUnhandledPromise (D:\Programming\Projects\...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-floating-promises.js:47:28)
    at ExpressionStatement (D:\Programming\Projects\...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-floating-promises.js:34:21)
    at listeners.(anonymous function).forEach.listener (d:\Programming\Projects\...\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (d:\Programming\Projects\...\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (d:\Programming\Projects\...\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (d:\Programming\Projects\...\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (d:\Programming\Projects\...\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (d:\Programming\Projects\...\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:645:23)
    at nodeQueue.forEach.traversalInfo (d:\Programming\Projects\...\node_modules\eslint\lib\linter\linter.js:885:32)
```

**Additional Info**

(Let me know if the stack trace above is insufficient.)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.13.0` |
| `@typescript-eslint/parser`        | `1.13.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `6.1.0` |
| `node`                             | `10.16.0` |
| `npm`                              | `6.9.0` |

**Comment by bradzacher** [comment]
seems like a misunderstanding `ts.isBinaryExpression` - returns true for `PostfixUnaryExpression`

**Comment by raymondfeng** [comment]
We're running into the same issue with TypeScript 3.7.2.

**Comment by bradzacher** [comment]
I'm unable to repro this against master:

```
 PASS  tests/rules/no-floating-promises.test.ts (5.107s)
  no-floating-promises
    valid
      ✓ 
let team1score = 0;
team1score++;
     (1150ms)
```

Looking at your versions - you're on a v old version of the plugin.
