### ISSUE TITLE
Bug: [consistent-type-assertions] error when type check is disabled for vue files

### ISSUE THREAD

**Issue by kuoruan** [typescript-eslint/typescript-eslint#8153]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://codesandbox.io/p/devbox/delicate-platform-64cd72

### Repro Code

```TypeScript
error reported when vue files have no `<script lang="ts">` block defined.

npm run lint
```

### ESLint Config

```javascript
module.exports = {
  root: true,
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
  ],
  parserOptions: {
    project: ["./tsconfig.json", "./tsconfig.node.json"],
  },
  overrides: [
    {
      files: ["*.vue"],
      extends: [
        "plugin:@typescript-eslint/disable-type-checked",
        "plugin:vue/vue3-recommended",
      ],
    },
  ],
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["ESNext", "DOM"],
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
}
```

### Expected Result

No error report

### Actual Result

```
Error: Error while loading rule '@typescript-eslint/consistent-type-assertions': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /workspaces/workspace/src/App.vue
    at getParserServices (/workspaces/workspace/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:21:15)
    at create (/workspaces/workspace/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-assertions.js:90:61)
    at Object.create (/workspaces/workspace/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
    at createRuleListeners (/workspaces/workspace/node_modules/eslint/lib/linter/linter.js:895:21)
    at /workspaces/workspace/node_modules/eslint/lib/linter/linter.js:1066:110
    at Array.forEach (<anonymous>)
    at runRules (/workspaces/workspace/node_modules/eslint/lib/linter/linter.js:1003:34)
    at Linter._verifyWithoutProcessors (/workspaces/workspace/node_modules/eslint/lib/linter/linter.js:1355:31)
    at /workspaces/workspace/node_modules/eslint/lib/linter/linter.js:1913:29
    at Array.map (<anonymous>)
 ```

### Additional Info

#7723

**Comment by auvred** [comment]
Could you try to do the following? 

```diff
module.exports = {
  root: true,
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/stylistic",
  ],
  parserOptions: {
    project: ["./tsconfig.json", "./tsconfig.node.json"],
  },
  overrides: [
    {
      files: ["*.vue"],
+     parserOptions: {
+       parser: '@typescript-eslint/parser',
+     },
      extends: [
        "plugin:@typescript-eslint/disable-type-checked",
        "plugin:vue/vue3-recommended",
      ],
    },
  ],
};
```

**Comment by kuoruan** [comment]
Hi @auvred 
Thank you for the information.
`consistent-type-assertions` works when set parser to `@typescript-eslint/parser`

In my original repo. I set paser to:
```
parser: {
    ts: "@typescript-eslint/parser",
    tsx: "@typescript-eslint/parser",
    js: "espree",
    jsx: "espree",
    "<template>": "@typescript-eslint/parser",
 },
 ```
 
 It will get the same error.
 Maybe it is a issue of `vue-eslint-parser`?

**Comment by kuoruan** [comment]
But only `consistent-type-assertions` shows this error. Every thing works when I disable it.

**Comment by auvred** [comment]
It's because `consistent-type-assertions` requires parser services to be generated https://github.com/typescript-eslint/typescript-eslint/blob/cde4d4d028ac9542a3372bf12c82ebfc137b5ae5/packages/eslint-plugin/src/rules/consistent-type-assertions.ts#L95

**Comment by kuoruan** [comment]
related to vuejs/vue-eslint-parser#104

set `parser.js` to `@typescript-eslint/parser` fixed this.

because the `parser.js` is returned by default
https://github.com/vuejs/vue-eslint-parser/blob/92dd3f306c30b3991a81eaca519286bc97b5f7ba/src/common/parser-options.ts#L97
