### ISSUE TITLE
Repo: ast-spec snapshot failures on main

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8698]
### Suggestion

I merged #8209 with `ast-spec` snapshot failures in the build because (a) I'm 100% confident that PR didn't introduce them and (b) I wanted to get the >150 file PR to stop receiving merge conflicts. `main` was probably going to start failing separate from that PR anyway. And now we have failures on the `main` branch commits. Example from https://github.com/typescript-eslint/typescript-eslint/actions/runs/8316456951/job/22755967761:

```plaintext
  ● AST Fixtures › legacy-fixtures › basics › type-import-type-with-type-parameters-in-type-reference › Babel - AST
    expect(received).toMatchSnapshot()
    Snapshot name: `AST Fixtures legacy-fixtures basics type-import-type-with-type-parameters-in-type-reference Babel - AST 1`
    - Snapshot  - 0
    + Received  + 1
    @@ -39,10 +39,11 @@
                      loc: {
                        start: { column: 18, line: 3 },
                        end: { column: 20, line: 3 },
                      },
                    },
    +               options: null,
                    qualifier: Identifier {
                      type: "Identifier",
                      name: "B",
                      range: [95, 96],

      227 |           it('Babel - AST', () => {
      228 |             expectSuccessResponse(babelParsed);
    > 229 |             expect(babelParsed.ast).toMatchSpecificSnapshot(
          |                                     ^
      230 |               fixture.snapshotFiles.success.babel.ast(snapshotCounter++),
      231 |             );
      232 |           });

      at Object.toMatchSpecificSnapshot (tests/fixtures.test.ts:229:37)
  ● AST Fixtures › legacy-fixtures › basics › type-import-type-with-type-parameters-in-type-reference › AST Alignment - AST
    expect(received).toMatchSnapshot()
    Snapshot name: `AST Fixtures legacy-fixtures basics type-import-type-with-type-parameters-in-type-reference AST Alignment - AST 1`
    - Snapshot  - 12
    + Received  + 13
    @@ -42,28 +42,29 @@
      -                 type: 'TSLiteralType',
      -                 literal: Literal {
      -                   type: 'Literal',
      -                   raw: '\'\'',
      -                   value: '',
    - +argument: Literal {
    - +                 type: 'Literal',
    - +                 raw: '\'\'',
    - +                 value: '',
    -
    - - range: [91, 93],
    + -
    + -    range: [91, 93],
    + -                   loc: {
    + -                     start: { column: 18, line: 3 },
    + -                     end: { column: 20, line: 3 },
    + - },
    - -                   loc: {
    - -      start: { column: 18, line: 3 },
    - -                     end: { column: 20, line: 3 },
    + -                 },
    + +argument: Literal {
    + +                 type: 'Literal',
    - -  },
    + +raw: '\'\'',
    - -},
    + +value: '',
    - -
    +
                        range: [91, 93],
                    end: { column: 27, line: 3 },
    @@ -110,10 +111,11 @@
                  loc: {
                    start: { column: 16, line: 4 },
                    end: { column: 19, line: 4 },
                  },
                },
    + +         options: null,
                qualifier: Identifier {
                  type: 'Identifier',
      -           decorators: Array [],
                  name: 'X',
      -           optional: false,

      246 |               babelParsed.ast,
      247 |             );
    > 248 |             expect(diffResult).toMatchSpecificSnapshot(
          |                                ^
      249 |               fixture.snapshotFiles.success.alignment.ast(snapshotCounter++),
      250 |             );
      251 |

      at Object.toMatchSpecificSnapshot (tests/fixtures.test.ts:248:32)
 › 4 snapshots failed.
Snapshot Summary
 › 4 snapshots failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.
Test Suites: 1 failed, 1 total
Tests:       4 failed, 4061 passed, 4065 total
Snapshots:   4 failed, 3408 passed, 3412 total
Time:        6.067 s
```

My guess is this is some kind of merge artifact/conflict from dependency bumps.

**Comment by JoshuaKGoldberg** [comment]
> I'm 100% confident that PR didn't introduce them

...that's now 99% confident. I just noticed `@babel/*` versions aren't all their latest. Maybe something was out of date / out of sync.
