### ISSUE TITLE
Repo: Integration tests failing on main with ESLint v9

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8864]
### Suggestion

https://github.com/typescript-eslint/typescript-eslint/actions/runs/8576187098/job/23507175593

```plaintext
 FAIL  tests/flat-config-types.test.ts (60.052 s)
  ● flat-config-types › eslint › should work successfully
    expect(received).toMatchSnapshot()
    Snapshot name: `flat-config-types eslint should work successfully 1`
    - Snapshot  - 10
    + Received  +  1
    @@ -107,18 +107,9 @@
          ...jestPlugin.configs['flat/recommended'],
        )
      }
      ",
          "suppressedMessages": [],
    -     "usedDeprecatedRules": [
    -       {
    -         "replacedBy": [],
    -         "ruleId": "no-extra-semi",
    -       },
    -       {
    -         "replacedBy": [],
    -         "ruleId": "no-mixed-spaces-and-tabs",
    -       },
    -     ],
    +     "usedDeprecatedRules": [],
          "warningCount": 0,
        },
      ]

      173 |     try {
      174 |       const lintOutput = JSON.parse(lintOutputRAW);
    > 175 |       expect(lintOutput).toMatchSnapshot();
          |                          ^
      176 |     } catch {
      177 |       throw new Error(
      178 |         `Lint output could not be parsed as JSON: \`${lintOutputRAW}\`.`,

      at toMatchSnapshot (tools/integration-test-base.ts:175:26)
      at Object.<anonymous> (tools/integration-test-base.ts:120:9)
 › 1 snapshot failed.
```

---

Looks like this is because of ESLint v9:

This change is included in the v9 release - https://github.com/eslint/eslint/pull/17716 

From https://github.com/eslint/eslint/pull/17716:

> Removed deprecated rules no-extra-semi and no-mixed-spaces-and-tabs.

**Comment by bradzacher** [comment]
That would be due to the v9 release yeah
This loops back to us really needing the integration tests to run in a separate job rather than just on main.
