### ISSUE TITLE
Repo: Weekly release flow is failing on changelogRenderer again

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9158]
### Suggestion

This looks similar to #8437 -> #8439:

```plaintext
 NX   Generating an entry in CHANGELOG.md for v7.11.0

/home/runner/work/.../.../typescript-eslint/node_modules/nx/src/command-line/release/changelog.js:444
    let contents = await changelogRenderer({
                         ^
TypeError: changelogRenderer is not a function
    at generateChangelogForWorkspace (/home/runner/work/.../.../typescript-eslint/node_modules/nx/src/command-line/release/changelog.js:444:26)
    at releaseChangelog (/home/runner/work/.../.../typescript-eslint/node_modules/nx/src/command-line/release/changelog.js:134:38)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/.../private
```

cc @JamesHenry

**Comment by JoshuaKGoldberg** [comment]
Oh, we're not on the latest version of nx:

https://github.com/typescript-eslint/typescript-eslint/blob/5b811a348c4140721cd4266d9f2564d22ba46e48/package.json#L114

That explains why the changes in https://github.com/nrwl/nx/pull/23214 aren't showing up locally for me. Heh.

**Comment by JoshuaKGoldberg** [comment]
Putting some logs in `node_modules/nx/src/command-line/release/changelog.js` and then running `yarn release` (note that our `dryRun` mode is enabled):

```plaintext
{ changelogRendererPath: './tools/release/changelog-renderer' }
{
  interpolatedChangelogRendererPath: './tools/release/changelog-renderer'
}
 NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed
{
  error: TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
      at fileURLToPath (node:internal/url:1393:11)
      at finalizeResolution (node:internal/modules/esm/resolve:265:42)
      at moduleResolve (node:internal/modules/esm/resolve:917:10)
      at defaultResolve (node:internal/modules/esm/resolve:1130:11)
      at nextResolve (node:internal/modules/esm/hooks:865:28)
      at h (file:///Users/josh/repos/typescript-eslint/node_modules/tsx/dist/esm/index.mjs?1716831076734:2:1939)
      at j (file:///Users/josh/repos/typescript-eslint/node_modules/tsx/dist/esm/index.mjs?1716831076734:2:3056)
      at nextResolve (node:internal/modules/esm/hooks:865:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:358:35) {
    code: 'ERR_INVALID_URL_SCHEME'
  }
}
```

**Comment by JoshuaKGoldberg** [comment]
If I `yarn add @swc-node/register -D`:

```plaintext
{ changelogRendererPath: 'tools/release/changelog-renderer.js' }
{
  interpolatedChangelogRendererPath: 'tools/release/changelog-renderer.js'
}
{
  error: TypeError: Cannot assign to read only property '.mjs' of object '[object Object]'
      at /Users/josh/repos/typescript-eslint/node_modules/pirates/lib/index.js:101:44
      at Array.forEach (<anonymous>)
      at addHook (/Users/josh/repos/typescript-eslint/node_modules/pirates/lib/index.js:95:8)
      at register (/Users/josh/repos/typescript-eslint/node_modules/@swc-node/register/register.ts:135:17)
      at getSwcTranspiler (/Users/josh/repos/typescript-eslint/node_modules/nx/src/plugins/js/utils/register.js:40:23)
      at /Users/josh/repos/typescript-eslint/node_modules/nx/src/plugins/js/utils/register.js:77:22
      at registerTranspiler (/Users/josh/repos/typescript-eslint/node_modules/nx/src/plugins/js/utils/register.js:100:12)
      at registerTsProject (/Users/josh/repos/typescript-eslint/node_modules/nx/src/plugins/js/utils/register.js:15:9)
      at resolveChangelogRenderer (/Users/josh/repos/typescript-eslint/node_modules/nx/src/command-line/release/changelog.js:375:66)
      at generateChangelogForWorkspace (/Users/josh/repos/typescript-eslint/node_modules/nx/src/command-line/release/changelog.js:427:31)
}
```

😭

**Comment by JoshuaKGoldberg** [comment]
I've also tried updating nx to 19. Same error, with a slightly nicer display.

```plaintext
$ yarn release

 NX   There was an error when resolving the configured changelog renderer at path: tools/release/changelog-renderer

(same errors as before)
```

I have no idea what to do here. 🙁

**Comment by JoshuaKGoldberg** [comment]
All right, @JamesHenry very kindly helped me out by noting that it's really just the TypeScript registration (`register_1.registerTsProject`) that was crashing. We don't need that because we author the tool in JS.
