### ISSUE TITLE
Bug: packages incorrectly publishes `.js.map` breaking stack traces

### ISSUE THREAD

**Issue by johnsoncodehk** [typescript-eslint/typescript-eslint#9352]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### Repro Code

```TypeScript
try {
	require('source-map-support').install();
	require('@typescript-eslint/typescript-estree').createProgram('fake-tsconfig.json');
} catch (err) {
	console.error(err);
}
```

### Expected Result

The console correctly prints the line of code in the .js that threw the error.
```
Error: error TS5012: Cannot read file 'fake-tsconfig.json': ENOENT: no such file or directory, open 'fake-tsconfig.json'.

    at Object.onUnRecoverableConfigFileDiagnostic (.../node_modules/@typescript-eslint/typescript-estree/dist/create-program/useProvidedPrograms.js:71:19)
```

### Actual Result

The line of code printed by the console points to a `.ts` file that is not included in the npm release.
```
Error: error TS5012: Cannot read file 'fake-tsconfig.json': ENOENT: no such file or directory, open 'fake-tsconfig.json'.

    at Object.onUnRecoverableConfigFileDiagnostic (.../node_modules/@typescript-eslint/typescript-estree/src/create-program/useProvidedPrograms.ts:71:15)
```

### Additional Info

Currently .js.map files is published to npm but does not come with source .ts files. This causes source map tools like [source-map-support](https://npmjs.com/package/source-map-support) to fail in converting source lines.

Related PR: #9351

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.13.0` |
| `@typescript-eslint/parser`            | `7.13.0` |
| `@typescript-eslint/rule-tester`       | `7.13.0` |
| `@typescript-eslint/scope-manager`     | `7.13.0` |
| `@typescript-eslint/typescript-estree` | `7.13.0` |
| `@typescript-eslint/type-utils`        | `7.13.0` |
| `@typescript-eslint/utils`             | `7.13.0` |

**Comment by bradzacher** [comment]
> The line of code printed by the console points to a .ts file that is not included in the npm release.

Well really - that's intentional.
If you're reporting bugs to us we'd love to see the `.ts` locations instead of the `.js` ones.
But the source isn't useful for consumers - so no real need to ship it.

Is there a reason you want the `.js` paths in stack traces here?

**Comment by johnsoncodehk** [comment]
> If you're reporting bugs to us we'd love to see the `.ts` locations instead of the `.js` ones.

Only consume `.js.map` in the error stack when users are using `source-map-support`, and this use case practically doesn't exist unless people intentionally install `source-map-support` before reproducing and reporting errors.

> Is there a reason you want the `.js` paths in stack traces here?

I need to display the file path and line of code where the error is thrown in the IDE to track the source of the error, if it points to a non-existent .ts file, the IDE will just try to open a non-existent file causing this functionality to be broken.

**Comment by JoshuaKGoldberg** [comment]
🤔 this seems like a downstream tooling issue with `source-map-support` to me. It's pretty common that packages will want to:

* Have published source maps trace back to the original `.ts` sources, to be accurate
* Not ship copious amounts of `.ts` sources

I was surprised looking through typescript-eslint's relatively standalone-ish `devDependencies` how many didn't publish sourcemaps:
* [`execa`](https://unpkg.com/browse/execa@9.3.0/)
* [`prettier`](https://unpkg.com/browse/prettier@3.3.2/)
* [`tmp`](https://unpkg.com/browse/tmp@0.2.3/)
* [`tsx`](https://unpkg.com/browse/tsx@4.15.8/)
* [`typescript`](https://unpkg.com/browse/typescript@5.5.2/lib/)

Do you have examples of common/popular libraries that _do_ publish sourcemaps pointing to files either published sources or built outputs @johnsoncodehk?

**Comment by johnsoncodehk** [comment]
> Do you have examples of common/popular libraries that _do_ publish sourcemaps pointing to either published sources or built outputs @johnsoncodehk?

I've heard that some developers prefer to send all files for a project as-is (.js + .ts + sourcemaps...), but I don't remember that project. In my experience sending sourcemaps without sending source TS files is usually because the maintainer forgot to exclude the sourcemaps.

I understand the correct approach is to **not** send sourcemaps and source TS files to reduce npm bundle size, and sending them doesn't really help with debugging.

**Comment by JoshuaKGoldberg** [comment]
> If you're reporting bugs to us we'd love to see the `.ts` locations instead of the `.js` ones.

This is nice in general ... but since we've gotten stricter about either using the playground or providing a full repro, I haven't actually needed this in a while.

I'd be in favor of removing the `.map` files from the published output for v8 as a package size reduction _if_:

* There isn't a specific reason why we have them there (e.g. a tooling integration that wants them)
* There wouldn't be significant user irritation from no longer having them

**Comment by JoshuaKGoldberg** [comment]
We talked a bit privately. There isn't time to do this for v8, but we have general interest for the next major version that has breaking changes beyond dependency versions.

Coincidentally, I stumbled onto this trying out making a sample ESLint plugin (#9676). Isolated reproduction here: https://github.com/JoshuaKGoldberg/repros/tree/repro-rule-tester-eslint-parse-error.

```plaintext
 FAIL  src/no-loop-over-enum.test.ts > no-loop-over-enum > invalid >
          enum Values { value }
          for (const a in Values) {}

TypeError: Cannot read properties of undefined (reading 'parse')
 ❯ parse node_modules/eslint/lib/linter/linter.js:906:29
 ❯ Linter._verifyWithFlatConfigArrayAndWithoutProcessors node_modules/eslint/lib/linter/linter.js:1660:33
 ❯ Linter._verifyWithFlatConfigArray node_modules/eslint/lib/linter/linter.js:2017:21
 ❯ Linter.verify node_modules/eslint/lib/linter/linter.js:1492:61
 ❯ RuleTester.runRuleForItem node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:710:33
 ❯ RuleTester.#testInvalidTemplate node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:862:25
 ❯ node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:513:40
```

Those stack traces don't line up to files on disk. It's inconvenient to not be able to Cmd/Ctrl-click them in VS Code.

**Comment by bluwy** [comment]
It looks like since v8.25.0 ([diff between v8.24.1](https://npmdiff.dev/%40typescript-eslint%2Futils/8.24.1/8.25.0/)), which includes https://github.com/typescript-eslint/typescript-eslint/pull/10361, it has [set `"sourcemap": false`](https://github.com/typescript-eslint/typescript-eslint/pull/10361/files#diff-0b280a445be167f54cd916c0718c952b8e0d4ca9621903d05eec25efd4c6ed6dL17-R27) in the `tsconfig.json` so there's no more `.js.map` files being generated. So this issue is now indirectly resolved.

**Comment by JoshuaKGoldberg** [comment]
😂 lovely! Given that it's been six months and nobody has mentioned anything, I think we can treat this & #11613 as _not_ breaking changes. Thanks!
