### ISSUE TITLE
Bug: can't enable recommendedTypeChecked and lint tsx files

### ISSUE THREAD

**Issue by damianobarbati** [typescript-eslint/typescript-eslint#9368]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

`tslint.configs.recommendedTypeChecked` not working on tsx files.

Repro here: <https://github.com/damianobarbati/eslint-v9>

To reproduce:
```sh
git clone git@github.com:damianobarbati/eslint-v9.git
cd eslint-v9
pnpm i
pnpm eslint src/__tests__/test.tsx
```

Output:
```sh
Oops! Something went wrong! :(

ESLint: 9.5.0

ConfigError: Config (unnamed): Unexpected key "0" found.
    at rethrowConfigError (/Users/damians/Desktop/eslint-v9/node_modules/.pnpm/@eslint+config-array@0.16.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:302:8)
    at /Users/damians/Desktop/eslint-v9/node_modules/.pnpm/@eslint+config-array@0.16.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1097:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/Users/damians/Desktop/eslint-v9/node_modules/.pnpm/@eslint+config-array@0.16.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1090:43)
    at FlatConfigArray.getConfig (/Users/damians/Desktop/eslint-v9/node_modules/.pnpm/@eslint+config-array@0.16.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1119:15)
    at /Users/damians/Desktop/eslint-v9/node_modules/.pnpm/eslint@9.5.0/node_modules/eslint/lib/eslint/eslint.js:870:40
    at Array.map (<anonymous>)
    at ESLint.lintFiles (/Users/damians/Desktop/eslint-v9/node_modules/.pnpm/eslint@9.5.0/node_modules/eslint/lib/eslint/eslint.js:868:23)
    at async Object.execute (/Users/damians/Desktop/eslint-v9/node_modules/.pnpm/eslint@9.5.0/node_modules/eslint/lib/cli.js:500:23)
    at async main (/Users/damians/Desktop/eslint-v9/node_modules/.pnpm/eslint@9.5.0/node_modules/eslint/bin/eslint.js:153:22)
```

### Reproduction Repository Link

https://github.com/damianobarbati/eslint-v9

### Repro Steps

```sh
git clone git@github.com:damianobarbati/eslint-v9.git
cd eslint-v9
pnpm i
pnpm eslint src/__tests__/test.tsx
```

### Versions

All latest.

**Comment by bradzacher** [comment]
This isn't a bug with anything. Your config is just wrong somewhere.

Have you tried debugging to figure out which config is breaking? For example - comment each config out one by one to determine which one is the one that's breaking things?

**Comment by bradzacher** [comment]
This isn't correct
https://github.com/damianobarbati/eslint-v9/blob/main/src%2Fconfigs%2Freact.js#L21

As per the compat module's docs
https://github.com/eslint/rewrite/blob/main/packages/compat/README.md#fixing-plugins
