### ISSUE TITLE
Could not be resolved function types in TSX props

### ISSUE THREAD

**Issue by kidkkr** [typescript-eslint/typescript-eslint#966]
**What code were you trying to parse?**
I use `@typescript-eslint/parser`  parser for TypeScript files.

```ts
<MyButton
  // ... some codes
  onClick={handleSubmit as ((e: any) => void)}
/>
```

**What did you expect to happen?**
Parse `((e: any)=> void)` as usual type.

**What actually happened?**
```
Error: The prop value with an expression type of TSAsExpression could not be resolved.

Please file issue to get this fixed immediately.
Occurred while linting /Users/MyProject/src/MyComponent.tsx:151
    at Object.extract [as JSXExpressionContainer] (/Users/MyProject/node_modules/jsx-ast-utils/lib/values/expressions/index.js:179:11)
    at getValue (/Users/MyProject/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
    at extractValue (/Users/MyProject/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getPropValue (/Users/MyProject/node_modules/jsx-ast-utils/lib/getPropValue.js:41:10)
    at /Users/MyProject/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-interactions.js:90:95
    at Array.some (<anonymous>)
    at JSXOpeningElement (/Users/MyProject/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-noninteractive-element-interactions.js:89:52)
    at listeners.(anonymous function).forEach.listener (/Users/MyProject/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/MyProject/node_modules/eslint/lib/util/safe-emitter.js:45:38)
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.1.0` |
| `TypeScript`                | `3.4.5` |
| `ESLint`                    | `5.12.0` |
| `node`                      | `8.14.1` |
| `npm`                       | `6.11.3` |

**Comment by bradzacher** [comment]
This is not a bug in this project, this is a bug in `eslint-plugin-jsx-a11y`.
You should file an issue in that package's repo.
