### ISSUE TITLE
Docs: Clarity issue on Flat config `extends` description

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9733]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Coming over from https://stackoverflow.com/questions/78827606/configure-eslint-eslint-config-js-to-only-analyze-typescript-files-ts/78828601?noredirect=1#comment138996204_78828601: re-reading the description in https://typescript-eslint.io/packages/typescript-eslint/#flat-config-extends:

> The `tseslint.config` utility function also adds handling for the `extends` property on flat config objects. This allows you to more easily extend shared configs for specific file patterns whilst also overriding rules/options provided by those configs:

...I do agree with the friendly StackOverflow commenter that the docs aren't super clear on what the thing _does_. They just speak to its purpose.

I'm thinking something like this as a rephrase, maybe?

> `tseslint.config` takes in a config object that includes an `extends` array of configs to extend. It returns the equivalent ESLint config of applying the rest of the settings for each extension.

### Affected URL(s)

https://typescript-eslint.io/packages/typescript-eslint/#flat-config-extends

**Comment by kirkwaiblinger** [comment]
+1, also the current docs are contradictory, in that they say it's a variadic identity function, but then go on to describe its `extends` feature. https://typescript-eslint.io/packages/typescript-eslint#config. IMO we should be more precise about that wording, because the current wording leaves me wondering "what other implicit magic does it also do?"

**Comment by SalahAdDin** [comment]
It is not clear for us how exactly to extend the rules:
```js
  {
    ...typescript.configs.recommendedTypeChecked,
    rules: {
      "@typescript-eslint/array-type": [
        "error",
        {
          default: "generic",
        },
      ],
      "@typescript-eslint/ban-ts-comment": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/explicit-function-return-type": 1,
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "typeParameter",
          format: ["PascalCase"],
          custom: { regex: "^T[A-Z]", match: true },
        },
      ],
      "@typescript-eslint/switch-exhaustiveness-check": "error",
    },
  },
```

It gives us the following issue:
```bash
Oops! Something went wrong! :(

ESLint: 9.9.0

ConfigError: Config (unnamed): Unexpected key "0" found.
    at rethrowConfigError (/media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/@eslint+config-array@0.17.1/node_modules/@eslint/config-array/dist/cjs/index.cjs:303:8)
    at /media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/@eslint+config-array@0.17.1/node_modules/@eslint/config-array/dist/cjs/index.cjs:1098:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/@eslint+config-array@0.17.1/node_modules/@eslint/config-array/dist/cjs/index.cjs:1091:43)
    at FlatConfigArray.getConfig (/media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/@eslint+config-array@0.17.1/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at /media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/eslint@9.9.0_jiti@1.21.6/node_modules/eslint/lib/eslint/eslint-helpers.js:346:56
    at Array.reduce (<anonymous>)
    at /media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/eslint@9.9.0_jiti@1.21.6/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36
    at /media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/eslint@9.9.0_jiti@1.21.6/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32
    at Object.isAppliedFilter (/media/Storage/Projects/Experiments/react-ts-vite-template/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 2.
 ```
 
 
 It could be cause we don't understand pretty well how the new configuration works.
 
 ```js
  ...typescript.configs.recommendedTypeChecked,
  {
    rules: {
      "@typescript-eslint/array-type": [
        "error",
        {
          default: "generic",
        },
      ],
      "@typescript-eslint/ban-ts-comment": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/explicit-function-return-type": 1,
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "typeParameter",
          format: ["PascalCase"],
          custom: { regex: "^T[A-Z]", match: true },
        },
      ],
      "@typescript-eslint/switch-exhaustiveness-check": "error",
    },
  },
```
It works, but we think it is overwriting the global configuration, or not? We are not sure about it.

**Comment by kirkwaiblinger** [comment]
@SalahAdDin it won't make sense to spread the `tseslint.configs.recommendedTypeChecked` into an object, since it's an array of config objects, not an object itself. (when you do so, JS will spread the array keys, starting with "0", which explains the error you see when eslint tries to interpret the config.)

The code that you've written in order to get it working is the same thing as what the `extends` would do... in other words, 
```ts
export default tseslint.config(
   ...tseslint.configs.recommendedTypeChecked,
   {
      "rules": {
          // your customizations here
      }
   }
);
```
has the same output as 
```ts
export default tseslint.config(
   {
      "extends": tseslint.configs.recommendedTypeChecked,
      "rules": {
          // your customizations here
      }
   }
);
```

**Comment by SalahAdDin** [comment]
> @SalahAdDin it won't make sense to spread the `tseslint.configs.recommendedTypeChecked` into an object, since it's an array of config objects, not an object itself. (when you do so, JS will spread the array keys, starting with "0", which explains the error you see when eslint tries to interpret the config.)
> 
> The code that you've written in order to get it working is the same thing as what the `extends` would do... in other words,
> 
> ```ts
> export default tseslint.config(
>    ...tseslint.configs.recommendedTypeChecked,
>    {
>       "rules": {
>           // your customizations here
>       }
>    }
> );
> ```
> 
> has the same output as
> 
> ```ts
> export default tseslint.config(
>    {
>       "extends": tseslint.configs.recommendedTypeChecked,
>       "rules": {
>           // your customizations here
>       }
>    }
> );
> ```

I'm confused since other plugins like [`react`](https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#flat-configs) it extends the rules in its own object; I guess this plugin does not support flat config.

**Comment by kirkwaiblinger** [comment]
> I'm confused since other plugins like [`react`](https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#flat-configs) it extends the rules in its own object; I guess this plugin does not support flat config.

I'm not sure I'm following your meaning... If I had to guess, the confusion you're experiencing has to do with the fact that our `tseslint.configs.recommendedTypeChecked` is an array, not just a single object. But, regardless, it sounds like this is veering far off-topic from this issue, which is purely about explaning what the `extends` field in a rule object does when used with the `tseslint.config()` helper. Would you kindly spin off a new issue or reach out in the discord if you want to continue this conversation more broadly than that topic? Thanks! 

As for the last part, if by "this plugin" you're referring to us, typescript-eslint, that is false. We support the flat config.

**Comment by SalahAdDin** [comment]
> > I'm confused since other plugins like [`react`](https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#flat-configs) it extends the rules in its own object; I guess this plugin does not support flat config.
> 
> I'm not sure I'm following your meaning... If I had to guess, the confusion you're experiencing has to do with the fact that our `tseslint.configs.recommendedTypeChecked` is an array, not just a single object. But, regardless, it sounds like this is veering far off-topic from this issue, which is purely about explaning what the `extends` field in a rule object does when used with the `tseslint.config()` helper. Would you kindly spin off a new issue or reach out in the discord if you want to continue this conversation more broadly than that topic? Thanks!
> 
> As for the last part, if by "this plugin" you're referring to us, typescript-eslint, that is false. We support the flat config.

```js
  {
    files: ['**/*.{js,mjs,cjs,jsx,mjsx,ts,tsx,mtsx}'],
    ...reactPlugin.configs.flat.recommended,
    languageOptions: {
      ...reactPlugin.configs.flat.recommended.languageOptions,
      globals: {
        ...globals.serviceworker,
        ...globals.browser,
      },
    },
  },
```

I meant this, it is extending the flat config; it is not the same way with this plugin.
