### ISSUE TITLE
Bug: Maximum call stack size exceeded for long binary operators

### ISSUE THREAD

**Issue by sosukesuzuki** [typescript-eslint/typescript-eslint#9773]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=LAKARAhlVgBA1KWtLQnRJmuhpK10F8cZisC08LSjNtDqGrzndXL37OzvamedEow79RIvhOEtJM6V3m9FQmlNVz1CzUu0q2O-XsECxsrYZNqL4jdbMHjN84-tHTyy7ZcenD97s9nfzsfV0C-K28A3zdI4KiQ6LCY8NiveIy4rPTsoNyInMK8ooListKKtPKqytS6lIbkptCWpNbEjoSuzJKavvrmtqHOnuqB9u78-saJ0dqZ4cne8cW56cGRqZXN5YWdsb2lg42j%2BZO17dP12a3Di7vb88eb3afXl%2BOPs6-r1ee-94Az5A74g377UEQ8FXS73N7AqGw-6Ih6AlHwyEw1EIrEY6Fwn5ItG4wnYzEEsFEnEU9GkvFU8nIkmUsn4pk05m0ln01kMtnEjmC9nCgUi6lixmiqXi6WSmXyuWK-kK5VKvnq3mannaum67l6rmGznGoWy1XmjU6-XWo2mlWWg0miUWrWOu1q102p1mh1e90uq2252%2BoM%2Bz2h%2B3h72RwPRj2x-0huMBt3BqOJ9NphNZ1Nh7N53Mxwvx4spv058sFytF6sl2tliN1xsN5NJjP5mvNtsVruZqu9jtN1t9zvDwct9ul7v9sdTkdDyf16ejxcDufj5cLnuzpfzifb1c7te7jd7zf7meHq8Hm%2BX28r%2B9bu-Ph8vp%2Bvj-vr8Xz8-7-ngCzyA08QPXMCT3A48oKPGDrzfP8EMA0CIJQ6C4N-JDINgx9EOArD0P-PDUOw%2BDMOIgjcOQtCcLI6jSKIuiMIYkimKoljCLYijaPYyj8Jo5iuLPABuIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
import { parse } from "@typescript-eslint/typescript-estree";

const code = `"aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa" +
  "aaaaa";`;

parse(code);
```

### ESLint Config

```javascript
// Using parser directly
```

### tsconfig

```jsonc
// Using parser directly
```

### Expected Result

No error

### Actual Result

```
RangeError: Maximum call stack size exceeded
    at #checkModifiers (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:2399:20)
    at Converter.converter (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:82:29)
    at Converter.convertNode (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:1588:32)
    at Converter.converter (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:87:29)
    at Converter.convertNode (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:1588:32)
    at Converter.converter (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:87:29)
    at Converter.convertNode (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:1588:32)
    at Converter.converter (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:87:29)
    at Converter.convertNode (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:1588:32)
    at Converter.converter (/home/sosukesuzuki/ghq/github.com/prettier/prettier/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:87:29)
```

### Additional Info

context: https://github.com/prettier/prettier/issues/16531

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
| `@typescript-eslint/parser`            | `X.Y.Z` |
| `@typescript-eslint/rule-tester`       | `X.Y.Z` |
| `@typescript-eslint/scope-manager`     | `X.Y.Z` |
| `@typescript-eslint/typescript-estree` | `X.Y.Z` |
| `@typescript-eslint/type-utils`        | `X.Y.Z` |
| `@typescript-eslint/utils`             | `X.Y.Z` |
| `TypeScript`                           | `X.Y.Z` |
| `ESLint`                               | `X.Y.Z` |
| `node`                                 | `X.Y.Z` |

**Comment by bradzacher** [comment]
I see in the thread they say

> This is not an edge case but a real use case

Both can be true - I think this is a one-in-a-billion, real usecase.
They have more chained binary expressions than the JS stack is large. That's massive and I doubt any other codebase has that many because it's insane in anything but generated code (even then - still insane).

I don't know if this is something we can solve without rewriting the converter tbh. Our conversion has been a recursive traversal of the tree since its inception.

We might be able to locally optimise this case to convert it to a loop? Not sure if it's really worth the effort to go down that route though, TBH.

An easy workaround - the user can split their code into multiple variables.
I also think that if they introduce some parentheses it should change how the expression is structured and thus reduce the stack size.

---

I'm happy if someone wants to do some investigation here to figure out the feasibility and work required for a fix. We can decide if it's worth the maintenance effort to add special case behaviour when we have some concrete info.

**Comment by fz6m** [comment]
Thank you for your reply.

I currently using workaround :

```ts
  const a = [
     'string',
     'string',
     'string',
     'string',
     'string',
     'string',
     // ... 1400+ strings
  ].join('')
```

As bradzacher said, this is a very rare case, it wasn't newly written but came from migrating Java code to the frontend (we want to move some backend logic to run on the frontend).
